

import { HSKWord } from './types';

export const HSK1_VOCABULARY: HSKWord[] = [
  { mandarin: '爱', pinyin: 'ài', vietnamese: 'yêu; thích' },
  { mandarin: '八', pinyin: 'bā', vietnamese: 'tám' },
  { mandarin: '爸爸', pinyin: 'baba', vietnamese: 'bố; cha' },
  { mandarin: '杯子', pinyin: 'bēizi', vietnamese: 'cốc; ly' },
  { mandarin: '北京', pinyin: 'Běijīng', vietnamese: 'Bắc Kinh' },
  { mandarin: '本', pinyin: 'běn', vietnamese: 'cuốn; quyển (lượng từ cho sách...)' },
  { mandarin: '不客气', pinyin: 'bú kèqi', vietnamese: 'đừng khách sáo; không có gì' },
  { mandarin: '不', pinyin: 'bù', vietnamese: 'không' },
  { mandarin: '菜', pinyin: 'cài', vietnamese: 'rau; món ăn' },
  { mandarin: '茶', pinyin: 'chá', vietnamese: 'trà' },
  { mandarin: '吃', pinyin: 'chī', vietnamese: 'ăn' },
  { mandarin: '出租车', pinyin: 'chūzūchē', vietnamese: 'xe taxi' },
  { mandarin: '打电话', pinyin: 'dǎ diànhuà', vietnamese: 'gọi điện thoại' },
  { mandarin: '大', pinyin: 'dà', vietnamese: 'to; lớn' },
  { mandarin: '的', pinyin: 'de', vietnamese: 'của (trợ từ)' },
  { mandarin: '点', pinyin: 'diǎn', vietnamese: 'giờ (đồng hồ)' },
  { mandarin: '电脑', pinyin: 'diànnǎo', vietnamese: 'máy vi tính' },
  { mandarin: '电视', pinyin: 'diànshì', vietnamese: 'ti vi' },
  { mandarin: '电影', pinyin: 'diànyǐng', vietnamese: 'điện ảnh; phim' },
  { mandarin: '东西', pinyin: 'dōngxi', vietnamese: 'đồ vật; thứ' },
  { mandarin: '都', pinyin: 'dōu', vietnamese: 'đều' },
  { mandarin: '读', pinyin: 'dú', vietnamese: 'đọc' },
  { mandarin: '对不起', pinyin: 'duìbuqǐ', vietnamese: 'xin lỗi' },
  { mandarin: '多', pinyin: 'duō', vietnamese: 'nhiều; bao nhiêu (hỏi tuổi/mức độ)' },
  { mandarin: '多少', pinyin: 'duōshao', vietnamese: 'bao nhiêu' },
  { mandarin: '儿子', pinyin: 'érzi', vietnamese: 'con trai' },
  { mandarin: '二', pinyin: 'èr', vietnamese: 'hai' },
  { mandarin: '饭店', pinyin: 'fàndiàn', vietnamese: 'nhà hàng; khách sạn' },
  { mandarin: '飞机', pinyin: 'fēijī', vietnamese: 'máy bay' },
  { mandarin: '分钟', pinyin: 'fēnzhōng', vietnamese: 'phút' },
  { mandarin: '高兴', pinyin: 'gāoxìng', vietnamese: 'vui vẻ; vui mừng' },
  { mandarin: '个', pinyin: 'gè', vietnamese: 'cái; con; người (lượng từ chung)' },
  { mandarin: '工作', pinyin: 'gōngzuò', vietnamese: 'công việc; làm việc' },
  { mandarin: '汉语', pinyin: 'Hànyǔ', vietnamese: 'Tiếng Hán; Tiếng Trung' },
  { mandarin: '好', pinyin: 'hǎo', vietnamese: 'tốt; được' },
  { mandarin: '号', pinyin: 'hào', vietnamese: 'ngày (trong tháng)' },
  { mandarin: '喝', pinyin: 'hē', vietnamese: 'uống' },
  { mandarin: '和', pinyin: 'hé', vietnamese: 'và; với' },
  { mandarin: '很', pinyin: 'hěn', vietnamese: 'rất' },
  { mandarin: '后面', pinyin: 'hòumiàn', vietnamese: 'phía sau' },
  { mandarin: '回', pinyin: 'huí', vietnamese: 'về' },
  { mandarin: '会', pinyin: 'huì', vietnamese: 'biết (qua học tập); có thể' },
  { mandarin: '几', pinyin: 'jǐ', vietnamese: 'mấy; bao nhiêu (hỏi số lượng ít)' },
  { mandarin: '家', pinyin: 'jiā', vietnamese: 'nhà; gia đình' },
  { mandarin: '叫', pinyin: 'jiào', vietnamese: 'gọi là; tên là' },
  { mandarin: '今天', pinyin: 'jīntiān', vietnamese: 'hôm nay' },
  { mandarin: '九', pinyin: 'jiǔ', vietnamese: 'chín' },
  { mandarin: '开', pinyin: 'kāi', vietnamese: 'lái (xe)' },
  { mandarin: '看', pinyin: 'kàn', vietnamese: 'nhìn; xem; đọc' },
  { mandarin: '看见', pinyin: 'kànjiàn', vietnamese: 'nhìn thấy' },
  { mandarin: '块', pinyin: 'kuài', vietnamese: 'đồng (tiền tệ); miếng' },
  { mandarin: '来', pinyin: 'lái', vietnamese: 'đến' },
  { mandarin: '老师', pinyin: 'lǎoshī', vietnamese: 'giáo viên' },
  { mandarin: '了', pinyin: 'le', vietnamese: 'rồi (trợ từ)' },
  { mandarin: '冷', pinyin: 'lěng', vietnamese: 'lạnh' },
  { mandarin: '里', pinyin: 'lǐ', vietnamese: 'bên trong' },
  { mandarin: '零', pinyin: 'líng', vietnamese: 'số không' },
  { mandarin: '六', pinyin: 'liù', vietnamese: 'sáu' },
  { mandarin: '妈妈', pinyin: 'māma', vietnamese: 'mẹ' },
  { mandarin: '吗', pinyin: 'ma', vietnamese: 'không (trợ từ nghi vấn)' },
  { mandarin: '买', pinyin: 'mǎi', vietnamese: 'mua' },
  { mandarin: '没关系', pinyin: 'méi guānxi', vietnamese: 'không sao; không có gì' },
  { mandarin: '没有', pinyin: 'méiyǒu', vietnamese: 'không có; chưa' },
  { mandarin: '米饭', pinyin: 'mǐfàn', vietnamese: 'cơm (gạo nấu chín)' },
  { mandarin: '明天', pinyin: 'míngtiān', vietnamese: 'ngày mai' },
  { mandarin: '名字', pinyin: 'míngzi', vietnamese: 'tên' },
  { mandarin: '哪', pinyin: 'nǎ', vietnamese: 'nào (dùng trước lượng từ)' },
  { mandarin: '哪儿', pinyin: 'nǎr', vietnamese: 'ở đâu' },
  { mandarin: '那(那儿)', pinyin: 'nà (nàr)', vietnamese: 'kia; đó; ở đó' },
  { mandarin: '呢', pinyin: 'ne', vietnamese: 'thì; vậy (trợ từ)' },
  { mandarin: '能', pinyin: 'néng', vietnamese: 'có thể' },
  { mandarin: '你', pinyin: 'nǐ', vietnamese: 'bạn; anh; chị (ngôi thứ 2)' },
  { mandarin: '年', pinyin: 'nián', vietnamese: 'năm' },
  { mandarin: '女儿', pinyin: "nǚ'ér", vietnamese: 'con gái' },
  { mandarin: '朋友', pinyin: 'péngyou', vietnamese: 'bạn bè' },
  { mandarin: '漂亮', pinyin: 'piàoliang', vietnamese: 'xinh đẹp; đẹp' },
  { mandarin: '苹果', pinyin: 'píngguǒ', vietnamese: 'quả táo' },
  { mandarin: '七', pinyin: 'qī', vietnamese: 'bảy' },
  { mandarin: '钱', pinyin: 'qián', vietnamese: 'tiền' },
  { mandarin: '前面', pinyin: 'qiánmiàn', vietnamese: 'phía trước' },
  { mandarin: '请', pinyin: 'qǐng', vietnamese: 'mời; xin vui lòng' },
  { mandarin: '去', pinyin: 'qù', vietnamese: 'đi' },
  { mandarin: '热', pinyin: 'rè', vietnamese: 'nóng' },
  { mandarin: '人', pinyin: 'rén', vietnamese: 'người' },
  { mandarin: '认识', pinyin: 'rènshi', vietnamese: 'quen biết' },
  { mandarin: '三', pinyin: 'sān', vietnamese: 'ba' },
  { mandarin: '商店', pinyin: 'shāngdiàn', vietnamese: 'cửa hàng' },
  { mandarin: '上', pinyin: 'shàng', vietnamese: 'trên; phía trên' },
  { mandarin: '上午', pinyin: 'shàngwǔ', vietnamese: 'buổi sáng' },
  { mandarin: '少', pinyin: 'shǎo', vietnamese: 'ít' },
  { mandarin: '谁', pinyin: 'shéi', vietnamese: 'ai' },
  { mandarin: '什么', pinyin: 'shénme', vietnamese: 'cái gì' },
  { mandarin: '十', pinyin: 'shí', vietnamese: 'mười' },
  { mandarin: '时候', pinyin: 'shíhou', vietnamese: 'khi; lúc' },
  { mandarin: '是', pinyin: 'shì', vietnamese: 'là; phải; vâng' },
  { mandarin: '书', pinyin: 'shū', vietnamese: 'sách' },
  { mandarin: '水', pinyin: 'shuǐ', vietnamese: 'nước' },
  { mandarin: '水果', pinyin: 'shuǐguǒ', vietnamese: 'hoa quả; trái cây' },
  { mandarin: '睡觉', pinyin: 'shuìjiào', vietnamese: 'ngủ' },
  { mandarin: '说', pinyin: 'shuō', vietnamese: 'nói' },
  { mandarin: '说话', pinyin: 'shuōhuà', vietnamese: 'nói chuyện' },
  { mandarin: '四', pinyin: 'sì', vietnamese: 'bốn' },
  { mandarin: '岁', pinyin: 'suì', vietnamese: 'tuổi' },
  { mandarin: '他', pinyin: 'tā', vietnamese: 'anh ấy; ông ấy' },
  { mandarin: '她', pinyin: 'tā', vietnamese: 'cô ấy; bà ấy' },
  { mandarin: '太', pinyin: 'tài', vietnamese: 'quá; lắm' },
  { mandarin: '天气', pinyin: 'tiānqì', vietnamese: 'thời tiết' },
  { mandarin: '听', pinyin: 'tīng', vietnamese: 'nghe' },
  { mandarin: '同学', pinyin: 'tóngxué', vietnamese: 'bạn học' },
  { mandarin: '喂', pinyin: 'wèi', vietnamese: 'alo (khi gọi điện)' },
  { mandarin: '我', pinyin: 'wǒ', vietnamese: 'tôi; tớ (ngôi thứ 1)' },
  { mandarin: '我们', pinyin: 'wǒmen', vietnamese: 'chúng tôi; chúng ta' },
  { mandarin: '五', pinyin: 'wǔ', vietnamese: 'năm' },
  { mandarin: '喜欢', pinyin: 'xǐhuan', vietnamese: 'thích' },
  { mandarin: '下', pinyin: 'xià', vietnamese: 'dưới; tiếp theo; rơi (mưa)' },
  { mandarin: '下午', pinyin: 'xiàwǔ', vietnamese: 'buổi chiều' },
  { mandarin: '下雨', pinyin: 'xià yǔ', vietnamese: 'mưa; trời mưa' },
  { mandarin: '先生', pinyin: 'xiānsheng', vietnamese: 'ngài; ông; chồng' },
  { mandarin: '现在', pinyin: 'xiànzài', vietnamese: 'bây giờ' },
  { mandarin: '想', pinyin: 'xiǎng', vietnamese: 'muốn; nghĩ; nhớ' },
  { mandarin: '小', pinyin: 'xiǎo', vietnamese: 'nhỏ; bé' },
  { mandarin: '小姐', pinyin: 'xiǎojiě', vietnamese: 'cô; tiểu thư' },
  { mandarin: '些', pinyin: 'xiē', vietnamese: 'một vài; một ít' },
  { mandarin: '写', pinyin: 'xiě', vietnamese: 'viết' },
  { mandarin: '谢谢', pinyin: 'xièxie', vietnamese: 'cảm ơn' },
  { mandarin: '星期', pinyin: 'xīngqī', vietnamese: 'tuần; thứ' },
  { mandarin: '学生', pinyin: 'xuésheng', vietnamese: 'học sinh; sinh viên' },
  { mandarin: '学习', pinyin: 'xuéxí', vietnamese: 'học tập' },
  { mandarin: '学校', pinyin: 'xuéxiào', vietnamese: 'trường học' },
  { mandarin: '一', pinyin: 'yī', vietnamese: 'một' },
  { mandarin: '一点儿', pinyin: 'yìdiǎnr', vietnamese: 'một chút; một ít' },
  { mandarin: '衣服', pinyin: 'yīfu', vietnamese: 'quần áo' },
  { mandarin: '医生', pinyin: 'yīshēng', vietnamese: 'bác sĩ' },
  { mandarin: '医院', pinyin: 'yīyuàn', vietnamese: 'bệnh viện' },
  { mandarin: '椅子', pinyin: 'yǐzi', vietnamese: 'ghế' },
  { mandarin: '有', pinyin: 'yǒu', vietnamese: 'có' },
  { mandarin: '月', pinyin: 'yuè', vietnamese: 'tháng; mặt trăng' },
  { mandarin: '再见', pinyin: 'zàijiàn', vietnamese: 'tạm biệt' },
  { mandarin: '在', pinyin: 'zài', vietnamese: 'ở; đang (làm gì)' },
  { mandarin: '怎么', pinyin: 'zěnme', vietnamese: 'như thế nào; sao' },
  { mandarin: '怎么样', pinyin: 'zěnmeyàng', vietnamese: 'thế nào; ra sao' },
  { mandarin: '这(这儿)', pinyin: 'zhè (zhèr)', vietnamese: 'đây; ở đây' },
  { mandarin: '中国', pinyin: 'Zhōngguó', vietnamese: 'Trung Quốc' },
  { mandarin: '中午', pinyin: 'zhōngwǔ', vietnamese: 'buổi trưa' },
  { mandarin: '住', pinyin: 'zhù', vietnamese: 'sống; ở' },
  { mandarin: '桌子', pinyin: 'zhuōzi', vietnamese: 'cái bàn' },
  { mandarin: '字', pinyin: 'zì', vietnamese: 'chữ' },
  { mandarin: '昨天', pinyin: 'zuótiān', vietnamese: 'hôm qua' },
  { mandarin: '坐', pinyin: 'zuò', vietnamese: 'ngồi; đi bằng (phương tiện)' },
  { mandarin: '做', pinyin: 'zuò', vietnamese: 'làm' },
];