import { HSKWord } from './types';

export const HSK2_VOCABULARY: HSKWord[] = [
  { mandarin: '吧', pinyin: 'ba', vietnamese: '(Trợ từ) nhé, nhỉ, đi, thôi (dùng cuối câu)' },
  { mandarin: '白', pinyin: 'bái', vietnamese: '(Tính từ) trắng' },
  { mandarin: '百', pinyin: 'bǎi', vietnamese: '(Số từ) một trăm' },
  { mandarin: '帮助', pinyin: 'bāngzhù', vietnamese: '(Động từ) giúp đỡ, hỗ trợ' },
  { mandarin: '报纸', pinyin: 'bàozhǐ', vietnamese: '(Danh từ) báo giấy' },
  { mandarin: '比', pinyin: 'bǐ', vietnamese: '(Giới từ) dùng để so sánh' },
  { mandarin: '别', pinyin: 'bié', vietnamese: '(Phó từ) đừng' },
  { mandarin: '长', pinyin: 'cháng', vietnamese: '(Tính từ) dài' },
  { mandarin: '唱歌', pinyin: 'chànggē', vietnamese: '(Động từ) hát' },
  { mandarin: '出', pinyin: 'chū', vietnamese: '(Động từ) ra, ra ngoài' },
  { mandarin: '穿', pinyin: 'chuān', vietnamese: '(Động từ) mặc, mang' },
  { mandarin: '次', pinyin: 'cì', vietnamese: '(Lượng từ) lần, lượt' },
  { mandarin: '从', pinyin: 'cóng', vietnamese: '(Giới từ) từ' },
  { mandarin: '错', pinyin: 'cuò', vietnamese: '(Tính từ) sai, sai lầm' },
  { mandarin: '打篮球', pinyin: 'dǎ lánqiú', vietnamese: '(Động từ) chơi bóng rổ' },
  { mandarin: '大家', pinyin: 'dàjiā', vietnamese: '(Đại từ) mọi người' },
  { mandarin: '到', pinyin: 'dào', vietnamese: '(Động từ) đến, tới' },
  { mandarin: '得', pinyin: 'de', vietnamese: '(Trợ từ) đánh dấu bổ ngữ' },
  { mandarin: '等', pinyin: 'děng', vietnamese: '(Động từ) đợi' },
  { mandarin: '弟弟', pinyin: 'dìdi', vietnamese: '(Danh từ) em trai' },
  { mandarin: '第一', pinyin: 'dì-yī', vietnamese: '(Số từ) thứ nhất, đầu tiên' },
  { mandarin: '懂', pinyin: 'dǒng', vietnamese: '(Động từ) hiểu' },
  { mandarin: '对', pinyin: 'duì', vietnamese: '(Tính từ) đúng' },
  { mandarin: '对', pinyin: 'duì', vietnamese: '(Giới từ) đối với, với' },
  { mandarin: '房间', pinyin: 'fángjiān', vietnamese: '(Danh từ) phòng' },
  { mandarin: '非常', pinyin: 'fēicháng', vietnamese: '(Phó từ) vô cùng, rất' },
  { mandarin: '服务员', pinyin: 'fúwùyuán', vietnamese: '(Danh từ) nhân viên phục vụ' },
  { mandarin: '高', pinyin: 'gāo', vietnamese: '(Tính từ) cao' },
  { mandarin: '告诉', pinyin: 'gàosu', vietnamese: '(Động từ) nói cho biết, bảo' },
  { mandarin: '哥哥', pinyin: 'gēge', vietnamese: '(Danh từ) anh trai' },
  { mandarin: '给', pinyin: 'gěi', vietnamese: '(Động từ) đưa cho, cho' },
  { mandarin: '公共汽车', pinyin: 'gōnggòngqìchē', vietnamese: '(Danh từ) xe buýt' },
  { mandarin: '公司', pinyin: 'gōngsī', vietnamese: '(Danh từ) công ty' },
  { mandarin: '狗', pinyin: 'gǒu', vietnamese: '(Danh từ) con chó' },
  { mandarin: '贵', pinyin: 'guì', vietnamese: '(Tính từ) đắt' },
  { mandarin: '过', pinyin: 'guo', vietnamese: '(Trợ từ) (đã) từng (dùng sau động từ)' },
  { mandarin: '还', pinyin: 'hái', vietnamese: '(Phó từ) vẫn, vẫn còn; còn, thêm' },
  { mandarin: '孩子', pinyin: 'háizi', vietnamese: '(Danh từ) con cái; trẻ con' },
  { mandarin: '好吃', pinyin: 'hǎochī', vietnamese: '(Tính từ) ngon' },
  { mandarin: '黑', pinyin: 'hēi', vietnamese: '(Tính từ) đen, tối' },
  { mandarin: '红', pinyin: 'hóng', vietnamese: '(Tính từ) đỏ' },
  { mandarin: '欢迎', pinyin: 'huānyíng', vietnamese: '(Động từ) hoan nghênh, chào mừng' },
  { mandarin: '回答', pinyin: 'huídá', vietnamese: '(Động từ) trả lời, giải đáp' },
  { mandarin: '火车站', pinyin: 'huǒchēzhàn', vietnamese: '(Danh từ) ga tàu hỏa' },
  { mandarin: '机场', pinyin: 'jīchǎng', vietnamese: '(Danh từ) sân bay' },
  { mandarin: '鸡蛋', pinyin: 'jīdàn', vietnamese: '(Danh từ) trứng gà' },
  { mandarin: '件', pinyin: 'jiàn', vietnamese: '(Lượng từ) chiếc, cái (dùng cho quần áo, sự việc)' },
  { mandarin: '教室', pinyin: 'jiàoshì', vietnamese: '(Danh từ) phòng học' },
  { mandarin: '姐姐', pinyin: 'jiějie', vietnamese: '(Danh từ) chị gái' },
  { mandarin: '介绍', pinyin: 'jièshào', vietnamese: '(Động từ) giới thiệu' },
  { mandarin: '进', pinyin: 'jìn', vietnamese: '(Động từ) vào' },
  { mandarin: '近', pinyin: 'jìn', vietnamese: '(Tính từ) gần' },
  { mandarin: '就', pinyin: 'jiù', vietnamese: '(Phó từ) thì, là, ngay' },
  { mandarin: '觉得', pinyin: 'juéde', vietnamese: '(Động từ) cảm thấy, cho rằng' },
  { mandarin: '咖啡', pinyin: 'kāfēi', vietnamese: '(Danh từ) cà phê' },
  { mandarin: '开始', pinyin: 'kāishǐ', vietnamese: '(Động từ) bắt đầu' },
  { mandarin: '考试', pinyin: 'kǎoshì', vietnamese: '(Danh từ) kỳ thi / (Động từ) thi' },
  { mandarin: '可能', pinyin: 'kěnéng', vietnamese: '(Động từ năng nguyện) có thể' },
  { mandarin: '可以', pinyin: 'kěyǐ', vietnamese: '(Động từ năng nguyện) có thể' },
  { mandarin: '课', pinyin: 'kè', vietnamese: '(Danh từ) bài học; lớp học' },
  { mandarin: '快', pinyin: 'kuài', vietnamese: '(Tính từ) nhanh; (Phó từ) sắp' },
  { mandarin: '快乐', pinyin: 'kuàilè', vietnamese: '(Tính từ) vui vẻ, hạnh phúc' },
  { mandarin: '累', pinyin: 'lèi', vietnamese: '(Tính từ) mệt' },
  { mandarin: '离', pinyin: 'lí', vietnamese: '(Giới từ) cách (xa)' },
  { mandarin: '两', pinyin: 'liǎng', vietnamese: '(Số từ) hai (dùng trước lượng từ)' },
  { mandarin: '路', pinyin: 'lù', vietnamese: '(Danh từ) đường; (Lượng từ) tuyến (xe)' },
  { mandarin: '旅游', pinyin: 'lǚyóu', vietnamese: '(Động từ) du lịch' },
  { mandarin: '卖', pinyin: 'mài', vietnamese: '(Động từ) bán' },
  { mandarin: '慢', pinyin: 'màn', vietnamese: '(Tính từ) chậm' },
  { mandarin: '忙', pinyin: 'máng', vietnamese: '(Tính từ) bận; (Động từ) bận rộn' },
  { mandarin: '猫', pinyin: 'māo', vietnamese: '(Danh từ) con mèo' },
  { mandarin: '每', pinyin: 'měi', vietnamese: '(Đại từ) mỗi' },
  { mandarin: '妹妹', pinyin: 'mèimei', vietnamese: '(Danh từ) em gái' },
  { mandarin: '门', pinyin: 'mén', vietnamese: '(Danh từ) cửa, cổng' },
  { mandarin: '男', pinyin: 'nán', vietnamese: '(Danh từ) nam, đàn ông' },
  { mandarin: '您', pinyin: 'nín', vietnamese: '(Đại từ) ngài, ông, bà (kính trọng)' },
  { mandarin: '牛奶', pinyin: 'niúnǎi', vietnamese: '(Danh từ) sữa bò' },
  { mandarin: '女', pinyin: 'nǚ', vietnamese: '(Danh từ) nữ, phụ nữ' },
  { mandarin: '旁边', pinyin: 'pángbiān', vietnamese: '(Danh từ) bên cạnh' },
  { mandarin: '跑步', pinyin: 'pǎobù', vietnamese: '(Động từ) chạy bộ' },
  { mandarin: '便宜', pinyin: 'piányi', vietnamese: '(Tính từ) rẻ' },
  { mandarin: '票', pinyin: 'piào', vietnamese: '(Danh từ) vé' },
  { mandarin: '妻子', pinyin: 'qīzi', vietnamese: '(Danh từ) vợ' },
  { mandarin: '起床', pinyin: 'qǐchuáng', vietnamese: '(Động từ) thức dậy' },
  { mandarin: '千', pinyin: 'qiān', vietnamese: '(Số từ) nghìn, ngàn' },
  { mandarin: '铅笔', pinyin: 'qiānbǐ', vietnamese: '(Danh từ) bút chì' },
  { mandarin: '晴', pinyin: 'qíng', vietnamese: '(Tính từ) trời trong, quang đãng' },
  { mandarin: '去年', pinyin: 'qùnián', vietnamese: '(Danh từ) năm ngoái' },
  { mandarin: '让', pinyin: 'ràng', vietnamese: '(Động từ) để, cho phép, bảo' },
  { mandarin: '日', pinyin: 'rì', vietnamese: '(Danh từ) ngày' },
  { mandarin: '上班', pinyin: 'shàngbān', vietnamese: '(Động từ) đi làm, vào làm' },
  { mandarin: '身体', pinyin: 'shēntǐ', vietnamese: '(Danh từ) cơ thể, sức khỏe' },
  { mandarin: '生病', pinyin: 'shēngbìng', vietnamese: '(Động từ) bị bệnh' },
  { mandarin: '生日', pinyin: 'shēngrì', vietnamese: '(Danh từ) sinh nhật' },
  { mandarin: '时间', pinyin: 'shíjiān', vietnamese: '(Danh từ) thời gian' },
  { mandarin: '事情', pinyin: 'shìqing', vietnamese: '(Danh từ) sự việc, công việc' },
  { mandarin: '手表', pinyin: 'shǒubiǎo', vietnamese: '(Danh từ) đồng hồ đeo tay' },
  { mandarin: '手机', pinyin: 'shǒujī', vietnamese: '(Danh từ) điện thoại di động' },
  { mandarin: '送', pinyin: 'sòng', vietnamese: '(Động từ) tặng; tiễn' },
  { mandarin: '虽然...但是...', pinyin: 'suīrán... dànshì...', vietnamese: '(Liên từ) tuy... nhưng...' },
  { mandarin: '它', pinyin: 'tā', vietnamese: '(Đại từ) nó (dùng cho đồ vật, động vật)' },
  { mandarin: '踢足球', pinyin: 'tī zúqiú', vietnamese: '(Động từ) đá bóng' },
  { mandarin: '题', pinyin: 'tí', vietnamese: '(Danh từ) câu hỏi, đề bài' },
  { mandarin: '跳舞', pinyin: 'tiàowǔ', vietnamese: '(Động từ) nhảy múa, khiêu vũ' },
  { mandarin: '外', pinyin: 'wài', vietnamese: '(Danh từ) bên ngoài' },
  { mandarin: '完', pinyin: 'wán', vietnamese: '(Động từ) xong, kết thúc' },
  { mandarin: '玩', pinyin: 'wán', vietnamese: '(Động từ) chơi' },
  { mandarin: '晚上', pinyin: 'wǎnshang', vietnamese: '(Danh từ) buổi tối' },
  { mandarin: '为什么', pinyin: 'wèi shénme', vietnamese: '(Đại từ) vì sao, tại sao' },
  { mandarin: '问', pinyin: 'wèn', vietnamese: '(Động từ) hỏi' },
  { mandarin: '问题', pinyin: 'wèntí', vietnamese: '(Danh từ) câu hỏi; vấn đề' },
  { mandarin: '西瓜', pinyin: 'xīguā', vietnamese: '(Danh từ) dưa hấu' },
  { mandarin: '希望', pinyin: 'xīwàng', vietnamese: '(Động từ) hy vọng, mong muốn' },
  { mandarin: '洗', pinyin: 'xǐ', vietnamese: '(Động từ) giặt, rửa' },
  { mandarin: '小时', pinyin: 'xiǎoshí', vietnamese: '(Danh từ) tiếng, giờ (đồng hồ)' },
  { mandarin: '笑', pinyin: 'xiào', vietnamese: '(Động từ) cười' },
  { mandarin: '新', pinyin: 'xīn', vietnamese: '(Tính từ) mới' },
  { mandarin: '姓', pinyin: 'xìng', vietnamese: '(Danh từ) họ; (Động từ) mang họ' },
  { mandarin: '休息', pinyin: 'xiūxi', vietnamese: '(Động từ) nghỉ ngơi' },
  { mandarin: '雪', pinyin: 'xuě', vietnamese: '(Danh từ) tuyết' },
  { mandarin: '颜色', pinyin: 'yánsè', vietnamese: '(Danh từ) màu sắc' },
  { mandarin: '眼睛', pinyin: 'yǎnjing', vietnamese: '(Danh từ) mắt' },
  { mandarin: '羊肉', pinyin: 'yángròu', vietnamese: '(Danh từ) thịt dê' },
  { mandarin: '药', pinyin: 'yào', vietnamese: '(Danh từ) thuốc' },
  { mandarin: '要', pinyin: 'yào', vietnamese: '(Động từ) muốn; yêu cầu; cần; phải' },
  { mandarin: '也', pinyin: 'yě', vietnamese: '(Phó từ) cũng' },
  { mandarin: '一下', pinyin: 'yíxià', vietnamese: '(Trợ từ) một chút (biểu thị hành động ngắn)' },
  { mandarin: '一起', pinyin: 'yìqǐ', vietnamese: '(Phó từ) cùng nhau' },
  { mandarin: '已经', pinyin: 'yǐjīng', vietnamese: '(Phó từ) đã' },
  { mandarin: '意思', pinyin: 'yìsi', vietnamese: '(Danh từ) ý nghĩa; ý kiến; sự thú vị' },
  { mandarin: '因为...所以...', pinyin: 'yīnwèi... suǒyǐ...', vietnamese: '(Liên từ) bởi vì... cho nên...' },
  { mandarin: '阴', pinyin: 'yīn', vietnamese: '(Tính từ) (trời) râm, âm u' },
  { mandarin: '游泳', pinyin: 'yóuyǒng', vietnamese: '(Động từ) bơi lội' },
  { mandarin: '右边', pinyin: 'yòubian', vietnamese: '(Danh từ) bên phải' },
  { mandarin: '鱼', pinyin: 'yú', vietnamese: '(Danh từ) con cá' },
  { mandarin: '远', pinyin: 'yuǎn', vietnamese: '(Tính từ) xa' },
  { mandarin: '运动', pinyin: 'yùndòng', vietnamese: '(Động từ) vận động, thể thao' },
  { mandarin: '再', pinyin: 'zài', vietnamese: '(Phó từ) lại, thêm, nữa' },
  { mandarin: '早上', pinyin: 'zǎoshang', vietnamese: '(Danh từ) buổi sáng' },
  { mandarin: '丈夫', pinyin: 'zhàngfu', vietnamese: '(Danh từ) chồng' },
  { mandarin: '找', pinyin: 'zhǎo', vietnamese: '(Động từ) tìm, tìm kiếm' },
  { mandarin: '着', pinyin: 'zhe', vietnamese: '(Trợ từ) (biểu thị hành động tiếp diễn)' },
  { mandarin: '真', pinyin: 'zhēn', vietnamese: '(Phó từ) thật, thật sự' },
  { mandarin: '正在', pinyin: 'zhèngzài', vietnamese: '(Phó từ) đang' },
  { mandarin: '知道', pinyin: 'zhīdào', vietnamese: '(Động từ) biết' },
  { mandarin: '准备', pinyin: 'zhǔnbèi', vietnamese: '(Động từ) chuẩn bị, dự định' },
  { mandarin: '自行车', pinyin: 'zìxíngchē', vietnamese: '(Danh từ) xe đạp' },
  { mandarin: '走', pinyin: 'zǒu', vietnamese: '(Động từ) đi bộ; rời đi' },
  { mandarin: '最', pinyin: 'zuì', vietnamese: '(Phó từ) nhất' },
  { mandarin: '左边', pinyin: 'zuǒbiān', vietnamese: '(Danh từ) bên trái' },
];