import { HSKWord } from './types';

export const HSK2_VOCABULARY: HSKWord[] = [
  { mandarin: '吧', pinyin: 'ba', vietnamese: '(Trợ từ) nhé, nhỉ, đi, thôi (dùng cuối câu)' },{ mandarin: '吧', pinyin: 'ba', vietnamese: 'đi, nhé, nhỉ (đứng cuối câu)' },
{ mandarin: '白', pinyin: 'bái', vietnamese: 'trắng' },
{ mandarin: '百', pinyin: 'bǎi', vietnamese: 'trăm' },
{ mandarin: '帮助', pinyin: 'bāngzhù', vietnamese: 'giúp đỡ' },
{ mandarin: '报纸', pinyin: 'bàozhǐ', vietnamese: 'báo' },
{ mandarin: '比', pinyin: 'bǐ', vietnamese: 'so sánh' },
{ mandarin: '别', pinyin: 'bié', vietnamese: 'đừng, khác biệt' },
{ mandarin: '长', pinyin: 'cháng', vietnamese: 'dài' },
{ mandarin: '唱歌', pinyin: 'chànggē', vietnamese: 'hát' },
{ mandarin: '出', pinyin: 'chū', vietnamese: 'ra ngoài' },
{ mandarin: '穿', pinyin: 'chuān', vietnamese: 'mặc' },
{ mandarin: '船', pinyin: 'chuán', vietnamese: 'thuyền' },
{ mandarin: '次', pinyin: 'cì', vietnamese: 'lần' },
{ mandarin: '从', pinyin: 'cóng', vietnamese: 'từ, theo' },
{ mandarin: '错', pinyin: 'cuò', vietnamese: 'sai' },
{ mandarin: '打篮球', pinyin: 'dǎ lánqiú', vietnamese: 'chơi bóng rổ' },
{ mandarin: '大家', pinyin: 'dàjiā', vietnamese: 'mọi người' },
{ mandarin: '但是', pinyin: 'dànshì', vietnamese: 'nhưng' },
{ mandarin: '到', pinyin: 'dào', vietnamese: 'đến' },
{ mandarin: '得', pinyin: 'děi', vietnamese: 'phải, đạt được' },
{ mandarin: '等', pinyin: 'děng', vietnamese: 'đợi' },
{ mandarin: '弟弟', pinyin: 'dìdì', vietnamese: 'em trai' },
{ mandarin: '第一', pinyin: 'dì yī', vietnamese: 'đầu tiên' },
{ mandarin: '懂', pinyin: 'dǒng', vietnamese: 'hiểu' },
{ mandarin: '对', pinyin: 'duì', vietnamese: 'đúng, đối với' },
{ mandarin: '房间', pinyin: 'fángjiān', vietnamese: 'phòng' },
{ mandarin: '非常', pinyin: 'fēicháng', vietnamese: 'rất, cực kỳ' },
{ mandarin: '服务员', pinyin: 'fúwùyuán', vietnamese: 'nhân viên phục vụ' },
{ mandarin: '高', pinyin: 'gāo', vietnamese: 'cao' },
{ mandarin: '告诉', pinyin: 'gàosù', vietnamese: 'nói cho, thông báo' },
{ mandarin: '哥哥', pinyin: 'gēge', vietnamese: 'anh trai' },
{ mandarin: '给', pinyin: 'gěi', vietnamese: 'đưa cho, cho' },
{ mandarin: '公共汽车', pinyin: 'gōnggòng qìchē', vietnamese: 'xe buýt' },
{ mandarin: '公斤', pinyin: 'gōngjīn', vietnamese: 'kilogram (kg)' },
{ mandarin: '公司', pinyin: 'gōngsī', vietnamese: 'công ty' },
{ mandarin: '贵', pinyin: 'guì', vietnamese: 'đắt, quý' },
{ mandarin: '过', pinyin: 'guò', vietnamese: 'qua, đi qua' },
{ mandarin: '还', pinyin: 'hái', vietnamese: 'vẫn, còn' },
{ mandarin: '孩子', pinyin: 'háizi', vietnamese: 'trẻ con' },
{ mandarin: '好吃', pinyin: 'hǎochī', vietnamese: 'ngon' },
{ mandarin: '号', pinyin: 'hào', vietnamese: 'số (như số điện thoại, số nhà)' },
{ mandarin: '黑', pinyin: 'hēi', vietnamese: 'đen' },
{ mandarin: '红', pinyin: 'hóng', vietnamese: 'đỏ' },
{ mandarin: '欢迎', pinyin: 'huānyíng', vietnamese: 'hoan nghênh, chào mừng' },
{ mandarin: '回答', pinyin: 'huídá', vietnamese: 'trả lời' },
{ mandarin: '机场', pinyin: 'jīchǎng', vietnamese: 'sân bay' },
{ mandarin: '鸡蛋', pinyin: 'jīdàn', vietnamese: 'trứng gà' },
{ mandarin: '件', pinyin: 'jiàn', vietnamese: 'cái (dùng cho sự việc, quần áo)' },
{ mandarin: '教室', pinyin: 'jiàoshì', vietnamese: 'lớp học' },
{ mandarin: '姐姐', pinyin: 'jiějie', vietnamese: 'chị gái' },
{ mandarin: '介绍', pinyin: 'jièshào', vietnamese: 'giới thiệu' },
{ mandarin: '进', pinyin: 'jìn', vietnamese: 'vào' },
{ mandarin: '近', pinyin: 'jìn', vietnamese: 'gần' },
{ mandarin: '就', pinyin: 'jiù', vietnamese: 'thì, ngay' },
{ mandarin: '觉得', pinyin: 'juéde', vietnamese: 'cảm thấy' },
{ mandarin: '咖啡', pinyin: 'kāfēi', vietnamese: 'cà phê' },
{ mandarin: '开始', pinyin: 'kāishǐ', vietnamese: 'bắt đầu' },
{ mandarin: '考试', pinyin: 'kǎoshì', vietnamese: 'thi' },
{ mandarin: '可能', pinyin: 'kěnéng', vietnamese: 'có thể' },
{ mandarin: '可以', pinyin: 'kěyǐ', vietnamese: 'có thể' },
{ mandarin: '课', pinyin: 'kè', vietnamese: 'bài học' },
{ mandarin: '快', pinyin: 'kuài', vietnamese: 'nhanh' },
{ mandarin: '快乐', pinyin: 'kuàilè', vietnamese: 'vui vẻ' },
{ mandarin: '累', pinyin: 'lèi', vietnamese: 'mệt' },
{ mandarin: '离', pinyin: 'lí', vietnamese: 'cách (khoảng cách), rời' },
{ mandarin: '两', pinyin: 'liǎng', vietnamese: 'hai (khi đếm số lượng)' },
{ mandarin: '路', pinyin: 'lù', vietnamese: 'đường' },
{ mandarin: '旅游', pinyin: 'lǚyóu', vietnamese: 'du lịch' },
{ mandarin: '卖', pinyin: 'mài', vietnamese: 'bán' },
{ mandarin: '慢', pinyin: 'màn', vietnamese: 'chậm' },
{ mandarin: '忙', pinyin: 'máng', vietnamese: 'bận' },
{ mandarin: '每', pinyin: 'měi', vietnamese: 'mỗi' },
{ mandarin: '妹妹', pinyin: 'mèimei', vietnamese: 'em gái' },
{ mandarin: '门', pinyin: 'mén', vietnamese: 'cửa' },
{ mandarin: '男人', pinyin: 'nánrén', vietnamese: 'đàn ông' },
{ mandarin: '您', pinyin: 'nín', vietnamese: 'bạn (dùng lịch sự)' },
{ mandarin: '牛奶', pinyin: 'niúnǎi', vietnamese: 'sữa bò' },
{ mandarin: '女人', pinyin: 'nǚrén', vietnamese: 'phụ nữ' },
{ mandarin: '旁边', pinyin: 'pángbiān', vietnamese: 'bên cạnh' },
{ mandarin: '跑步', pinyin: 'pǎobù', vietnamese: 'chạy bộ' },
{ mandarin: '便宜', pinyin: 'piányí', vietnamese: 'rẻ' },
{ mandarin: '票', pinyin: 'piào', vietnamese: 'vé' },
{ mandarin: '妻子', pinyin: 'qīzi', vietnamese: 'vợ' },
{ mandarin: '起床', pinyin: 'qǐchuáng', vietnamese: 'dậy (rời khỏi giường)' },
{ mandarin: '千', pinyin: 'qiān', vietnamese: 'nghìn' },
{ mandarin: '晴', pinyin: 'qíng', vietnamese: 'nắng, quang đãng' },
{ mandarin: '去年', pinyin: 'qùnián', vietnamese: 'năm ngoái' },
{ mandarin: '让', pinyin: 'ràng', vietnamese: 'để, làm cho, nhường' },
{ mandarin: '上班', pinyin: 'shàngbān', vietnamese: 'đi làm' },
{ mandarin: '身体', pinyin: 'shēntǐ', vietnamese: 'cơ thể' },
{ mandarin: '生病', pinyin: 'shēngbìng', vietnamese: 'bị bệnh' },
{ mandarin: '生日', pinyin: 'shēngrì', vietnamese: 'sinh nhật' },
{ mandarin: '时间', pinyin: 'shíjiān', vietnamese: 'thời gian' },
{ mandarin: '事情', pinyin: 'shìqíng', vietnamese: 'việc' },
{ mandarin: '手表', pinyin: 'shǒubiǎo', vietnamese: 'đồng hồ' },
{ mandarin: '手机', pinyin: 'shǒujī', vietnamese: 'điện thoại di động' },
{ mandarin: '送', pinyin: 'sòng', vietnamese: 'tặng' },
{ mandarin: '所以', pinyin: 'suǒyǐ', vietnamese: 'vì vậy' },
{ mandarin: '它', pinyin: 'tā', vietnamese: 'nó (cho vật, động vật)' },
{ mandarin: '踢足球', pinyin: 'tī zúqiú', vietnamese: 'đá bóng' },
{ mandarin: '题', pinyin: 'tí', vietnamese: 'câu hỏi, đề bài' },
{ mandarin: '跳舞', pinyin: 'tiàowǔ', vietnamese: 'nhảy múa' },
{ mandarin: '外', pinyin: 'wài', vietnamese: 'ngoài' },
{ mandarin: '玩', pinyin: 'wán', vietnamese: 'chơi' },
{ mandarin: '完', pinyin: 'wán', vietnamese: 'xong, hoàn thành' },
{ mandarin: '晚上', pinyin: 'wǎnshàng', vietnamese: 'buổi tối' },
{ mandarin: '为什么', pinyin: 'wèishénme', vietnamese: 'tại sao' },
{ mandarin: '问', pinyin: 'wèn', vietnamese: 'hỏi' },
{ mandarin: '问题', pinyin: 'wèntí', vietnamese: 'vấn đề' },
{ mandarin: '西瓜', pinyin: 'xīguā', vietnamese: 'dưa hấu' },
{ mandarin: '希望', pinyin: 'xīwàng', vietnamese: 'hy vọng' },
{ mandarin: '洗', pinyin: 'xǐ', vietnamese: 'rửa' },
{ mandarin: '向', pinyin: 'xiàng', vietnamese: 'hướng về, đối với' },
{ mandarin: '小时', pinyin: 'xiǎoshí', vietnamese: 'tiếng đồng hồ' },
{ mandarin: '笑', pinyin: 'xiào', vietnamese: 'cười' },
{ mandarin: '新', pinyin: 'xīn', vietnamese: 'mới' },
{ mandarin: '姓', pinyin: 'xìng', vietnamese: 'họ' },
{ mandarin: '休息', pinyin: 'xiūxi', vietnamese: 'nghỉ ngơi' },
{ mandarin: '雪', pinyin: 'xuě', vietnamese: 'tuyết' },
{ mandarin: '颜色', pinyin: 'yánsè', vietnamese: 'màu sắc' },
{ mandarin: '眼睛', pinyin: 'yǎnjing', vietnamese: 'mắt' },
{ mandarin: '羊肉', pinyin: 'yángròu', vietnamese: 'thịt cừu' },
{ mandarin: '要', pinyin: 'yào', vietnamese: 'muốn, cần' },
{ mandarin: '药', pinyin: 'yào', vietnamese: 'thuốc' },
{ mandarin: '也', pinyin: 'yě', vietnamese: 'cũng' },
{ mandarin: '已经', pinyin: 'yǐjīng', vietnamese: 'đã' },
{ mandarin: '一起', pinyin: 'yìqǐ', vietnamese: 'cùng nhau' },
{ mandarin: '意思', pinyin: 'yìsi', vietnamese: 'ý nghĩa' },
{ mandarin: '阴', pinyin: 'yīn', vietnamese: 'âm u, trời nhiều mây' },
{ mandarin: '因为', pinyin: 'yīnwèi', vietnamese: 'vì' },
{ mandarin: '游泳', pinyin: 'yóuyǒng', vietnamese: 'bơi' },
{ mandarin: '右边', pinyin: 'yòubiān', vietnamese: 'bên phải' },
{ mandarin: '鱼', pinyin: 'yú', vietnamese: 'cá' },
{ mandarin: '元', pinyin: 'yuán', vietnamese: 'Đồng (đơn vị tiền tệ)' },
{ mandarin: '远', pinyin: 'yuǎn', vietnamese: 'xa' },
{ mandarin: '运动', pinyin: 'yùndòng', vietnamese: 'vận' },
{ mandarin: '再', pinyin: 'zài', vietnamese: 'lại' },
{ mandarin: '早上', pinyin: 'zǎoshàng', vietnamese: 'buổi sáng' },
{ mandarin: '张', pinyin: 'zhāng', vietnamese: 'tờ, bức (dùng cho vật phẳng, giấy, tranh, bàn)' },
{ mandarin: '丈夫', pinyin: 'zhàngfu', vietnamese: 'chồng' },
{ mandarin: '找', pinyin: 'zhǎo', vietnamese: 'tìm' },
{ mandarin: '着', pinyin: 'zhe', vietnamese: 'đang (dùng để chỉ trạng thái hiện tại)' },
{ mandarin: '真', pinyin: 'zhēn', vietnamese: 'thật' },
{ mandarin: '正在', pinyin: 'zhèngzài', vietnamese: 'đang' },
{ mandarin: '知道', pinyin: 'zhīdào', vietnamese: 'biết' },
{ mandarin: '准备', pinyin: 'zhǔnbèi', vietnamese: 'chuẩn bị' },
{ mandarin: '自行车', pinyin: 'zìxíngchē', vietnamese: 'xe đạp' },
{ mandarin: '走', pinyin: 'zǒu', vietnamese: 'đi' },
{ mandarin: '最', pinyin: 'zuì', vietnamese: 'nhất (so sánh nhất)' },
{ mandarin: '左边', pinyin: 'zuǒbiān', vietnamese: 'bên trái' },
];