import { HSKWord } from './types';

export const HSK3_VOCABULARY: HSKWord[] = [
  { mandarin: '阿姨', pinyin: 'āyí', vietnamese: 'dì, cô' },
{ mandarin: '啊', pinyin: 'a', vietnamese: 'a, à, ơ (trợ từ ngữ khí)' },
{ mandarin: '矮', pinyin: 'ǎi', vietnamese: 'thấp, lùn' },
{ mandarin: '爱好', pinyin: 'àihào', vietnamese: 'sở thích' },
{ mandarin: '安静', pinyin: 'ānjìng', vietnamese: 'yên tĩnh' },
{ mandarin: '把', pinyin: 'bǎ', vietnamese: 'đem, lấy (giới từ)' },
{ mandarin: '班', pinyin: 'bān', vietnamese: 'lớp, ca (làm việc)' },
{ mandarin: '搬', pinyin: 'bān', vietnamese: 'chuyển, dời' },
{ mandarin: '半', pinyin: 'bàn', vietnamese: 'một nửa' },
{ mandarin: '办法', pinyin: 'bànfǎ', vietnamese: 'biện pháp' },
{ mandarin: '办公室', pinyin: 'bàngōngshì', vietnamese: 'văn phòng' },
{ mandarin: '帮忙', pinyin: 'bāngmáng', vietnamese: 'giúp đỡ (động từ li hợp)' },
{ mandarin: '包', pinyin: 'bāo', vietnamese: 'túi, bao' },
{ mandarin: '饱', pinyin: 'bǎo', vietnamese: 'no' },
{ mandarin: '北方', pinyin: 'běifāng', vietnamese: 'miền Bắc' },
{ mandarin: '被', pinyin: 'bèi', vietnamese: 'bị, được (giới từ bị động)' },
{ mandarin: '比较', pinyin: 'bǐjiào', vietnamese: 'khá, tương đối' },
{ mandarin: '比赛', pinyin: 'bǐsài', vietnamese: 'cuộc thi, thi đấu' },
{ mandarin: '必须', pinyin: 'bìxū', vietnamese: 'phải, cần phải' },
{ mandarin: '变化', pinyin: 'biànhuà', vietnamese: 'thay đổi' },
{ mandarin: '表示', pinyin: 'biǎoshì', vietnamese: 'biểu thị, thể hiện' },
{ mandarin: '表演', pinyin: 'biǎoyǎn', vietnamese: 'biểu diễn' },
{ mandarin: '别人', pinyin: 'biérén', vietnamese: 'người khác' },
{ mandarin: '宾馆', pinyin: 'bīnguǎn', vietnamese: 'khách sạn' },
{ mandarin: '冰箱', pinyin: 'bīngxiāng', vietnamese: 'tủ lạnh' },
{ mandarin: '才', pinyin: 'cái', vietnamese: 'mới (nhấn mạnh thời gian muộn, trễ)' },
{ mandarin: '菜单', pinyin: 'càidān', vietnamese: 'thực đơn' },
{ mandarin: '参加', pinyin: 'cānjiā', vietnamese: 'tham gia' },
{ mandarin: '草', pinyin: 'cǎo', vietnamese: 'cỏ' },
{ mandarin: '层', pinyin: 'céng', vietnamese: 'tầng' },
{ mandarin: '差', pinyin: 'chà', vietnamese: 'kém, thiếu, tệ' },
{ mandarin: '超市', pinyin: 'chāoshì', vietnamese: 'siêu thị' },
{ mandarin: '衬衫', pinyin: 'chènshān', vietnamese: 'áo sơ mi' },
{ mandarin: '成绩', pinyin: 'chéngjì', vietnamese: 'thành tích' },
{ mandarin: '城市', pinyin: 'chéngshì', vietnamese: 'thành phố' },
{ mandarin: '迟到', pinyin: 'chídào', vietnamese: 'đến trễ' },
{ mandarin: '出现', pinyin: 'chūxiàn', vietnamese: 'xuất hiện' },
{ mandarin: '厨房', pinyin: 'chúfáng', vietnamese: 'nhà bếp' },
{ mandarin: '除了', pinyin: 'chúle', vietnamese: 'ngoài ra, trừ ra' },
{ mandarin: '春', pinyin: 'chūn', vietnamese: 'mùa xuân' },
{ mandarin: '词语', pinyin: 'cíyǔ', vietnamese: 'từ ngữ' },
{ mandarin: '聪明', pinyin: 'cōngmíng', vietnamese: 'thông minh' },
{ mandarin: '打扫', pinyin: 'dǎsǎo', vietnamese: 'quét dọn' },
{ mandarin: '打算', pinyin: 'dǎsuàn', vietnamese: 'dự định' },
{ mandarin: '带', pinyin: 'dài', vietnamese: 'mang theo, dẫn theo' },
{ mandarin: '担心', pinyin: 'dānxīn', vietnamese: 'lo lắng' },
{ mandarin: '蛋糕', pinyin: 'dàngāo', vietnamese: 'bánh ngọt' },
{ mandarin: '当然', pinyin: 'dāngrán', vietnamese: 'đương nhiên' },
{ mandarin: '地', pinyin: 'de', vietnamese: 'trợ từ của động từ' },
{ mandarin: '灯', pinyin: 'dēng', vietnamese: 'đèn' },
{ mandarin: '低', pinyin: 'dī', vietnamese: 'thấp' },
{ mandarin: '地方', pinyin: 'dìfāng', vietnamese: 'nơi, chỗ' },
{ mandarin: '地铁', pinyin: 'dìtiě', vietnamese: 'tàu điện ngầm' },
{ mandarin: '地图', pinyin: 'dìtú', vietnamese: 'bản đồ' },
{ mandarin: '电梯', pinyin: 'diàntī', vietnamese: 'thang máy' },
{ mandarin: '电子邮箱', pinyin: 'diànzǐ yóuxiāng', vietnamese: 'hộp thư điện tử (email)' },
{ mandarin: '东', pinyin: 'dōng', vietnamese: 'đông (hướng đông)' },
{ mandarin: '冬', pinyin: 'dōng', vietnamese: 'mùa đông' },
{ mandarin: '动物', pinyin: 'dòngwù', vietnamese: 'động vật' },
{ mandarin: '短', pinyin: 'duǎn', vietnamese: 'ngắn' },
{ mandarin: '段', pinyin: 'duàn', vietnamese: 'đoạn, quãng' },
{ mandarin: '锻炼', pinyin: 'duànliàn', vietnamese: 'luyện tập, rèn luyện' },
{ mandarin: '多么', pinyin: 'duōme', vietnamese: 'bao nhiêu, biết bao' },
{ mandarin: '饿', pinyin: 'è', vietnamese: 'đói' },
{ mandarin: '而且', pinyin: 'érqiě', vietnamese: 'mà còn, hơn nữa' },
{ mandarin: '耳朵', pinyin: 'ěrduo', vietnamese: 'tai' },
{ mandarin: '发烧', pinyin: 'fāshāo', vietnamese: 'sốt' },
{ mandarin: '发现', pinyin: 'fāxiàn', vietnamese: 'phát hiện' },
{ mandarin: '方便', pinyin: 'fāngbiàn', vietnamese: 'thuận tiện' },
{ mandarin: '放', pinyin: 'fàng', vietnamese: 'đặt, để' },
{ mandarin: '放心', pinyin: 'fàngxīn', vietnamese: 'yên tâm' },
{ mandarin: '分', pinyin: 'fēn', vietnamese: 'phút, phân' },
{ mandarin: '附近', pinyin: 'fùjìn', vietnamese: 'gần đây, vùng lân cận' },
{ mandarin: '复习', pinyin: 'fùxí', vietnamese: 'ôn tập' },
{ mandarin: '干净', pinyin: 'gānjìng', vietnamese: 'sạch sẽ' },
{ mandarin: '敢', pinyin: 'gǎn', vietnamese: 'dám' },
{ mandarin: '感冒', pinyin: 'gǎnmào', vietnamese: 'cảm mạo, cảm lạnh' },
{ mandarin: '刚才', pinyin: 'gāngcái', vietnamese: 'vừa mới' },
{ mandarin: '跟', pinyin: 'gēn', vietnamese: 'cùng với' },
{ mandarin: '根据', pinyin: 'gēnjù', vietnamese: 'căn cứ vào' },
{ mandarin: '更', pinyin: 'gèng', vietnamese: 'hơn, càng' },
{ mandarin: '公园', pinyin: 'gōngyuán', vietnamese: 'công viên' },
{ mandarin: '故事', pinyin: 'gùshì', vietnamese: 'câu chuyện' },
{ mandarin: '刮风', pinyin: 'guā fēng', vietnamese: 'gió thổi' },
{ mandarin: '关', pinyin: 'guān', vietnamese: 'đóng, tắt' },
{ mandarin: '关系', pinyin: 'guānxì', vietnamese: 'quan hệ' },
{ mandarin: '关心', pinyin: 'guānxīn', vietnamese: 'quan tâm' },
{ mandarin: '关于', pinyin: 'guānyú', vietnamese: 'về (liên quan đến)' },
{ mandarin: '国家', pinyin: 'guójiā', vietnamese: 'quốc gia' },
{ mandarin: '果汁', pinyin: 'guǒzhī', vietnamese: 'nước ép trái cây' },
{ mandarin: '过去', pinyin: 'guòqù', vietnamese: 'quá khứ' },
{ mandarin: '还是', pinyin: 'háishì', vietnamese: 'vẫn còn, hay là' },
{ mandarin: '害怕', pinyin: 'hàipà', vietnamese: 'sợ' },
{ mandarin: '河', pinyin: 'hé', vietnamese: 'sông' },
{ mandarin: '黑板', pinyin: 'hēibǎn', vietnamese: 'bảng' },
{ mandarin: '护照', pinyin: 'hùzhào', vietnamese: 'hộ chiếu' },
{ mandarin: '花', pinyin: 'huā', vietnamese: 'hoa, tiêu (tiền, thời gian)' },
{ mandarin: '花园', pinyin: 'huāyuán', vietnamese: 'vườn hoa' },
{ mandarin: '画', pinyin: 'huà', vietnamese: 'vẽ, tranh' },
{ mandarin: '坏', pinyin: 'huài', vietnamese: 'hỏng, xấu' },
{ mandarin: '还', pinyin: 'huán', vietnamese: 'trả lại, hoàn' },
{ mandarin: '环境', pinyin: 'huánjìng', vietnamese: 'môi trường' },
{ mandarin: '换', pinyin: 'huàn', vietnamese: 'đổi' },
{ mandarin: '黄', pinyin: 'huáng', vietnamese: 'màu vàng' },
{ mandarin: '会议', pinyin: 'huìyì', vietnamese: 'hội nghị, cuộc họp' },
{ mandarin: '或者', pinyin: 'huòzhě', vietnamese: 'hoặc là' },
{ mandarin: '机会', pinyin: 'jīhuì', vietnamese: 'cơ hội' },
{ mandarin: '几乎', pinyin: 'jīhū', vietnamese: 'hầu như, gần như' },
{ mandarin: '极', pinyin: 'jí', vietnamese: 'cực kỳ' },
{ mandarin: '记得', pinyin: 'jìdé', vietnamese: 'nhớ, nhớ đến' },
{ mandarin: '季节', pinyin: 'jìjié', vietnamese: 'mùa' },
{ mandarin: '检查', pinyin: 'jiǎnchá', vietnamese: 'kiểm tra' },
{ mandarin: '简单', pinyin: 'jiǎndān', vietnamese: 'đơn giản' },
{ mandarin: '健康', pinyin: 'jiànkāng', vietnamese: 'khỏe mạnh' },
{ mandarin: '见面', pinyin: 'jiànmiàn', vietnamese: 'gặp mặt' },
{ mandarin: '讲', pinyin: 'jiǎng', vietnamese: 'nói, giảng' },
{ mandarin: '教', pinyin: 'jiāo', vietnamese: 'dạy' },
{ mandarin: '角', pinyin: 'jiǎo', vietnamese: 'góc' },
{ mandarin: '脚', pinyin: 'jiǎo', vietnamese: 'chân' },
{ mandarin: '接', pinyin: 'jiē', vietnamese: 'nhận, tiếp' },
{ mandarin: '街道', pinyin: 'jiēdào', vietnamese: 'đường phố' },
{ mandarin: '结婚', pinyin: 'jiéhūn', vietnamese: 'kết hôn' },
{ mandarin: '结束', pinyin: 'jiéshù', vietnamese: 'kết thúc' },
{ mandarin: '节目', pinyin: 'jiémù', vietnamese: 'chương trình' },
{ mandarin: '节日', pinyin: 'jiérì', vietnamese: 'ngày lễ' },
{ mandarin: '解决', pinyin: 'jiějué', vietnamese: 'giải quyết' },
{ mandarin: '借', pinyin: 'jiè', vietnamese: 'mượn' },
{ mandarin: '经常', pinyin: 'jīngcháng', vietnamese: 'thường xuyên' },
{ mandarin: '经过', pinyin: 'jīngguò', vietnamese: 'trải qua' },
{ mandarin: '经历', pinyin: 'jīnglì', vietnamese: 'kinh nghiệm' },
{ mandarin: '久', pinyin: 'jiǔ', vietnamese: 'lâu' },
{ mandarin: '旧', pinyin: 'jiù', vietnamese: 'cũ' },
{ mandarin: '举行', pinyin: 'jǔxíng', vietnamese: 'tổ chức' },
{ mandarin: '句子', pinyin: 'jùzi', vietnamese: 'câu' },
{ mandarin: '决定', pinyin: 'juédìng', vietnamese: 'quyết định' },
{ mandarin: '可爱', pinyin: 'kě ài', vietnamese: 'đáng yêu' },
{ mandarin: '刻', pinyin: 'kè', vietnamese: 'khắc (15 phút)' },
{ mandarin: '客人', pinyin: 'kèrén', vietnamese: 'khách' },
{ mandarin: '空调', pinyin: 'kòngtiáo', vietnamese: 'máy điều hòa' },
{ mandarin: '口', pinyin: 'kǒu', vietnamese: 'miệng, khẩu' },
{ mandarin: '哭', pinyin: 'kū', vietnamese: 'khóc' },
{ mandarin: '裤子', pinyin: 'kùzi', vietnamese: 'quần' },
{ mandarin: '筷子', pinyin: 'kuàizi', vietnamese: 'đũa' },
{ mandarin: '蓝', pinyin: 'lán', vietnamese: 'màu xanh' },
{ mandarin: '老', pinyin: 'lǎo', vietnamese: 'già, cũ' },
{ mandarin: '离开', pinyin: 'líkāi', vietnamese: 'rời khỏi' },
{ mandarin: '礼物', pinyin: 'lǐwù', vietnamese: 'quà' },
{ mandarin: '历史', pinyin: 'lìshǐ', vietnamese: 'lịch sử' },
{ mandarin: '脸', pinyin: 'liǎn', vietnamese: 'mặt' },
{ mandarin: '练习', pinyin: 'liànxí', vietnamese: 'luyện tập' },
{ mandarin: '辆', pinyin: 'liàng', vietnamese: 'chiếc (xe)' },
{ mandarin: '了解', pinyin: 'liǎojiě', vietnamese: 'hiểu rõ' },
{ mandarin: '邻居', pinyin: 'línjū', vietnamese: 'hàng xóm' },
{ mandarin: '楼', pinyin: 'lóu', vietnamese: 'tòa nhà' },
{ mandarin: '马', pinyin: 'mǎ', vietnamese: 'con ngựa' },
{ mandarin: '马上', pinyin: 'mǎshàng', vietnamese: 'ngay lập tức' },
{ mandarin: '满意', pinyin: 'mǎnyì', vietnamese: 'hài lòng' },
{ mandarin: '帽子', pinyin: 'màozi', vietnamese: 'mũ' },
{ mandarin: '米', pinyin: 'mǐ', vietnamese: 'gạo, mét' },
{ mandarin: '面包', pinyin: 'miànbāo', vietnamese: 'bánh mì' },
{ mandarin: '面条', pinyin: 'miàntiáo', vietnamese: 'mì sợi' },
{ mandarin: '明白', pinyin: 'míngbái', vietnamese: 'hiểu rõ' },
{ mandarin: '拿', pinyin: 'ná', vietnamese: 'cầm, lấy' },
{ mandarin: '奶奶', pinyin: 'nǎinai', vietnamese: 'bà nội' },
{ mandarin: '南', pinyin: 'nán', vietnamese: 'phía nam' },
{ mandarin: '难', pinyin: 'nán', vietnamese: 'khó' },
{ mandarin: '难过', pinyin: 'nánguò', vietnamese: 'buồn' },
{ mandarin: '年级', pinyin: 'niánjí', vietnamese: 'lớp, năm học' },
{ mandarin: '年轻', pinyin: 'niánqīng', vietnamese: 'trẻ' },
{ mandarin: '鸟', pinyin: 'niǎo', vietnamese: 'chim' },
{ mandarin: '努力', pinyin: 'nǔlì', vietnamese: 'nỗ lực, chăm chỉ' },
{ mandarin: '爬山', pinyin: 'páshān', vietnamese: 'leo núi' },
{ mandarin: '盘子', pinyin: 'pánzi', vietnamese: 'đĩa' },
{ mandarin: '胖', pinyin: 'pàng', vietnamese: 'béo' },
{ mandarin: '啤酒', pinyin: 'píjiǔ', vietnamese: 'bia' },
{ mandarin: '葡萄', pinyin: 'pútao', vietnamese: 'nho' },
{ mandarin: '普通话', pinyin: 'pǔtōnghuà', vietnamese: 'tiếng Phổ thông (tiếng Trung chuẩn)' },
{ mandarin: '骑', pinyin: 'qí', vietnamese: 'cưỡi, đi (xe đạp, xe máy)' },
{ mandarin: '其实', pinyin: 'qíshí', vietnamese: 'thực ra' },
{ mandarin: '其他', pinyin: 'qítā', vietnamese: 'khác' },
{ mandarin: '奇怪', pinyin: 'qíguài', vietnamese: 'kỳ lạ' },
{ mandarin: '铅笔', pinyin: 'qiānbǐ', vietnamese: 'bút chì' },
{ mandarin: '清楚', pinyin: 'qīngchǔ', vietnamese: 'rõ ràng' },
{ mandarin: '秋', pinyin: 'qiū', vietnamese: 'mùa thu' },
{ mandarin: '裙子', pinyin: 'qúnzi', vietnamese: 'váy' },
{ mandarin: '然后', pinyin: 'ránhòu', vietnamese: 'sau đó' },
{ mandarin: '热情', pinyin: 'rèqíng', vietnamese: 'nhiệt tình' },
{ mandarin: '认为', pinyin: 'rènwéi', vietnamese: 'cho rằng' },
{ mandarin: '认真', pinyin: 'rènzhēn', vietnamese: 'nghiêm túc' },
{ mandarin: '容易', pinyin: 'róngyì', vietnamese: 'dễ dàng' },
{ mandarin: '如果', pinyin: 'rúguǒ', vietnamese: 'nếu như' },
{ mandarin: '伞', pinyin: 'sǎn', vietnamese: 'ô, dù' },
{ mandarin: '上网', pinyin: 'shàngwǎng', vietnamese: 'lên mạng' },
{ mandarin: '生气', pinyin: 'shēngqì', vietnamese: 'giận dữ' },
{ mandarin: '声音', pinyin: 'shēngyīn', vietnamese: 'âm thanh' },
{ mandarin: '使', pinyin: 'shǐ', vietnamese: 'khiến, làm cho' },
{ mandarin: '世界', pinyin: 'shìjiè', vietnamese: 'thế giới' },
{ mandarin: '瘦', pinyin: 'shòu', vietnamese: 'gầy' },
{ mandarin: '舒服', pinyin: 'shūfu', vietnamese: 'thoải mái' },
{ mandarin: '叔叔', pinyin: 'shūshu', vietnamese: 'chú' },
{ mandarin: '树', pinyin: 'shù', vietnamese: 'cây' },
{ mandarin: '数学', pinyin: 'shùxué', vietnamese: 'toán học' },
{ mandarin: '刷牙', pinyin: 'shuāyá', vietnamese: 'đánh răng' },
{ mandarin: '双', pinyin: 'shuāng', vietnamese: 'đôi' },
{ mandarin: '水平', pinyin: 'shuǐpíng', vietnamese: 'trình độ' },
{ mandarin: '司机', pinyin: 'sījī', vietnamese: 'lái xe, tài xế' },
{ mandarin: '虽然', pinyin: 'suīrán', vietnamese: 'tuy rằng' },
{ mandarin: '太阳', pinyin: 'tàiyáng', vietnamese: 'mặt trời' },
{ mandarin: '糖', pinyin: 'táng', vietnamese: 'kẹo, đường' },
{ mandarin: '特别', pinyin: 'tèbié', vietnamese: 'đặc biệt' },
{ mandarin: '疼', pinyin: 'téng', vietnamese: 'đau' },
{ mandarin: '提高', pinyin: 'tígāo', vietnamese: 'nâng cao' },
{ mandarin: '体育', pinyin: 'tǐyù', vietnamese: 'thể dục, thể thao' },
{ mandarin: '甜', pinyin: 'tián', vietnamese: 'ngọt' },
{ mandarin: '条', pinyin: 'tiáo', vietnamese: 'sợi, cái' },
{ mandarin: '同事', pinyin: 'tóngshì', vietnamese: 'đồng nghiệp' },
{ mandarin: '同意', pinyin: 'tóngyì', vietnamese: 'đồng ý' },
{ mandarin: '头发', pinyin: 'tóufa', vietnamese: 'tóc' },
{ mandarin: '突然', pinyin: 'tūrán', vietnamese: 'đột nhiên' },
{ mandarin: '图书馆', pinyin: 'túshūguǎn', vietnamese: 'thư viện' },
{ mandarin: '腿', pinyin: 'tuǐ', vietnamese: 'chân' },
{ mandarin: '完成', pinyin: 'wánchéng', vietnamese: 'hoàn thành' },
{ mandarin: '碗', pinyin: 'wǎn', vietnamese: 'bát' },
{ mandarin: '万', pinyin: 'wàn', vietnamese: 'vạn, mười nghìn' },
{ mandarin: '忘记', pinyin: 'wàngjì', vietnamese: 'quên' },
{ mandarin: '位', pinyin: 'wèi', vietnamese: 'vị, ngài' },
{ mandarin: '为', pinyin: 'wèi', vietnamese: 'vì' },
{ mandarin: '为了', pinyin: 'wèile', vietnamese: 'để, vì' },
{ mandarin: '文化', pinyin: 'wénhuà', vietnamese: 'văn hóa' },
{ mandarin: '西', pinyin: 'xī', vietnamese: 'phía tây' },
{ mandarin: '习惯', pinyin: 'xíguàn', vietnamese: 'thói quen' },
{ mandarin: '洗手间', pinyin: 'xǐshǒujiān', vietnamese: 'nhà vệ sinh' },
{ mandarin: '洗澡', pinyin: 'xǐzǎo', vietnamese: 'tắm' },
{ mandarin: '喜欢', pinyin: 'xǐhuān', vietnamese: 'thích' },
{ mandarin: '现在', pinyin: 'xiànzài', vietnamese: 'hiện' },
{ mandarin: '香蕉', pinyin: 'xiāngjiāo', vietnamese: 'chuối' },
{ mandarin: '相同', pinyin: 'xiāngtóng', vietnamese: 'giống nhau' },
{ mandarin: '相信', pinyin: 'xiāngxìn', vietnamese: 'tin tưởng' },
{ mandarin: '像', pinyin: 'xiàng', vietnamese: 'giống' },
{ mandarin: '小心', pinyin: 'xiǎoxīn', vietnamese: 'cẩn thận' },
{ mandarin: '校长', pinyin: 'xiàozhǎng', vietnamese: 'hiệu trưởng' },
{ mandarin: '鞋', pinyin: 'xié', vietnamese: 'giày' },
{ mandarin: '新闻', pinyin: 'xīnwén', vietnamese: 'tin tức' },
{ mandarin: '新鲜', pinyin: 'xīnxiān', vietnamese: 'tươi mới' },
{ mandarin: '信', pinyin: 'xìn', vietnamese: 'thư, tin tưởng' },
{ mandarin: '行李箱', pinyin: 'xínglǐxiāng', vietnamese: 'vali' },
{ mandarin: '兴趣', pinyin: 'xìngqù', vietnamese: 'hứng thú' },
{ mandarin: '熊猫', pinyin: 'xióngmāo', vietnamese: 'gấu trúc' },
{ mandarin: '需要', pinyin: 'xūyào', vietnamese: 'cần' },
{ mandarin: '选择', pinyin: 'xuǎnzé', vietnamese: 'lựa chọn' },
{ mandarin: '眼镜', pinyin: 'yǎnjìng', vietnamese: 'kính' },
{ mandarin: '要求', pinyin: 'yāoqiú', vietnamese: 'yêu cầu' },
{ mandarin: '爷爷', pinyin: 'yéye', vietnamese: 'ông nội' },
{ mandarin: '一定', pinyin: 'yīdìng', vietnamese: 'nhất định' },
{ mandarin: '一共', pinyin: 'yīgòng', vietnamese: 'tổng cộng' },
{ mandarin: '一会儿', pinyin: 'yīhuìr', vietnamese: 'một lát' },
{ mandarin: '一样', pinyin: 'yīyàng', vietnamese: 'giống nhau' },
{ mandarin: '以后', pinyin: 'yǐhòu', vietnamese: 'sau này' },
{ mandarin: '以前', pinyin: 'yǐqián', vietnamese: 'trước đây' },
{ mandarin: '以为', pinyin: 'yǐwéi', vietnamese: 'cho rằng' },
{ mandarin: '一般', pinyin: 'yībān', vietnamese: 'thông thường' },
{ mandarin: '一边', pinyin: 'yībiān', vietnamese: 'vừa ... vừa ...' },
{ mandarin: '一直', pinyin: 'yīzhí', vietnamese: 'luôn luôn' },
{ mandarin: '音乐', pinyin: 'yīnyuè', vietnamese: 'âm nhạc' },
{ mandarin: '银行', pinyin: 'yínháng', vietnamese: 'ngân hàng' },
{ mandarin: '应该', pinyin: 'yīnggāi', vietnamese: 'nên' },
{ mandarin: '影响', pinyin: 'yǐngxiǎng', vietnamese: 'ảnh hưởng' },
{ mandarin: '用', pinyin: 'yòng', vietnamese: 'dùng' },
{ mandarin: '游戏', pinyin: 'yóuxì', vietnamese: 'trò chơi' },
{ mandarin: '又', pinyin: 'yòu', vietnamese: 'lại, vừa' },
{ mandarin: '有名', pinyin: 'yǒumíng', vietnamese: 'nổi tiếng' },
{ mandarin: '遇到', pinyin: 'yùdào', vietnamese: 'gặp phải' },
{ mandarin: '月亮', pinyin: 'yuèliàng', vietnamese: 'mặt trăng' },
{ mandarin: '云', pinyin: 'yún', vietnamese: 'mây' },
{ mandarin: '站', pinyin: 'zhàn', vietnamese: 'đứng, trạm' },
{ mandarin: '长', pinyin: 'zhǎng', vietnamese: 'dài' },
{ mandarin: '着急', pinyin: 'zhāojí', vietnamese: 'lo lắng' },
{ mandarin: '照顾', pinyin: 'zhàogu', vietnamese: 'chăm sóc' },
{ mandarin: '照片', pinyin: 'zhàopiàn', vietnamese: 'bức ảnh' },
{ mandarin: '照相机', pinyin: 'zhàoxiàngjī', vietnamese: 'máy ảnh' },
{ mandarin: '只', pinyin: 'zhǐ', vietnamese: 'chỉ' },
{ mandarin: '中间', pinyin: 'zhōngjiān', vietnamese: 'ở giữa' },
{ mandarin: '终于', pinyin: 'zhōngyú', vietnamese: 'cuối cùng' },
{ mandarin: '种', pinyin: 'zhǒng', vietnamese: 'loại, hạt giống' },
{ mandarin: '重要', pinyin: 'zhòngyào', vietnamese: 'quan trọng' },
{ mandarin: '主要', pinyin: 'zhǔyào', vietnamese: 'chủ yếu' },
{ mandarin: '周末', pinyin: 'zhōumò', vietnamese: 'cuối tuần' },
{ mandarin: '祝', pinyin: 'zhù', vietnamese: 'chúc' },
{ mandarin: '注意', pinyin: 'zhùyì', vietnamese: 'chú ý' },
{ mandarin: '字典', pinyin: 'zìdiǎn', vietnamese: 'từ điển' },
{ mandarin: '自己', pinyin: 'zìjǐ', vietnamese: 'bản thân' },
{ mandarin: '总是', pinyin: 'zǒngshì', vietnamese: 'luôn luôn' },
{ mandarin: '最近', pinyin: 'zuìjìn', vietnamese: 'gần đây' },
{ mandarin: '作业', pinyin: 'zuòyè', vietnamese: 'bài tập về nhà' },
{ mandarin: '作用', pinyin: 'zuòyòng', vietnamese: 'tác dụng, vai trò' },
];