import { HSKWord } from './types';

export const HSK3_VOCABULARY: HSKWord[] = [
  { mandarin: '阿姨', pinyin: 'āyí', vietnamese: 'Dì, cô (gọi phụ nữ trung niên)' },
  { mandarin: '啊', pinyin: 'a', vietnamese: 'Thán từ (biểu thị ngạc nhiên, cảm thán)' },
  { mandarin: '矮', pinyin: 'ǎi', vietnamese: 'Thấp, lùn' },
  { mandarin: '爱好', pinyin: 'àihào', vietnamese: 'Sở thích; đam mê' },
  { mandarin: '安静', pinyin: 'ānjìng', vietnamese: 'Yên tĩnh, tĩnh lặng' },
  { mandarin: '把', pinyin: 'bǎ', vietnamese: 'Giới từ (dùng trước tân ngữ)' },
  { mandarin: '班', pinyin: 'bān', vietnamese: 'Lớp học, khóa học' },
  { mandarin: '搬', pinyin: 'bān', vietnamese: 'Chuyển, dời' },
  { mandarin: '办法', pinyin: 'bànfǎ', vietnamese: 'Biện pháp, cách làm' },
  { mandarin: '办公室', pinyin: 'bàngōngshì', vietnamese: 'Văn phòng' },
  { mandarin: '半', pinyin: 'bàn', vietnamese: 'Một nửa' },
  { mandarin: '帮忙', pinyin: 'bāngmáng', vietnamese: 'Giúp đỡ' },
  { mandarin: '包', pinyin: 'bāo', vietnamese: 'Cái túi, túi xách' },
  { mandarin: '饱', pinyin: 'bǎo', vietnamese: 'No (ăn no)' },
  { mandarin: '北方', pinyin: 'běifāng', vietnamese: 'Phía Bắc' },
  { mandarin: '被', pinyin: 'bèi', vietnamese: 'Giới từ (biểu thị bị động)' },
  { mandarin: '鼻子', pinyin: 'bízi', vietnamese: 'Cái mũi' },
  { mandarin: '比较', pinyin: 'bǐjiào', vietnamese: 'Tương đối, khá là' },
  { mandarin: '比赛', pinyin: 'bǐsài', vietnamese: 'Cuộc thi, trận đấu' },
  { mandarin: '笔记本', pinyin: 'bǐjìběn', vietnamese: 'Sổ ghi chép; Máy tính xách tay' },
  { mandarin: '必须', pinyin: 'bìxū', vietnamese: 'Phải, nhất định phải' },
  { mandarin: '变化', pinyin: 'biànhuà', vietnamese: 'Sự thay đổi; thay đổi' },
  { mandarin: '别人', pinyin: 'biéren', vietnamese: 'Người khác' },
  { mandarin: '宾馆', pinyin: 'bīnguǎn', vietnamese: 'Nhà nghỉ, khách sạn' },
  { mandarin: '冰箱', pinyin: 'bīngxiāng', vietnamese: 'Tủ lạnh' },
  { mandarin: '不但...而且...', pinyin: 'bú dàn... érqiě...', vietnamese: 'Không những... mà còn...' },
  { mandarin: '才', pinyin: 'cái', vietnamese: 'Mới (chỉ sự việc vừa xảy ra hoặc muộn)' },
  { mandarin: '菜单', pinyin: 'càidān', vietnamese: 'Thực đơn' },
  { mandarin: '参加', pinyin: 'cānjiā', vietnamese: 'Tham gia' },
  { mandarin: '草', pinyin: 'cǎo', vietnamese: 'Cỏ' },
  { mandarin: '层', pinyin: 'céng', vietnamese: 'Tầng, lớp' },
  { mandarin: '差', pinyin: 'chà', vietnamese: 'Tồi, kém; thiếu' },
  { mandarin: '长', pinyin: 'cháng', vietnamese: 'Dài' },
  { mandarin: '超市', pinyin: 'chāoshì', vietnamese: 'Siêu thị' },
  { mandarin: '衬衫', pinyin: 'chènshān', vietnamese: 'Áo sơ mi' },
  { mandarin: '成绩', pinyin: 'chéngjī', vietnamese: 'Thành tích, kết quả' },
  { mandarin: '城市', pinyin: 'chéngshì', vietnamese: 'Thành phố' },
  { mandarin: '迟到', pinyin: 'chídào', vietnamese: 'Đến muộn' },
  { mandarin: '出现', pinyin: 'chūxiàn', vietnamese: 'Xuất hiện' },
  { mandarin: '除了', pinyin: 'chúle', vietnamese: 'Ngoài... ra (còn...)' },
  { mandarin: '船', pinyin: 'chuán', vietnamese: 'Thuyền, tàu' },
  { mandarin: '春', pinyin: 'chūn', vietnamese: 'Mùa xuân' },
  { mandarin: '词典', pinyin: 'cídiǎn', vietnamese: 'Từ điển' },
  { mandarin: '聪明', pinyin: 'cōngmíng', vietnamese: 'Thông minh' },
  { mandarin: '打扫', pinyin: 'dǎsǎo', vietnamese: 'Quét dọn, dọn dẹp' },
  { mandarin: '打算', pinyin: 'dǎsuan', vietnamese: 'Dự định, kế hoạch' },
  { mandarin: '带', pinyin: 'dài', vietnamese: 'Mang, dẫn' },
  { mandarin: '担心', pinyin: 'dānxīn', vietnamese: 'Lo lắng' },
  { mandarin: '蛋糕', pinyin: 'dàngāo', vietnamese: 'Bánh ngọt, bánh kem' },
  { mandarin: '当然', pinyin: 'dāngrán', vietnamese: 'Đương nhiên, tất nhiên' },
  { mandarin: '灯', pinyin: 'dēng', vietnamese: 'Cái đèn' },
  { mandarin: '地', pinyin: 'de', vietnamese: 'Trợ từ (bổ sung trạng ngữ)' },
  { mandarin: '地方', pinyin: 'dìfang', vietnamese: 'Địa phương, nơi chốn' },
  { mandarin: '地铁', pinyin: 'dìtiě', vietnamese: 'Tàu điện ngầm, metro' },
  { mandarin: '地图', pinyin: 'dìtú', vietnamese: 'Bản đồ' },
  { mandarin: '电梯', pinyin: 'diàntī', vietnamese: 'Thang máy' },
  { mandarin: '电子邮件', pinyin: 'diànzǐ yóujiàn', vietnamese: 'Thư điện tử, email' },
  { mandarin: '东', pinyin: 'dōng', vietnamese: 'Phía đông' },
  { mandarin: '冬', pinyin: 'dōng', vietnamese: 'Mùa đông' },
  { mandarin: '动物园', pinyin: 'dòngwùyuán', vietnamese: 'Vườn bách thú' },
  { mandarin: '短', pinyin: 'duǎn', vietnamese: 'Ngắn' },
  { mandarin: '段', pinyin: 'duàn', vietnamese: 'Đoạn (văn, thời gian, đường)' },
  { mandarin: '锻炼', pinyin: 'duànliàn', vietnamese: 'Rèn luyện, tập luyện' },
  { mandarin: '多么', pinyin: 'duōme', vietnamese: 'Biết bao, làm sao' },
  { mandarin: '饿', pinyin: 'è', vietnamese: 'Đói' },
  { mandarin: '耳朵', pinyin: 'ěrduo', vietnamese: 'Cái tai' },
  { mandarin: '发', pinyin: 'fā', vietnamese: 'Gửi (thư, email)' },
  { mandarin: '发烧', pinyin: 'fāshāo', vietnamese: 'Phát sốt, bị sốt' },
  { mandarin: '发现', pinyin: 'fāxiàn', vietnamese: 'Phát hiện, tìm ra' },
  { mandarin: '方便', pinyin: 'fāngbiàn', vietnamese: 'Tiện lợi, thuận tiện' },
  { mandarin: '放', pinyin: 'fàng', vietnamese: 'Đặt, để' },
  { mandarin: '放心', pinyin: 'fàngxīn', vietnamese: 'Yên tâm' },
  { mandarin: '分', pinyin: 'fēn', vietnamese: 'Phút; điểm; chia' },
  { mandarin: '附近', pinyin: 'fùjìn', vietnamese: 'Gần đây, lân cận' },
  { mandarin: '复习', pinyin: 'fùxí', vietnamese: 'Ôn tập' },
  { mandarin: '干净', pinyin: 'gānjìng', vietnamese: 'Sạch sẽ' },
  { mandarin: '感冒', pinyin: 'gǎnmào', vietnamese: 'Cảm cúm, bị cảm' },
  { mandarin: '感兴趣', pinyin: 'gǎn xìngqù', vietnamese: 'Có hứng thú' },
  { mandarin: '刚才', pinyin: 'gāngcái', vietnamese: 'Vừa rồi, lúc nãy' },
  { mandarin: '个子', pinyin: 'gèzi', vietnamese: 'Chiều cao' },
  { mandarin: '根据', pinyin: 'gēnjù', vietnamese: 'Căn cứ vào, dựa vào' },
  { mandarin: '跟', pinyin: 'gēn', vietnamese: 'Cùng, với' },
  { mandarin: '更', pinyin: 'gèng', vietnamese: 'Càng, hơn nữa' },
  { mandarin: '公斤', pinyin: 'gōngjīn', vietnamese: 'Kilogram' },
  { mandarin: '公园', pinyin: 'gōngyuán', vietnamese: 'Công viên' },
  { mandarin: '故事', pinyin: 'gùshi', vietnamese: 'Câu chuyện' },
  { mandarin: '刮风', pinyin: 'guāfēng', vietnamese: 'Gió thổi' },
  { mandarin: '关', pinyin: 'guān', vietnamese: 'Đóng, tắt' },
  { mandarin: '关系', pinyin: 'guānxì', vietnamese: 'Quan hệ' },
  { mandarin: '关心', pinyin: 'guānxīn', vietnamese: 'Quan tâm' },
  { mandarin: '关于', pinyin: 'guānyú', vietnamese: 'Về, liên quan đến' },
  { mandarin: '国家', pinyin: 'guójiā', vietnamese: 'Quốc gia, đất nước' },
  { mandarin: '过', pinyin: 'guò', vietnamese: 'Sống, trải qua' },
  { mandarin: '过去', pinyin: 'guòqù', vietnamese: 'Quá khứ' },
  { mandarin: '还是', pinyin: 'háishì', vietnamese: 'Vẫn, vẫn là; hay là' },
  { mandarin: '害怕', pinyin: 'hàipà', vietnamese: 'Sợ hãi' },
  { mandarin: '航班', pinyin: 'hángbān', vietnamese: 'Chuyến bay' },
  { mandarin: '黑板', pinyin: 'hēibǎn', vietnamese: 'Bảng đen' },
  { mandarin: '后来', pinyin: 'hòulái', vietnamese: 'Sau này, về sau' },
  { mandarin: '护照', pinyin: 'hùzhào', vietnamese: 'Hộ chiếu' },
  { mandarin: '花', pinyin: 'huā', vietnamese: 'Tiêu (tiền, thời gian)' },
  { mandarin: '花', pinyin: 'huā', vietnamese: 'Bông hoa, hoa' },
  { mandarin: '画', pinyin: 'huà', vietnamese: 'Vẽ; bức tranh' },
  { mandarin: '坏', pinyin: 'huài', vietnamese: 'Hỏng, xấu, tồi' },
  { mandarin: '还', pinyin: 'huán', vietnamese: 'Trả lại' },
  { mandarin: '环境', pinyin: 'huánjìng', vietnamese: 'Môi trường' },
  { mandarin: '换', pinyin: 'huàn', vietnamese: 'Đổi, thay' },
  { mandarin: '黄河', pinyin: 'Huánghé', vietnamese: 'Sông Hoàng Hà' },
  { mandarin: '会议', pinyin: 'huìyì', vietnamese: 'Cuộc họp' },
  { mandarin: '或者', pinyin: 'huòzhě', vietnamese: 'Hoặc là, hay là' },
  { mandarin: '几乎', pinyin: 'jīhū', vietnamese: 'Gần như, hầu như' },
  { mandarin: '机会', pinyin: 'jīhuì', vietnamese: 'Cơ hội' },
  { mandarin: '极', pinyin: 'jí', vietnamese: 'Cực kỳ, vô cùng' },
  { mandarin: '记得', pinyin: 'jìde', vietnamese: 'Nhớ' },
  { mandarin: '季节', pinyin: 'jìjié', vietnamese: 'Mùa' },
  { mandarin: '检查', pinyin: 'jiǎnchá', vietnamese: 'Kiểm tra' },
  { mandarin: '简单', pinyin: 'jiǎndān', vietnamese: 'Đơn giản' },
  { mandarin: '见面', pinyin: 'jiànmiàn', vietnamese: 'Gặp mặt' },
  { mandarin: '健康', pinyin: 'jiànkāng', vietnamese: 'Khỏe mạnh, sức khỏe' },
  { mandarin: '讲', pinyin: 'jiǎng', vietnamese: 'Giảng, nói' },
  { mandarin: '降落', pinyin: 'jiàngluò', vietnamese: 'Hạ cánh' },
  { mandarin: '角', pinyin: 'jiǎo', vietnamese: 'Hào (đơn vị tiền)' },
  { mandarin: '脚', pinyin: 'jiǎo', vietnamese: 'Cái chân, bàn chân' },
  { mandarin: '教', pinyin: 'jiāo', vietnamese: 'Dạy' },
  { mandarin: '接', pinyin: 'jiē', vietnamese: 'Đón, nhận' },
  { mandarin: '街道', pinyin: 'jiēdào', vietnamese: 'Đường phố' },
  { mandarin: '节目', pinyin: 'jiémù', vietnamese: 'Chương trình' },
  { mandarin: '节日', pinyin: 'jiérì', vietnamese: 'Ngày lễ, lễ hội' },
  { mandarin: '结婚', pinyin: 'jiéhūn', vietnamese: 'Kết hôn, cưới' },
  { mandarin: '结束', pinyin: 'jiéshù', vietnamese: 'Kết thúc, chấm dứt' },
  { mandarin: '解决', pinyin: 'jiějué', vietnamese: 'Giải quyết' },
  { mandarin: '借', pinyin: 'jiè', vietnamese: 'Mượn, cho mượn' },
  { mandarin: '经常', pinyin: 'jīngcháng', vietnamese: 'Thường xuyên' },
  { mandarin: '经过', pinyin: 'jīngguò', vietnamese: 'Trải qua; sau khi' },
  { mandarin: '经理', pinyin: 'jīnglǐ', vietnamese: 'Giám đốc, quản lý' },
  { mandarin: '久', pinyin: 'jiǔ', vietnamese: 'Lâu, thời gian dài' },
  { mandarin: '旧', pinyin: 'jiù', vietnamese: 'Cũ' },
  { mandarin: '句子', pinyin: 'jùzi', vietnamese: 'Câu' },
  { mandarin: '决定', pinyin: 'juédìng', vietnamese: 'Quyết định' },
  { mandarin: '可爱', pinyin: 'kě\'ài', vietnamese: 'Đáng yêu, dễ thương' },
  { mandarin: '渴', pinyin: 'kě', vietnamese: 'Khát' },
  { mandarin: '刻', pinyin: 'kè', vietnamese: 'Khắc (15 phút)' },
  { mandarin: '客人', pinyin: 'kèrén', vietnamese: 'Khách' },
  { mandarin: '空调', pinyin: 'kōngtiáo', vietnamese: 'Máy lạnh, điều hòa' },
  { mandarin: '口', pinyin: 'kǒu', vietnamese: 'Lượng từ (người, gia súc, vật có miệng)' },
  { mandarin: '哭', pinyin: 'kū', vietnamese: 'Khóc' },
  { mandarin: '裤子', pinyin: 'kùzi', vietnamese: 'Cái quần' },
  { mandarin: '筷子', pinyin: 'kuàizi', vietnamese: 'Đôi đũa' },
  { mandarin: '蓝', pinyin: 'lán', vietnamese: 'Màu xanh dương' },
  { mandarin: '老', pinyin: 'lǎo', vietnamese: 'Già' },
  { mandarin: '离开', pinyin: 'líkāi', vietnamese: 'Rời đi, cách' },
  { mandarin: '礼物', pinyin: 'lǐwù', vietnamese: 'Quà tặng' },
  { mandarin: '历史', pinyin: 'lìshǐ', vietnamese: 'Lịch sử' },
  { mandarin: '脸', pinyin: 'liǎn', vietnamese: 'Khuôn mặt' },
  { mandarin: '练习', pinyin: 'liànxí', vietnamese: 'Luyện tập; bài tập' },
  { mandarin: '辆', pinyin: 'liàng', vietnamese: 'Lượng từ (xe cộ)' },
  { mandarin: '聊天', pinyin: 'liáotiān', vietnamese: 'Trò chuyện' },
  { mandarin: '了解', pinyin: 'liǎojiě', vietnamese: 'Hiểu rõ, tìm hiểu' },
  { mandarin: '邻居', pinyin: 'línjū', vietnamese: 'Hàng xóm' },
  { mandarin: '留学', pinyin: 'liúxué', vietnamese: 'Du học' },
  { mandarin: '楼', pinyin: 'lóu', vietnamese: 'Lầu, tầng, tòa nhà' },
  { mandarin: '绿', pinyin: 'lǜ', vietnamese: 'Màu xanh lá' },
  { mandarin: '马', pinyin: 'mǎ', vietnamese: 'Ngựa' },
  { mandarin: '马上', pinyin: 'mǎshàng', vietnamese: 'Ngay lập tức' },
  { mandarin: '满意', pinyin: 'mǎnyì', vietnamese: 'Hài lòng' },
  { mandarin: '帽子', pinyin: 'màozi', vietnamese: 'Cái mũ' },
  { mandarin: '米', pinyin: 'mǐ', vietnamese: 'Mét' },
  { mandarin: '面包', pinyin: 'miànbāo', vietnamese: 'Bánh mì' },
  { mandarin: '面条', pinyin: 'miàntiáo', vietnamese: 'Mì sợi' },
  { mandarin: '明白', pinyin: 'míngbai', vietnamese: 'Hiểu, rõ ràng' },
  { mandarin: '拿', pinyin: 'ná', vietnamese: 'Cầm, lấy' },
  { mandarin: '奶奶', pinyin: 'nǎinai', vietnamese: 'Bà nội' },
  { mandarin: '南', pinyin: 'nán', vietnamese: 'Phía Nam' },
  { mandarin: '难', pinyin: 'nán', vietnamese: 'Khó' },
  { mandarin: '难过', pinyin: 'nánguò', vietnamese: 'Khó chịu, buồn bã' },
  { mandarin: '年级', pinyin: 'niánjí', vietnamese: 'Năm học, khối' },
  { mandarin: '年轻', pinyin: 'niánqīng', vietnamese: 'Trẻ' },
  { mandarin: '鸟', pinyin: 'niǎo', vietnamese: 'Chim' },
  { mandarin: '努力', pinyin: 'nǔlì', vietnamese: 'Nỗ lực, chăm chỉ' },
  { mandarin: '爬山', pinyin: 'páshān', vietnamese: 'Leo núi' },
  { mandarin: '盘子', pinyin: 'pánzi', vietnamese: 'Cái đĩa' },
  { mandarin: '胖', pinyin: 'pàng', vietnamese: 'Béo, mập' },
  { mandarin: '皮鞋', pinyin: 'píxié', vietnamese: 'Giày da' },
  { mandarin: '啤酒', pinyin: 'píjiǔ', vietnamese: 'Bia' },
  { mandarin: '普通话', pinyin: 'pǔtōnghuà', vietnamese: 'Tiếng Phổ thông' },
  { mandarin: '其实', pinyin: 'qíshí', vietnamese: 'Thực ra, kỳ thực' },
  { mandarin: '其他', pinyin: 'qítā', vietnamese: 'Khác, còn lại' },
  { mandarin: '奇怪', pinyin: 'qíguài', vietnamese: 'Kỳ lạ, quái lạ' },
  { mandarin: '骑', pinyin: 'qí', vietnamese: 'Cưỡi (xe, ngựa)' },
  { mandarin: '起飞', pinyin: 'qǐfēi', vietnamese: 'Cất cánh' },
  { mandarin: '清楚', pinyin: 'qīngchu', vietnamese: 'Rõ ràng; hiểu rõ' },
  { mandarin: '秋', pinyin: 'qiū', vietnamese: 'Mùa thu' },
  { mandarin: '裙子', pinyin: 'qúnzi', vietnamese: 'Cái váy, cái đầm' },
  { mandarin: '然后', pinyin: 'ránhòu', vietnamese: 'Sau đó' },
  { mandarin: '热情', pinyin: 'rèqíng', vietnamese: 'Nhiệt tình' },
  { mandarin: '认为', pinyin: 'rènwéi', vietnamese: 'Cho rằng, nghĩ rằng' },
  { mandarin: '认真', pinyin: 'rènzhēn', vietnamese: 'Nghiêm túc, chăm chỉ' },
  { mandarin: '容易', pinyin: 'róngyì', vietnamese: 'Dễ, dễ dàng' },
  { mandarin: '如果', pinyin: 'rúguǒ', vietnamese: 'Nếu, nếu như' },
  { mandarin: '伞', pinyin: 'sǎn', vietnamese: 'Cái ô, cái dù' },
  { mandarin: '上网', pinyin: 'shàngwǎng', vietnamese: 'Lên mạng, online' },
  { mandarin: '生气', pinyin: 'shēngqì', vietnamese: 'Tức giận' },
  { mandarin: '声音', pinyin: 'shēngyīn', vietnamese: 'Âm thanh, giọng nói' },
  { mandarin: '世界', pinyin: 'shìjiè', vietnamese: 'Thế giới' },
  { mandarin: '试', pinyin: 'shì', vietnamese: 'Thử' },
  { mandarin: '瘦', pinyin: 'shòu', vietnamese: 'Gầy' },
  { mandarin: '叔叔', pinyin: 'shūshu', vietnamese: 'Chú' },
  { mandarin: '舒服', pinyin: 'shūfu', vietnamese: 'Thoải mái, dễ chịu' },
  { mandarin: '树', pinyin: 'shù', vietnamese: 'Cái cây' },
  { mandarin: '数学', pinyin: 'shùxué', vietnamese: 'Toán học' },
  { mandarin: '刷牙', pinyin: 'shuāyá', vietnamese: 'Đánh răng' },
  { mandarin: '双', pinyin: 'shuāng', vietnamese: 'Đôi, cặp' },
  { mandarin: '水平', pinyin: 'shuǐpíng', vietnamese: 'Trình độ' },
  { mandarin: '司机', pinyin: 'sījī', vietnamese: 'Tài xế, lái xe' },
  { mandarin: '太阳', pinyin: 'tàiyáng', vietnamese: 'Mặt trời' },
  { mandarin: '特别', pinyin: 'tèbié', vietnamese: 'Đặc biệt, rất' },
  { mandarin: '疼', pinyin: 'téng', vietnamese: 'Đau' },
  { mandarin: '提高', pinyin: 'tígāo', vietnamese: 'Nâng cao, cải thiện' },
  { mandarin: '体育', pinyin: 'tǐyù', vietnamese: 'Thể thao' },
  { mandarin: '甜', pinyin: 'tián', vietnamese: 'Ngọt' },
  { mandarin: '条', pinyin: 'tiáo', vietnamese: 'Lượng từ (vật dài, quần, cá)' },
  { mandarin: '同事', pinyin: 'tóngshì', vietnamese: 'Đồng nghiệp' },
  { mandarin: '同意', pinyin: 'tóngyì', vietnamese: 'Đồng ý' },
  { mandarin: '头发', pinyin: 'tóufa', vietnamese: 'Tóc' },
  { mandarin: '突然', pinyin: 'túrán', vietnamese: 'Đột nhiên' },
  { mandarin: '图书馆', pinyin: 'túshūguǎn', vietnamese: 'Thư viện' },
  { mandarin: '腿', pinyin: 'tuǐ', vietnamese: 'Cái chân' },
  { mandarin: '完成', pinyin: 'wánchéng', vietnamese: 'Hoàn thành' },
  { mandarin: '碗', pinyin: 'wǎn', vietnamese: 'Cái bát, chén; bát (lượng từ)' },
  { mandarin: '万', pinyin: 'wàn', vietnamese: 'Vạn, mười nghìn' },
  { mandarin: '忘记', pinyin: 'wàngjì', vietnamese: 'Quên' },
  { mandarin: '为', pinyin: 'wèi', vietnamese: 'Là, trở thành' },
  { mandarin: '为了', pinyin: 'wèile', vietnamese: 'Vì, để' },
  { mandarin: '位', pinyin: 'wèi', vietnamese: 'Vị (lượng từ lịch sự)' },
  { mandarin: '文化', pinyin: 'wénhuà', vietnamese: 'Văn hóa' },
  { mandarin: '西', pinyin: 'xī', vietnamese: 'Phía Tây' },
  { mandarin: '习惯', pinyin: 'xíguàn', vietnamese: 'Thói quen; quen' },
  { mandarin: '洗手间', pinyin: 'xǐshǒujiān', vietnamese: 'Nhà vệ sinh' },
  { mandarin: '洗澡', pinyin: 'xǐzǎo', vietnamese: 'Tắm' },
  { mandarin: '夏', pinyin: 'xià', vietnamese: 'Mùa hè' },
  { mandarin: '先', pinyin: 'xiān', vietnamese: 'Trước, trước hết' },
  { mandarin: '相信', pinyin: 'xiāngxìn', vietnamese: 'Tin tưởng' },
  { mandarin: '香蕉', pinyin: 'xiāngjiāo', vietnamese: 'Chuối' },
  { mandarin: '向', pinyin: 'xiàng', vietnamese: 'Hướng về, về phía' },
  { mandarin: '像', pinyin: 'xiàng', vietnamese: 'Giống' },
  { mandarin: '小心', pinyin: 'xiǎoxīn', vietnamese: 'Cẩn thận' },
  { mandarin: '校长', pinyin: 'xiàozhǎng', vietnamese: 'Hiệu trưởng' },
  { mandarin: '新闻', pinyin: 'xīnwén', vietnamese: 'Tin tức' },
  { mandarin: '新鲜', pinyin: 'xīnxiān', vietnamese: 'Tươi, tươi mới' },
  { mandarin: '信用卡', pinyin: 'xìnyòngkǎ', vietnamese: 'Thẻ tín dụng' },
  { mandarin: '行李箱', pinyin: 'xínglixiāng', vietnamese: 'Vali hành lý' },
  { mandarin: '熊猫', pinyin: 'xióngmāo', vietnamese: 'Gấu trúc' },
  { mandarin: '需要', pinyin: 'xūyào', vietnamese: 'Cần, nhu cầu' },
  { mandarin: '选择', pinyin: 'xuǎnzé', vietnamese: 'Lựa chọn' },
  { mandarin: '要求', pinyin: 'yāoqiú', vietnamese: 'Yêu cầu' },
  { mandarin: '爷爷', pinyin: 'yéye', vietnamese: 'Ông nội' },
  { mandarin: '一定', pinyin: 'yídìng', vietnamese: 'Nhất định' },
  { mandarin: '一共', pinyin: 'yígòng', vietnamese: 'Tổng cộng' },
  { mandarin: '一会儿', pinyin: 'yíhuìr', vietnamese: 'Một lát, một chút' },
  { mandarin: '一样', pinyin: 'yíyàng', vietnamese: 'Giống nhau' },
  { mandarin: '一般', pinyin: 'yìbān', vietnamese: 'Bình thường, thông thường' },
  { mandarin: '一边', pinyin: 'yìbiān', vietnamese: 'Vừa... vừa...' },
  { mandarin: '一直', pinyin: 'yìzhí', vietnamese: 'Luôn luôn, thẳng' },
  { mandarin: '以前', pinyin: 'yǐqián', vietnamese: 'Trước đây, trước kia' },
  { mandarin: '音乐', pinyin: 'yīnyuè', vietnamese: 'Âm nhạc' },
  { mandarin: '银行', pinyin: 'yínháng', vietnamese: 'Ngân hàng' },
  { mandarin: '饮料', pinyin: 'yǐnliào', vietnamese: 'Đồ uống' },
  { mandarin: '应该', pinyin: 'yīnggāi', vietnamese: 'Nên' },
  { mandarin: '影响', pinyin: 'yǐngxiǎng', vietnamese: 'Ảnh hưởng' },
  { mandarin: '用', pinyin: 'yòng', vietnamese: 'Dùng' },
  { mandarin: '游戏', pinyin: 'yóuxì', vietnamese: 'Trò chơi' },
  { mandarin: '有名', pinyin: 'yǒumíng', vietnamese: 'Nổi tiếng' },
  { mandarin: '又', pinyin: 'yòu', vietnamese: 'Lại (tái diễn)' },
  { mandarin: '遇到', pinyin: 'yùdào', vietnamese: 'Gặp, bắt gặp' },
  { mandarin: '元', pinyin: 'yuán', vietnamese: 'Tệ (đơn vị tiền)' },
  { mandarin: '愿意', pinyin: 'yuànyì', vietnamese: 'Bằng lòng, sẵn lòng' },
  { mandarin: '月亮', pinyin: 'yuèliang', vietnamese: 'Mặt trăng' },
  { mandarin: '越...越...', pinyin: 'yuè... yuè...', vietnamese: 'Càng... càng...' },
  { mandarin: '站', pinyin: 'zhàn', vietnamese: 'Đứng; trạm, bến' },
  { mandarin: '张', pinyin: 'zhāng', vietnamese: 'Lượng từ (giấy, bàn, mặt); mở' },
  { mandarin: '照顾', pinyin: 'zhàogù', vietnamese: 'Chăm sóc' },
  { mandarin: '照片', pinyin: 'zhàopiàn', vietnamese: 'Ảnh, bức ảnh' },
  { mandarin: '照相机', pinyin: 'zhàoxiàngjī', vietnamese: 'Máy ảnh' },
  { mandarin: '只', pinyin: 'zhī', vietnamese: 'Lượng từ (con vật, đồ vật theo cặp)' },
  { mandarin: '只', pinyin: 'zhǐ', vietnamese: 'Chỉ, chỉ là' },
  { mandarin: '中间', pinyin: 'zhōngjiān', vietnamese: 'Ở giữa' },
  { mandarin: '中文', pinyin: 'Zhōngwén', vietnamese: 'Tiếng Trung' },
  { mandarin: '终于', pinyin: 'zhōngyú', vietnamese: 'Cuối cùng' },
  { mandarin: '种', pinyin: 'zhǒng', vietnamese: 'Loại, chủng loại' },
  { mandarin: '重要', pinyin: 'zhòngyào', vietnamese: 'Quan trọng' },
  { mandarin: '周末', pinyin: 'zhōumò', vietnamese: 'Cuối tuần' },
  { mandarin: '主要', pinyin: 'zhǔyào', vietnamese: 'Chủ yếu' },
  { mandarin: '注意', pinyin: 'zhùyì', vietnamese: 'Chú ý' },
  { mandarin: '着急', pinyin: 'zháojí', vietnamese: 'Lo lắng, sốt ruột' },
  { mandarin: '自己', pinyin: 'zìjǐ', vietnamese: 'Chính mình' },
  { mandarin: '总是', pinyin: 'zǒngshì', vietnamese: 'Luôn, luôn luôn' },
  { mandarin: '嘴', pinyin: 'zuǐ', vietnamese: 'Miệng' },
  { mandarin: '最近', pinyin: 'zuìjìn', vietnamese: 'Gần đây' },
  { mandarin: '作业', pinyin: 'zuòyè', vietnamese: 'Bài tập' },
  { mandarin: '作用', pinyin: 'zuòyòng', vietnamese: 'Tác dụng, vai trò' },
];