import { HSKWord } from './types';

export const HSK4_VOCABULARY: HSKWord[] = [
  { mandarin: '爱情', pinyin: 'àiqíng', vietnamese: 'n. tình yêu (giữa nam và nữ)' },
  { mandarin: '安排', pinyin: 'ānpái', vietnamese: 'v. lên kế hoạch chi tiết; sắp xếp n. kế hoạch' },
  { mandarin: '安全', pinyin: 'ānquán', vietnamese: 'adj. an toàn n. sự an toàn' },
  { mandarin: '按时', pinyin: 'ànshí', vietnamese: 'adv. đúng giờ; đúng lịch; đúng hạn' },
  { mandarin: '按照', pinyin: 'ànzhào', vietnamese: 'prep. dựa theo, căn cứ theo' },
  { mandarin: '百分之', pinyin: 'bǎifēn zhī', vietnamese: 'phần trăm' },
  { mandarin: '棒', pinyin: 'bàng', vietnamese: 'adj. tuyệt vời; giỏi' },
  { mandarin: '包子', pinyin: 'bāozi', vietnamese: 'n. bánh bao (có nhân)' },
  { mandarin: '保护', pinyin: 'bǎohù', vietnamese: 'v. bảo vệ' },
  { mandarin: '保证', pinyin: 'bǎozhèng', vietnamese: 'v. bảo đảm; hứa n. sự bảo đảm' },
  { mandarin: '报名', pinyin: 'bàomíng', vietnamese: 'sv. báo danh, đăng ký' },
  { mandarin: '抱', pinyin: 'bào', vietnamese: 'v. ôm, bế' },
  { mandarin: '抱歉', pinyin: 'bàoqiàn', vietnamese: 'v. xin lỗi; cảm thấy có lỗi' },
  { mandarin: '倍', pinyin: 'bèi', vietnamese: 'nm. lần (gấp bội)' },
  { mandarin: '本来', pinyin: 'běnlái', vietnamese: 'adv. vốn dĩ, ban đầu' },
  { mandarin: '笨', pinyin: 'bèn', vietnamese: 'adj. đần; ngốc; dốt' },
  { mandarin: '比如', pinyin: 'bǐrú', vietnamese: 'v. ví dụ như' },
  { mandarin: '毕业', pinyin: 'bìyè', vietnamese: 'sv. tốt nghiệp' },
  { mandarin: '遍', pinyin: 'biàn', vietnamese: 'vm. lần (số lần thực hiện hành động)' },
  { mandarin: '标准', pinyin: 'biāozhǔn', vietnamese: 'n. tiêu chuẩn adj. chuẩn, đúng tiêu chuẩn' },
  { mandarin: '表格', pinyin: 'biǎogé', vietnamese: 'n. bảng biểu; mẫu đơn' },
  { mandarin: '表示', pinyin: 'biǎoshì', vietnamese: 'v. biểu thị; bày tỏ' },
  { mandarin: '表演', pinyin: 'biǎoyǎn', vietnamese: 'v. biểu diễn; diễn n. màn trình diễn; tiết mục' },
  { mandarin: '表扬', pinyin: 'biǎoyáng', vietnamese: 'v. khen ngợi, biểu dương n. sự khen ngợi, sự công nhận' },
  { mandarin: '饼干', pinyin: 'bǐnggān', vietnamese: 'n. bánh quy' },
  { mandarin: '并且', pinyin: 'bìngqiě', vietnamese: 'conj. hơn nữa; vả lại' },
  { mandarin: '博士', pinyin: 'bóshì', vietnamese: 'n. tiến sĩ' },
  { mandarin: '不过', pinyin: 'búguò', vietnamese: 'conj. nhưng; tuy nhiên' },
  { mandarin: '不得不', pinyin: 'bùdébù', vietnamese: 'phải, buộc phải' },
  { mandarin: '不管', pinyin: 'bùguǎn', vietnamese: 'conj. bất kể; dù cho' },
  { mandarin: '不好意思', pinyin: 'bùhǎoyìsi', vietnamese: 'cảm thấy ngại hoặc xin lỗi' },
  { mandarin: '不仅', pinyin: 'bùjǐn', vietnamese: 'conj. không chỉ' },
  { mandarin: '部分', pinyin: 'bùfen', vietnamese: 'n. bộ phận; phần' },
  { mandarin: '擦', pinyin: 'cā', vietnamese: 'v. lau, chùi' },
  { mandarin: '猜', pinyin: 'cāi', vietnamese: 'v. đoán' },
  { mandarin: '材料', pinyin: 'cáiliào', vietnamese: 'n. tài liệu tham khảo' },
  { mandarin: '参观', pinyin: 'cānguān', vietnamese: 'v. tham quan (để học hỏi)' },
  { mandarin: '餐厅', pinyin: 'cāntīng', vietnamese: 'n. nhà hàng, phòng ăn' },
  { mandarin: '厕所', pinyin: 'cèsuǒ', vietnamese: 'n. nhà vệ sinh; phòng tắm' },
  { mandarin: '差不多', pinyin: 'chàbuduō', vietnamese: 'adv. khoảng; gần như' },
  { mandarin: '长城', pinyin: 'Chángchéng', vietnamese: 'n. Vạn Lý Trường Thành' },
  { mandarin: '长江', pinyin: 'Chángjiāng', vietnamese: 'n. Sông Trường Giang (Dương Tử)' },
  { mandarin: '尝', pinyin: 'cháng', vietnamese: 'v. nếm, thử (món ăn)' },
  { mandarin: '场', pinyin: 'chǎng', vietnamese: 'vm. dùng cho các hoạt động' },
  { mandarin: '超过', pinyin: 'chāoguò', vietnamese: 'v. vượt qua; bỏ lại phía sau' },
  { mandarin: '吵', pinyin: 'chǎo', vietnamese: 'adj. ồn ào v. cãi nhau' },
  { mandarin: '成功', pinyin: 'chénggōng', vietnamese: 'v. thành công n. sự thành công' },
  { mandarin: '成为', pinyin: 'chéngwéi', vietnamese: 'v. trở thành' },
  { mandarin: '诚实', pinyin: 'chéngshí', vietnamese: 'adj. thành thật, trung thực' },
  { mandarin: '乘坐', pinyin: 'chéngzuò', vietnamese: 'v. đi (xe, tàu, v.v.)' },
  { mandarin: '吃惊', pinyin: 'chījīng', vietnamese: 'sv. giật mình; kinh ngạc' },
  { mandarin: '重新', pinyin: 'chóngxīn', vietnamese: 'adv. một lần nữa, lại' },
  { mandarin: '抽烟', pinyin: 'chōuyān', vietnamese: 'hút thuốc' },
  { mandarin: '出差', pinyin: 'chūchāi', vietnamese: 'sv. đi công tác' },
  { mandarin: '出发', pinyin: 'chūfā', vietnamese: 'v. xuất phát; khởi hành' },
  { mandarin: '出生', pinyin: 'chūshēng', vietnamese: 'v. ra đời, được sinh ra' },
  { mandarin: '厨房', pinyin: 'chúfáng', vietnamese: 'n. nhà bếp' },
  { mandarin: '传真', pinyin: 'chuánzhēn', vietnamese: 'n. fax' },
  { mandarin: '窗户', pinyin: 'chuānghu', vietnamese: 'n. cửa sổ' },
  { mandarin: '词语', pinyin: 'cíyǔ', vietnamese: 'n. từ ngữ' },
  { mandarin: '从来', pinyin: 'cónglái', vietnamese: 'adv. từ trước đến nay; luôn luôn' },
  { mandarin: '粗心', pinyin: 'cūxīn', vietnamese: 'adj. cẩu thả; bất cẩn' },
  { mandarin: '存', pinyin: 'cún', vietnamese: 'v. giữ; tiết kiệm; gửi (tiền)' },
  { mandarin: '错误', pinyin: 'cuòwù', vietnamese: 'adj. sai; không đúng; nhầm n. lỗi; sai lầm' },
  { mandarin: '答案', pinyin: 'dá\'àn', vietnamese: 'n. câu trả lời, đáp án' },
  { mandarin: '打扮', pinyin: 'dǎban', vietnamese: 'v. ăn mặc; trang điểm' },
  { mandarin: '打扰', pinyin: 'dǎrǎo', vietnamese: 'v. làm phiền; quấy rầy' },
  { mandarin: '打印', pinyin: 'dǎyìn', vietnamese: 'v. in (văn bản)' },
  { mandarin: '打招呼', pinyin: 'dǎzhāohu', vietnamese: 'chào hỏi (bằng lời hoặc cử chỉ)' },
  { mandarin: '打折', pinyin: 'dǎzhé', vietnamese: 'sv. giảm giá' },
  { mandarin: '打针', pinyin: 'dǎzhēn', vietnamese: 'sv. tiêm, chích (thuốc)' },
  { mandarin: '大概', pinyin: 'dàgài', vietnamese: 'adv. có lẽ; gần như' },
  { mandarin: '大使馆', pinyin: 'dàshǐguǎn', vietnamese: 'n. đại sứ quán' },
  { mandarin: '大约', pinyin: 'dàyuē', vietnamese: 'adv. khoảng; xấp xỉ' },
  { mandarin: '大夫', pinyin: 'dàifu', vietnamese: 'n. bác sĩ; y sĩ' },
  { mandarin: '戴', pinyin: 'dài', vietnamese: 'v. đeo; đội (mũ)' },
  { mandarin: '当时', pinyin: 'dāngshí', vietnamese: 'n. lúc đó; khi đó' },
  { mandarin: '刀', pinyin: 'dāo', vietnamese: 'n. dao' },
  { mandarin: '导游', pinyin: 'dǎoyóu', vietnamese: 'n. hướng dẫn viên du lịch' },
  { mandarin: '倒', pinyin: 'dǎo', vietnamese: 'v. ngã; đổ' },
  { mandarin: '到处', pinyin: 'dàochù', vietnamese: 'adv. khắp nơi' },
  { mandarin: '到底', pinyin: 'dàodǐ', vietnamese: 'adv. rốt cuộc (dùng trong câu hỏi)' },
  { mandarin: '道歉', pinyin: 'dàoqiàn', vietnamese: 'sv. xin lỗi' },
  { mandarin: '得意', pinyin: 'déyì', vietnamese: 'adj. hài lòng với bản thân; đắc ý' },
  { mandarin: '得', pinyin: 'de', vietnamese: 'sa. trợ từ bổ ngữ v. nhận được; đạt được' },
  { mandarin: '登机牌', pinyin: 'dēngjīpái', vietnamese: 'n. thẻ lên máy bay' },
  { mandarin: '等', pinyin: 'děng', vietnamese: 'sa. vân vân; v.v.' },
  { mandarin: '低', pinyin: 'dī', vietnamese: 'adj. thấp; xuống v. hạ thấp, cúi' },
  { mandarin: '底', pinyin: 'dǐ', vietnamese: 'n. cuối (năm, tháng)' },
  { mandarin: '地点', pinyin: 'dìdiǎn', vietnamese: 'n. địa điểm; nơi' },
  { mandarin: '地球', pinyin: 'dìqiú', vietnamese: 'n. Trái Đất' },
  { mandarin: '地址', pinyin: 'dìzhǐ', vietnamese: 'n. địa chỉ' },
  { mandarin: '调查', pinyin: 'diàochá', vietnamese: 'v. điều tra n. cuộc điều tra; khảo sát' },
  { mandarin: '掉', pinyin: 'diào', vietnamese: 'v. rơi; rớt' },
  { mandarin: '丢', pinyin: 'diū', vietnamese: 'v. mất, đánh mất' },
  { mandarin: '动作', pinyin: 'dòngzuò', vietnamese: 'n. động tác; hành động' },
  { mandarin: '堵车', pinyin: 'dǔchē', vietnamese: 'v. kẹt xe, tắc đường' },
  { mandarin: '肚子', pinyin: 'dùzi', vietnamese: 'n. bụng' },
  { mandarin: '短信', pinyin: 'duǎnxìn', vietnamese: 'n. tin nhắn ngắn' },
  { mandarin: '对话', pinyin: 'duìhuà', vietnamese: 'n. đối thoại, hội thoại' },
  { mandarin: '对面', pinyin: 'duìmiàn', vietnamese: 'n. phía đối diện' },
  { mandarin: '儿童', pinyin: 'értóng', vietnamese: 'n. trẻ em, nhi đồng' },
  { mandarin: '而', pinyin: 'ér', vietnamese: 'conj. và; nhưng; mà' },
  { mandarin: '发生', pinyin: 'fāshēng', vietnamese: 'v. xảy ra' },
  { mandarin: '发展', pinyin: 'fāzhǎn', vietnamese: 'v. phát triển; mở rộng' },
  { mandarin: '法律', pinyin: 'fǎlǜ', vietnamese: 'n. pháp luật' },
  { mandarin: '翻译', pinyin: 'fānyì', vietnamese: 'v. phiên dịch; biên dịch' },
  { mandarin: '烦恼', pinyin: 'fánnǎo', vietnamese: 'n. phiền não; lo lắng v. phiền lòng; lo lắng' },
  { mandarin: '反对', pinyin: 'fǎnduì', vietnamese: 'v. phản đối' },
  { mandarin: '方法', pinyin: 'fāngfǎ', vietnamese: 'n. phương pháp; cách thức' },
  { mandarin: '方面', pinyin: 'fāngmiàn', vietnamese: 'n. phương diện, mặt, khía cạnh' },
  { mandarin: '方向', pinyin: 'fāngxiàng', vietnamese: 'n. phương hướng, hướng' },
  { mandarin: '房东', pinyin: 'fángdōng', vietnamese: 'n. chủ nhà (cho thuê)' },
  { mandarin: '放弃', pinyin: 'fàngqì', vietnamese: 'v. từ bỏ' },
  { mandarin: '放暑假', pinyin: 'fàng shǔjià', vietnamese: 'nghỉ hè' },
  { mandarin: '放松', pinyin: 'fàngsōng', vietnamese: 'v. thư giãn, thả lỏng' },
  { mandarin: '费用', pinyin: 'fèiyong', vietnamese: 'n. chi phí; lệ phí' },
  { mandarin: '份', pinyin: 'fèn', vietnamese: 'nm. phần; suất' },
  { mandarin: '丰富', pinyin: 'fēngfù', vietnamese: 'adj. phong phú; dồi dào v. làm phong phú' },
  { mandarin: '否则', pinyin: 'fǒuzé', vietnamese: 'conj. nếu không thì' },
  { mandarin: '符合', pinyin: 'fúhé', vietnamese: 'v. phù hợp với' },
  { mandarin: '父亲', pinyin: 'fùqīn', vietnamese: 'n. cha, bố' },
  { mandarin: '付款', pinyin: 'fùkuǎn', vietnamese: 'v. thanh toán' },
  { mandarin: '负责', pinyin: 'fùzé', vietnamese: 'v. phụ trách; chịu trách nhiệm adj. có trách nhiệm' },
  { mandarin: '复印', pinyin: 'fùyìn', vietnamese: 'v. sao chép; photocopy' },
  { mandarin: '复杂', pinyin: 'fùzá', vietnamese: 'adj. phức tạp' },
  { mandarin: '富', pinyin: 'fù', vietnamese: 'adj. giàu có' },
  { mandarin: '改变', pinyin: 'gǎibiàn', vietnamese: 'v. thay đổi n. sự thay đổi' },
  { mandarin: '干杯', pinyin: 'gānbēi', vietnamese: 'v. cạn ly, dzô' },
  { mandarin: '赶', pinyin: 'gǎn', vietnamese: 'v. bắt kịp; đuổi kịp' },
  { mandarin: '敢', pinyin: 'gǎn', vietnamese: 'aux. dám (làm gì)' },
  { mandarin: '感动', pinyin: 'gǎndòng', vietnamese: 'v. cảm động; xúc động' },
  { mandarin: '感觉', pinyin: 'gǎnjué', vietnamese: 'n. cảm giác; ấn tượng v. cảm thấy' },
  { mandarin: '感情', pinyin: 'gǎnqíng', vietnamese: 'n. tình cảm; cảm xúc' },
  { mandarin: '感谢', pinyin: 'gǎnxiè', vietnamese: 'v. cảm ơn; biết ơn n. sự cảm ơn; lòng biết ơn' },
  { mandarin: '干', pinyin: 'gàn', vietnamese: 'v. làm; làm việc' },
  { mandarin: '高级', pinyin: 'gāojí', vietnamese: 'adj. cao cấp' },
  { mandarin: '高速公路', pinyin: 'gāosùgōnglù', vietnamese: 'n. đường cao tốc' },
  { mandarin: '各', pinyin: 'gè', vietnamese: 'pron. mỗi, các' },
  { mandarin: '工资', pinyin: 'gōngzī', vietnamese: 'n. lương; tiền lương' },
  { mandarin: '公里', pinyin: 'gōnglǐ', vietnamese: 'nm. kilômét' },
  { mandarin: '功夫', pinyin: 'gōngfu', vietnamese: 'n. Kung Fu' },
  { mandarin: '共同', pinyin: 'gòngtóng', vietnamese: 'adj. chung, cộng đồng' },
  { mandarin: '购物', pinyin: 'gòuwù', vietnamese: 'sv. mua sắm' },
  { mandarin: '够', pinyin: 'gòu', vietnamese: 'adv. đủ v. đủ (số lượng)' },
  { mandarin: '估计', pinyin: 'gūjì', vietnamese: 'v. ước tính; đoán n. sự ước tính' },
  { mandarin: '鼓励', pinyin: 'gǔlì', vietnamese: 'n. sự động viên; sự khuyến khích v. động viên; cổ vũ' },
  { mandarin: '故意', pinyin: 'gùyì', vietnamese: 'adv. cố ý; cố tình' },
  { mandarin: '顾客', pinyin: 'gùkè', vietnamese: 'n. khách hàng' },
  { mandarin: '挂', pinyin: 'guà', vietnamese: 'v. treo; tạm ngừng v. gác (điện thoại)' },
  { mandarin: '关键', pinyin: 'guānjiàn', vietnamese: 'n. điểm mấu chốt; yếu tố then chốt adj. then chốt; rất quan trọng' },
  { mandarin: '观众', pinyin: 'guānzhòng', vietnamese: 'n. khán giả; người xem' },
  { mandarin: '管理', pinyin: 'guǎnlǐ', vietnamese: 'v. phụ trách; quản lý n. sự quản lý' },
  { mandarin: '光', pinyin: 'guāng', vietnamese: 'n. ánh sáng adv. chỉ; duy nhất adj. hết; sạch (dùng sau động từ)' },
  { mandarin: '广播', pinyin: 'guǎngbō', vietnamese: 'n. phát thanh, truyền thanh' },
  { mandarin: '广告', pinyin: 'guǎnggào', vietnamese: 'n. quảng cáo' },
  { mandarin: '逛', pinyin: 'guàng', vietnamese: 'v. dạo; đi dạo' },
  { mandarin: '规定', pinyin: 'guīdìng', vietnamese: 'v. quy định; ra lệnh n. quy tắc; quy định' },
  { mandarin: '国籍', pinyin: 'guójí', vietnamese: 'n. quốc tịch' },
  { mandarin: '国际', pinyin: 'guójì', vietnamese: 'adj. quốc tế' },
  { mandarin: '果汁', pinyin: 'guǒzhī', vietnamese: 'n. nước ép trái cây' },
  { mandarin: '过程', pinyin: 'guòchéng', vietnamese: 'n. quá trình; tiến trình' },
  { mandarin: '海洋', pinyin: 'hǎiyáng', vietnamese: 'n. đại dương' },
  { mandarin: '害羞', pinyin: 'hàixiū', vietnamese: 'adj. nhút nhát; e thẹn' },
  { mandarin: '寒假', pinyin: 'hánjià', vietnamese: 'n. nghỉ đông' },
  { mandarin: '汗', pinyin: 'hàn', vietnamese: 'n. mồ hôi' },
  { mandarin: '好处', pinyin: 'hǎochu', vietnamese: 'n. điểm tốt; lợi thế' },
  { mandarin: '好像', pinyin: 'hǎoxiàng', vietnamese: 'adv. dường như; có vẻ như' },
  { mandarin: '号码', pinyin: 'hàomǎ', vietnamese: 'n. số; con số' },
  { mandarin: '合格', pinyin: 'hégé', vietnamese: 'adj. đủ tiêu chuẩn, đạt chuẩn' },
  { mandarin: '合适', pinyin: 'héshì', vietnamese: 'adj. vừa vặn; phù hợp' },
  { mandarin: '盒子', pinyin: 'hézi', vietnamese: 'n. hộp' },
  { mandarin: '后悔', pinyin: 'hòuhuǐ', vietnamese: 'v. hối hận' },
  { mandarin: '厚', pinyin: 'hòu', vietnamese: 'adj. dày n. độ dày' },
  { mandarin: '互联网', pinyin: 'hùliánwǎng', vietnamese: 'n. Internet' },
  { mandarin: '互相', pinyin: 'hùxiāng', vietnamese: 'adv. lẫn nhau; với nhau' },
  { mandarin: '护士', pinyin: 'hùshi', vietnamese: 'n. y tá' },
  { mandarin: '怀疑', pinyin: 'huáiyí', vietnamese: 'v. nghi ngờ' },
  { mandarin: '回忆', pinyin: 'huíyì', vietnamese: 'v. hồi tưởng, nhớ lại n. ký ức; hồi ức' },
  { mandarin: '活动', pinyin: 'huódòng', vietnamese: 'v. tập thể dục, vận động n. hoạt động' },
  { mandarin: '活泼', pinyin: 'huópō', vietnamese: 'adj. hoạt bát, nhanh nhẹn' },
  { mandarin: '火', pinyin: 'huǒ', vietnamese: 'n. lửa n. sự tức giận adj. thịnh hành; nổi tiếng' },
  { mandarin: '获得', pinyin: 'huòdé', vietnamese: 'v. nhận được; đạt được' },
  { mandarin: '积极', pinyin: 'jījí', vietnamese: 'adj. tích cực; hăng hái' },
  { mandarin: '积累', pinyin: 'jīlěi', vietnamese: 'v. tích lũy n. sự tích lũy' },
  { mandarin: '基础', pinyin: 'jīchǔ', vietnamese: 'n. cơ sở; nền tảng adj. cơ bản' },
  { mandarin: '激动', pinyin: 'jīdòng', vietnamese: 'adj. xúc động; kích động v. làm náo động; truyền cảm hứng' },
  { mandarin: '及时', pinyin: 'jíshí', vietnamese: 'adv. kịp thời, đúng lúc adj. vừa đúng lúc' },
  { mandarin: '即使', pinyin: 'jíshǐ', vietnamese: 'conj. cho dù; kể cả nếu' },
  { mandarin: '计划', pinyin: 'jìhuà', vietnamese: 'n. kế hoạch v. lên kế hoạch' },
  { mandarin: '计算机', pinyin: 'jìsuànjī', vietnamese: 'n. máy vi tính' },
  { mandarin: '记者', pinyin: 'jìzhě', vietnamese: 'n. nhà báo; phóng viên' },
  { mandarin: '技术', pinyin: 'jìshù', vietnamese: 'n. công nghệ; kỹ thuật' },
  { mandarin: '既然', pinyin: 'jìrán', vietnamese: 'conj. đã, vì đã' },
  { mandarin: '继续', pinyin: 'jìxù', vietnamese: 'adv. tiếp tục; tiếp diễn' },
  { mandarin: '寄', pinyin: 'jì', vietnamese: 'v. gửi (thư, hàng)' },
  { mandarin: '加班', pinyin: 'jiābān', vietnamese: 'sv. làm thêm giờ, tăng ca' },
  { mandarin: '加油站', pinyin: 'jiāyóuzhàn', vietnamese: 'n. trạm xăng, cây xăng' },
  { mandarin: '家具', pinyin: 'jiājù', vietnamese: 'n. đồ nội thất, đồ gia dụng' },
  { mandarin: '价格', pinyin: 'jiàgé', vietnamese: 'n. giá cả' },
  { mandarin: '假', pinyin: 'jiǎ', vietnamese: 'adj. giả; không thật' },
  { mandarin: '坚持', pinyin: 'jiānchí', vietnamese: 'v. kiên trì; khăng khăng' },
  { mandarin: '减肥', pinyin: 'jiǎnféi', vietnamese: 'sv. giảm cân' },
  { mandarin: '减少', pinyin: 'jiǎnshǎo', vietnamese: 'v. giảm bớt; cắt giảm' },
  { mandarin: '建议', pinyin: 'jiànyì', vietnamese: 'v. đề nghị; khuyên n. đề nghị; lời khuyên' },
  { mandarin: '将来', pinyin: 'jiānglái', vietnamese: 'n. trong tương lai; sau này' },
  { mandarin: '奖金', pinyin: 'jiǎngjīn', vietnamese: 'n. tiền thưởng' },
  { mandarin: '降低', pinyin: 'jiàngdī', vietnamese: 'v. hạ thấp; giảm' },
  { mandarin: '交', pinyin: 'jiāo', vietnamese: 'v. đưa; nộp v. kết (bạn)' },
  { mandarin: '交流', pinyin: 'jiāoliú', vietnamese: 'v. giao tiếp v. trao đổi' },
  { mandarin: '交通', pinyin: 'jiāotōng', vietnamese: 'n. giao thông' },
  { mandarin: '郊区', pinyin: 'jiāoqū', vietnamese: 'n. ngoại ô; ngoại thành' },
  { mandarin: '骄傲', pinyin: 'jiāo\'ào', vietnamese: 'adj. tự hào, kiêu ngạo' },
  { mandarin: '饺子', pinyin: 'jiǎozi', vietnamese: 'n. sủi cảo; bánh chẻo' },
  { mandarin: '教授', pinyin: 'jiàoshòu', vietnamese: 'n. giáo sư' },
  { mandarin: '教育', pinyin: 'jiàoyù', vietnamese: 'n. giáo dục v. giáo dục, dạy dỗ' },
  { mandarin: '接受', pinyin: 'jiēshòu', vietnamese: 'v. chấp nhận; tiếp nhận' },
  { mandarin: '接着', pinyin: 'jiēzhe', vietnamese: 'v. tiếp tục; tiếp đó' },
  { mandarin: '节', pinyin: 'jié', vietnamese: 'nm. tiết (học)' },
  { mandarin: '节约', pinyin: 'jiéyuē', vietnamese: 'v. tiết kiệm' },
  { mandarin: '结果', pinyin: 'jiéguǒ', vietnamese: 'n. kết quả' },
  { mandarin: '解释', pinyin: 'jiěshì', vietnamese: 'v. giải thích; định nghĩa n. lời giải thích' },
  { mandarin: '尽管', pinyin: 'jǐnguǎn', vietnamese: 'conj. mặc dù; dù cho' },
  { mandarin: '紧张', pinyin: 'jǐnzhāng', vietnamese: 'adj. cảm thấy lo lắng, căng thẳng' },
  { mandarin: '进行', pinyin: 'jìnxíng', vietnamese: 'v. thực hiện; tiến hành' },
  { mandarin: '禁止', pinyin: 'jìnzhǐ', vietnamese: 'v. cấm; ngăn cấm' },
  { mandarin: '京剧', pinyin: 'jīngjù', vietnamese: 'n. Kinh kịch' },
  { mandarin: '经济', pinyin: 'jīngjì', vietnamese: 'n. kinh tế' },
  { mandarin: '经历', pinyin: 'jīnglì', vietnamese: 'v. trải qua; nếm trải n. kinh nghiệm, trải nghiệm trong quá khứ' },
  { mandarin: '经验', pinyin: 'jīngyàn', vietnamese: 'n. kinh nghiệm' },
  { mandarin: '精彩', pinyin: 'jīngcǎi', vietnamese: 'adj. (buổi biểu diễn, trận đấu) xuất sắc, tuyệt vời' },
  { mandarin: '景色', pinyin: 'jǐngsè', vietnamese: 'n. phong cảnh; cảnh vật' },
  { mandarin: '警察', pinyin: 'jǐngchá', vietnamese: 'n. cảnh sát' },
  { mandarin: '竞争', pinyin: 'jìngzhēng', vietnamese: 'v. cạnh tranh' },
  { mandarin: '竟然', pinyin: 'jìngrán', vietnamese: 'adv. không ngờ, vậy mà' },
  { mandarin: '镜子', pinyin: 'jìngzi', vietnamese: 'n. gương; kính' },
  { mandarin: '究竟', pinyin: 'jiūjìng', vietnamese: 'adv. rốt cuộc, tóm lại' },
  { mandarin: '举', pinyin: 'jǔ', vietnamese: 'v. nâng; giơ (tay)' },
  { mandarin: '举办', pinyin: 'jǔbàn', vietnamese: 'v. tổ chức (triển lãm, cuộc thi, v.v.)' },
  { mandarin: '举行', pinyin: 'jǔxíng', vietnamese: 'v. thực hiện; diễn ra' },
  { mandarin: '拒绝', pinyin: 'jùjué', vietnamese: 'v. từ chối; bác bỏ' },
  { mandarin: '距离', pinyin: 'jùlí', vietnamese: 'v. cách (xa)' },
  { mandarin: '聚会', pinyin: 'jùhuì', vietnamese: 'n. cuộc họp mặt; buổi gặp gỡ' },
  { mandarin: '开玩笑', pinyin: 'kāi wánxiào', vietnamese: 'nói đùa, đùa cợt' },
  { mandarin: '开心', pinyin: 'kāixīn', vietnamese: 'adj. vui vẻ; phấn khởi' },
  { mandarin: '看法', pinyin: 'kànfǎ', vietnamese: 'n. quan điểm, ý kiến' },
  { mandarin: '考虑', pinyin: 'kǎolǜ', vietnamese: 'v. suy nghĩ; cân nhắc' },
  { mandarin: '科学', pinyin: 'kēxué', vietnamese: 'n. khoa học' },
  { mandarin: '棵', pinyin: 'kē', vietnamese: 'nm. (lượng từ) dùng cho cây cối' },
  { mandarin: '咳嗽', pinyin: 'késou', vietnamese: 'v. ho' },
  { mandarin: '可怜', pinyin: 'kělián', vietnamese: 'adj. đáng thương; tội nghiệp' },
  { mandarin: '可是', pinyin: 'kěshì', vietnamese: 'conj. nhưng; tuy nhiên' },
  { mandarin: '可惜', pinyin: 'kěxī', vietnamese: 'adj. đáng tiếc' },
  { mandarin: '客厅', pinyin: 'kètīng', vietnamese: 'n. phòng khách' },
  { mandarin: '肯定', pinyin: 'kěndìng', vietnamese: 'adv. chắc chắn; nhất định' },
  { mandarin: '空', pinyin: 'kōng', vietnamese: 'adj. trống rỗng; trống' },
  { mandarin: '空气', pinyin: 'kōngqì', vietnamese: 'n. không khí' },
  { mandarin: '恐怕', pinyin: 'kǒngpà', vietnamese: 'adv. có lẽ; e rằng' },
  { mandarin: '苦', pinyin: 'kǔ', vietnamese: 'adj. đắng' },
  { mandarin: '矿泉水', pinyin: 'kuàngquánshuǐ', vietnamese: 'n. nước khoáng' },
  { mandarin: '困', pinyin: 'kùn', vietnamese: 'adj. buồn ngủ' },
  { mandarin: '困难', pinyin: 'kùnnan', vietnamese: 'n. rắc rối; khó khăn adj. khó khăn; vất vả' },
  { mandarin: '垃圾桶', pinyin: 'lājītǒng', vietnamese: 'n. thùng rác' },
  { mandarin: '拉', pinyin: 'lā', vietnamese: 'v. kéo; dắt (tay)' },
  { mandarin: '辣', pinyin: 'là', vietnamese: 'adj. (vị) cay' },
  { mandarin: '来不及', pinyin: 'láibují', vietnamese: 'không đủ thời gian, không kịp' },
  { mandarin: '来得及', pinyin: 'láidejí', vietnamese: 'có đủ thời gian, kịp' },
  { mandarin: '来自', pinyin: 'láizì', vietnamese: 'v. đến từ' },
  { mandarin: '懒', pinyin: 'lǎn', vietnamese: 'adj. lười biếng' },
  { mandarin: '浪费', pinyin: 'làngfèi', vietnamese: 'v. lãng phí' },
  { mandarin: '浪漫', pinyin: 'làngmàn', vietnamese: 'adj. lãng mạn' },
  { mandarin: '老虎', pinyin: 'lǎohǔ', vietnamese: 'n. con hổ' },
  { mandarin: '冷静', pinyin: 'lěngjìng', vietnamese: 'adj. bình tĩnh; điềm tĩnh v. bình tĩnh lại' },
  { mandarin: '离婚', pinyin: 'líhūn', vietnamese: 'v. ly hôn' },
  { mandarin: '礼拜天', pinyin: 'lǐbàitiān', vietnamese: 'n. Chủ nhật' },
  { mandarin: '礼貌', pinyin: 'lǐmào', vietnamese: 'n. sự lịch sự; lễ phép' },
  { mandarin: '理发', pinyin: 'lǐfà', vietnamese: 'v. cắt tóc' },
  { mandarin: '理解', pinyin: 'lǐjiě', vietnamese: 'v. hiểu; thấu hiểu' },
  { mandarin: '理想', pinyin: 'lǐxiǎng', vietnamese: 'n. lý tưởng adj. hoàn hảo; đáng mơ ước' },
  { mandarin: '力气', pinyin: 'lìqi', vietnamese: 'n. (thể) sức; sức lực' },
  { mandarin: '厉害', pinyin: 'lìhai', vietnamese: 'adj. nghiêm trọng; dữ dội' },
  { mandarin: '俩', pinyin: 'liǎ', vietnamese: 'num. (một) cặp; (hai) người' },
  { mandarin: '连', pinyin: 'lián', vietnamese: 'adv. ngay cả (dùng để nhấn mạnh) v. liên tiếp' },
  { mandarin: '联系', pinyin: 'liánxì', vietnamese: 'v. liên lạc; thiết lập liên lạc n. sự liên kết; mối quan hệ' },
  { mandarin: '凉快', pinyin: 'liángkuai', vietnamese: 'adj. mát mẻ' },
  { mandarin: '零钱', pinyin: 'língqián', vietnamese: 'n. tiền lẻ' },
  { mandarin: '另外', pinyin: 'lìngwài', vietnamese: 'adj. ngoài ra, khác' },
  { mandarin: '留', pinyin: 'liú', vietnamese: 'v. ở lại' },
  { mandarin: '流利', pinyin: 'liúlì', vietnamese: 'adj. trôi chảy, lưu loát' },
  { mandarin: '流行', pinyin: 'liúxíng', vietnamese: 'adj. phổ biến; thịnh hành' },
  { mandarin: '旅行', pinyin: 'lǚxíng', vietnamese: 'v. du lịch' },
  { mandarin: '律师', pinyin: 'lǜshī', vietnamese: 'n. luật sư' },
  { mandarin: '乱', pinyin: 'luàn', vietnamese: 'adj. lộn xộn; bừa bộn; rối' },
  { mandarin: '麻烦', pinyin: 'máfan', vietnamese: 'adj. phiền phức v. làm phiền n. sự phiền phức; gánh nặng' },
  { mandarin: '马虎', pinyin: 'mǎhu', vietnamese: 'adj. cẩu thả; lơ đễnh' },
  { mandarin: '满', pinyin: 'mǎn', vietnamese: 'adj. đầy; tràn' },
  { mandarin: '毛', pinyin: 'máo', vietnamese: 'n. lông; tóc nm. hào (đơn vị tiền tệ)' },
  { mandarin: '毛巾', pinyin: 'máojīn', vietnamese: 'n. khăn tắm, khăn mặt' },
  { mandarin: '美好', pinyin: 'měihǎo', vietnamese: 'adj. tươi đẹp (dùng cho những thứ trừu tượng)' },
  { mandarin: '美丽', pinyin: 'měilì', vietnamese: 'adj. xinh đẹp' },
  { mandarin: '梦', pinyin: 'mèng', vietnamese: 'n. giấc mơ v. mơ (khi ngủ)' },
  { mandarin: '迷路', pinyin: 'mílù', vietnamese: 'v. lạc đường' },
  { mandarin: '密码', pinyin: 'mìmǎ', vietnamese: 'n. mã; mật khẩu' },
  { mandarin: '免费', pinyin: 'miǎnfèi', vietnamese: 'adj. miễn phí' },
  { mandarin: '秒', pinyin: 'miǎo', vietnamese: 'n. giây' },
  { mandarin: '民族', pinyin: 'mínzú', vietnamese: 'n. dân tộc; chủng tộc' },
  { mandarin: '母亲', pinyin: 'mǔqīn', vietnamese: 'n. mẹ' },
  { mandarin: '目的', pinyin: 'mùdì', vietnamese: 'n. mục đích' },
  { mandarin: '内', pinyin: 'nèi', vietnamese: 'n. bên trong; nội bộ' },
  { mandarin: '内容', pinyin: 'nèiróng', vietnamese: 'n. nội dung' },
  { mandarin: '耐心', pinyin: 'nàixīn', vietnamese: 'n. sự kiên nhẫn' },
  { mandarin: '难道', pinyin: 'nándào', vietnamese: 'adv. lẽ nào, chẳng lẽ (dùng trong câu hỏi tu từ)' },
  { mandarin: '难受', pinyin: 'nánshòu', vietnamese: 'adj. cảm thấy không khỏe; khó chịu' },
  { mandarin: '能力', pinyin: 'nénglì', vietnamese: 'n. năng lực; khả năng' },
  { mandarin: '年龄', pinyin: 'niánlíng', vietnamese: 'n. tuổi tác' },
  { mandarin: '弄', pinyin: 'nòng', vietnamese: 'v. làm; xoay xở' },
  { mandarin: '暖和', pinyin: 'nuǎnhuo', vietnamese: 'adj. ấm áp' },
  { mandarin: '偶尔', pinyin: 'ǒu\'ěr', vietnamese: 'adv. thỉnh thoảng; đôi khi' },
  { mandarin: '排队', pinyin: 'páiduì', vietnamese: 'v. xếp hàng' },
  { mandarin: '排列', pinyin: 'páiliè', vietnamese: 'v. sắp xếp; xếp hạng' },
  { mandarin: '排球', pinyin: 'páiqiú', vietnamese: 'n. bóng chuyền' },
  { mandarin: '判断', pinyin: 'pànduàn', vietnamese: 'n. quyết định; phán đoán' },
  { mandarin: '陪', pinyin: 'péi', vietnamese: 'v. đi cùng; đồng hành' },
  { mandarin: '批评', pinyin: 'pīpíng', vietnamese: 'v. phê bình n. sự phê bình; lời bình' },
  { mandarin: '皮肤', pinyin: 'pífū', vietnamese: 'n. da' },
  { mandarin: '脾气', pinyin: 'píqi', vietnamese: 'n. tính khí; tính tình' },
  { mandarin: '篇', pinyin: 'piān', vietnamese: 'nm. (lượng từ) dùng cho bài luận, bài báo' },
  { mandarin: '骗', pinyin: 'piàn', vietnamese: 'v. lừa dối; lừa gạt' },
  { mandarin: '乒乓球', pinyin: 'pīngpāngqiú', vietnamese: 'n. bóng bàn' },
  { mandarin: '平时', pinyin: 'píngshí', vietnamese: 'n. bình thường; thường ngày' },
  { mandarin: '瓶子', pinyin: 'píngzi', vietnamese: 'n. cái chai; cái lọ' },
  { mandarin: '破', pinyin: 'pò', vietnamese: 'adj. hỏng; rách' },
  { mandarin: '葡萄', pinyin: 'pútao', vietnamese: 'n. quả nho' },
  { mandarin: '普遍', pinyin: 'pǔbiàn', vietnamese: 'adj. phổ biến; chung' },
  { mandarin: '其次', pinyin: 'qícì', vietnamese: 'prep. thứ hai là; tiếp theo' },
  { mandarin: '其中', pinyin: 'qízhōng', vietnamese: 'prep. trong số đó; trong đó' },
  { mandarin: '起来', pinyin: 'qǐlái', vietnamese: 'v. (dùng sau động từ) biểu thị phương hướng hoặc xu hướng' },
  { mandarin: '气候', pinyin: 'qìhòu', vietnamese: 'n. khí hậu' },
  { mandarin: '千万', pinyin: 'qiānwàn', vietnamese: 'adv. dù thế nào cũng; bằng mọi giá' },
  { mandarin: '签证', pinyin: 'qiānzhèng', vietnamese: 'n. visa, thị thực' },
  { mandarin: '敲', pinyin: 'qiāo', vietnamese: 'v. gõ; đập' },
  { mandarin: '桥', pinyin: 'qiáo', vietnamese: 'n. cây cầu' },
  { mandarin: '巧克力', pinyin: 'qiǎokèlì', vietnamese: 'n. sô cô la' },
  { mandarin: '亲戚', pinyin: 'qīnqi', vietnamese: 'n. họ hàng; người thân' },
  { mandarin: '轻', pinyin: 'qīng', vietnamese: 'adj. nhẹ' },
  { mandarin: '轻松', pinyin: 'qīngsōng', vietnamese: 'adj. nhẹ nhàng; thư thái v. thư giãn' },
  { mandarin: '情况', pinyin: 'qíngkuàng', vietnamese: 'n. tình hình; hoàn cảnh' },
  { mandarin: '请假', pinyin: 'qǐngjià', vietnamese: 'sv. xin nghỉ phép' },
  { mandarin: '穷', pinyin: 'qióng', vietnamese: 'adj. nghèo; nghèo khổ' },
  { mandarin: '区别', pinyin: 'qūbié', vietnamese: 'n. sự khác biệt' },
  { mandarin: '取', pinyin: 'qǔ', vietnamese: 'v. lấy; nhận' },
  { mandarin: '全部', pinyin: 'quánbù', vietnamese: 'n. toàn bộ adj. toàn bộ; hoàn chỉnh' },
  { mandarin: '缺点', pinyin: 'quēdiǎn', vietnamese: 'n. khuyết điểm; thiếu sót' },
  { mandarin: '缺少', pinyin: 'quēshǎo', vietnamese: 'v. thiếu; thiếu hụt' },
  { mandarin: '却', pinyin: 'què', vietnamese: 'conj. nhưng; tuy nhiên; mà' },
  { mandarin: '确实', pinyin: 'quèshí', vietnamese: 'adv. thực sự; quả thực' },
  { mandarin: '然而', pinyin: 'rán\'ér', vietnamese: 'conj. tuy nhiên; nhưng' },
  { mandarin: '热闹', pinyin: 'rènao', vietnamese: 'adj. náo nhiệt; ồn ào' },
  { mandarin: '任何', pinyin: 'rènhé', vietnamese: 'pron. bất kỳ; bất cứ' },
  { mandarin: '任务', pinyin: 'rènwu', vietnamese: 'n. nhiệm vụ; công việc' },
  { mandarin: '扔', pinyin: 'rēng', vietnamese: 'v. ném đi; vứt đi' },
  { mandarin: '仍然', pinyin: 'réngrán', vietnamese: 'adv. vẫn; vẫn còn' },
  { mandarin: '日记', pinyin: 'rìjì', vietnamese: 'n. nhật ký' },
  { mandarin: '入口', pinyin: 'rùkǒu', vietnamese: 'n. lối vào; cổng vào' },
  { mandarin: '散步', pinyin: 'sànbù', vietnamese: 'sv. đi dạo; tản bộ' },
  { mandarin: '森林', pinyin: 'sēnlín', vietnamese: 'n. rừng rậm' },
  { mandarin: '沙发', pinyin: 'shāfā', vietnamese: 'n. ghế sô pha' },
  { mandarin: '伤心', pinyin: 'shāngxīn', vietnamese: 'adj. buồn; đau lòng' },
  { mandarin: '商量', pinyin: 'shāngliang', vietnamese: 'v. tham khảo ý kiến; thảo luận; bàn bạc' },
  { mandarin: '稍微', pinyin: 'shāowēi', vietnamese: 'adv. một chút; một ít' },
  { mandarin: '勺子', pinyin: 'sháozi', vietnamese: 'n. cái thìa; cái muỗng' },
  { mandarin: '社会', pinyin: 'shèhuì', vietnamese: 'n. xã hội' },
  { mandarin: '申请', pinyin: 'shēnqǐng', vietnamese: 'v. đăng ký; nộp đơn xin' },
  { mandarin: '深', pinyin: 'shēn', vietnamese: 'adj. sâu' },
  { mandarin: '甚至', pinyin: 'shènzhì', vietnamese: 'adv. thậm chí; đến mức' },
  { mandarin: '生活', pinyin: 'shēnghuó', vietnamese: 'n. cuộc sống; sinh kế' },
  { mandarin: '生命', pinyin: 'shēngmìng', vietnamese: 'n. cuộc sống; mạng sống' },
  { mandarin: '生意', pinyin: 'shēngyi', vietnamese: 'n. kinh doanh; buôn bán' },
  { mandarin: '省', pinyin: 'shěng', vietnamese: 'n. tỉnh' },
  { mandarin: '剩', pinyin: 'shèng', vietnamese: 'v. còn lại; thừa lại' },
  { mandarin: '失败', pinyin: 'shībài', vietnamese: 'v. bị đánh bại; thua; thất bại n. sự thất bại; thua lỗ' },
  { mandarin: '失望', pinyin: 'shīwàng', vietnamese: 'v. mất hy vọng adj. thất vọng; nản lòng' },
  { mandarin: '师傅', pinyin: 'shīfu', vietnamese: 'n. (cách xưng hô) thưa ông, thưa bác (tương tự "mister" hoặc "sir")' },
  { mandarin: '十分', pinyin: 'shífēn', vietnamese: 'adv. rất; vô cùng' },
  { mandarin: '实际', pinyin: 'shíjì', vietnamese: 'adj. thực tế; có thật' },
  { mandarin: '实在', pinyin: 'shízai', vietnamese: 'adj. thật thà; đáng tin cậy adv. quả thực; thực sự' },
  { mandarin: '使', pinyin: 'shǐ', vietnamese: 'v. khiến; gây ra' },
  { mandarin: '使用', pinyin: 'shǐyòng', vietnamese: 'v. sử dụng' },
  { mandarin: '世纪', pinyin: 'shìjì', vietnamese: 'n. thế kỷ' },
  { mandarin: '是否', pinyin: 'shìfǒu', vietnamese: 'adv. có hay không' },
  { mandarin: '适合', pinyin: 'shìhé', vietnamese: 'v. phù hợp; vừa vặn' },
  { mandarin: '适应', pinyin: 'shìyìng', vietnamese: 'v. điều chỉnh; thích ứng; phù hợp' },
  { mandarin: '收', pinyin: 'shōu', vietnamese: 'v. nhận; chấp nhận' },
  { mandarin: '收入', pinyin: 'shōurù', vietnamese: 'n. thu nhập; doanh thu' },
  { mandarin: '收拾', pinyin: 'shōushi', vietnamese: 'v. dọn dẹp; sắp xếp' },
  { mandarin: '首都', pinyin: 'shǒudū', vietnamese: 'n. thủ đô (của một quốc gia)' },
  { mandarin: '首先', pinyin: 'shǒuxiān', vietnamese: 'adv. trước hết' },
  { mandarin: '受不了', pinyin: 'shòubuliǎo', vietnamese: 'không thể chịu đựng được' },
  { mandarin: '受到', pinyin: 'shòudào', vietnamese: 'v. chấp nhận; nhận được' },
  { mandarin: '售货员', pinyin: 'shòuhuòyuán', vietnamese: 'n. nhân viên bán hàng' },
  { mandarin: '输', pinyin: 'shū', vietnamese: 'v. thua; bị đánh bại' },
  { mandarin: '熟悉', pinyin: 'shúxī', vietnamese: 'v. biết rõ; quen thuộc adj. quen thuộc' },
  { mandarin: '数量', pinyin: 'shùliàng', vietnamese: 'n. số lượng' },
  { mandarin: '数字', pinyin: 'shùzì', vietnamese: 'n. con số; chữ số' },
  { mandarin: '帅', pinyin: 'shuài', vietnamese: 'adj. đẹp trai; bảnh bao (dùng cho nam)' },
  { mandarin: '顺便', pinyin: 'shùnbiàn', vietnamese: 'adv. tiện thể; nhân tiện' },
  { mandarin: '顺利', pinyin: 'shùnlì', vietnamese: 'adj. trôi chảy; không gặp trở ngại' },
  { mandarin: '顺序', pinyin: 'shùnxù', vietnamese: 'n. trật tự; thứ tự' },
  { mandarin: '说明', pinyin: 'shuōmíng', vietnamese: 'v. giải thích; minh họa; cho thấy' },
  { mandarin: '硕士', pinyin: 'shuòshì', vietnamese: 'n. thạc sĩ' },
  { mandarin: '死', pinyin: 'sǐ', vietnamese: 'v. chết' },
  { mandarin: '速度', pinyin: 'sùdù', vietnamese: 'n. tốc độ' },
  { mandarin: '塑料袋', pinyin: 'sùliàodài', vietnamese: 'n. túi nhựa, túi ni lông' },
  { mandarin: '酸', pinyin: 'suān', vietnamese: 'adj. chua adj. mỏi; đau' },
  { mandarin: '随便', pinyin: 'suíbiàn', vietnamese: 'adj. tùy tiện; ngẫu nhiên' },
  { mandarin: '随着', pinyin: 'suízhe', vietnamese: 'conj. cùng với' },
  { mandarin: '孙子', pinyin: 'sūnzi', vietnamese: 'n. cháu trai (con của con trai)' },
  { mandarin: '所有', pinyin: 'suǒyǒu', vietnamese: 'adj. tất cả' },
  { mandarin: '台', pinyin: 'tái', vietnamese: 'nm. (lượng từ) dùng cho máy móc' },
  { mandarin: '抬', pinyin: 'tái', vietnamese: 'v. nâng; giơ; di chuyển; khiêng' },
  { mandarin: '态度', pinyin: 'tàidu', vietnamese: 'n. thái độ' },
  { mandarin: '谈', pinyin: 'tán', vietnamese: 'v. nói chuyện; trò chuyện; thảo luận' },
  { mandarin: '弹钢琴', pinyin: 'tán gāngqín', vietnamese: 'chơi đàn piano' },
  { mandarin: '汤', pinyin: 'tāng', vietnamese: 'n. canh; súp' },
  { mandarin: '糖', pinyin: 'táng', vietnamese: 'n. đường; kẹo' },
  { mandarin: '躺', pinyin: 'tǎng', vietnamese: 'v. nằm' },
  { mandarin: '趟', pinyin: 'tàng', vietnamese: 'vm. lần (chuyến đi)' },
  { mandarin: '讨论', pinyin: 'tǎolùn', vietnamese: 'v. thảo luận; tranh luận n. cuộc thảo luận; cuộc tranh luận' },
  { mandarin: '讨厌', pinyin: 'tǎoyàn', vietnamese: 'v. chán; ghét; không thích adj. khó chịu; đáng ghét' },
  { mandarin: '特点', pinyin: 'tèdiǎn', vietnamese: 'n. đặc điểm; đặc trưng' },
  { mandarin: '提', pinyin: 'tí', vietnamese: 'v. xách v. đưa ra; nêu ra; đề cập' },
  { mandarin: '提供', pinyin: 'tígōng', vietnamese: 'v. cung cấp' },
  { mandarin: '提前', pinyin: 'tíqián', vietnamese: 'adv. trước; sớm (thời gian) v. đẩy (ngày, giờ) lên sớm hơn' },
  { mandarin: '提醒', pinyin: 'tíxǐng', vietnamese: 'sv. nhắc nhở; cảnh báo' },
  { mandarin: '填空', pinyin: 'tiánkòng', vietnamese: 'n. điền vào chỗ trống' },
  { mandarin: '条件', pinyin: 'tiáojiàn', vietnamese: 'n. yêu cầu; điều kiện' },
  { mandarin: '停', pinyin: 'tíng', vietnamese: 'v. dừng' },
  { mandarin: '挺', pinyin: 'tǐng', vietnamese: 'adv. rất; khá' },
  { mandarin: '通过', pinyin: 'tōngguò', vietnamese: 'v. đi qua; đi ngang qua prep. bằng cách; thông qua v. thông qua (kỳ thi)' },
  { mandarin: '通知', pinyin: 'tōngzhī', vietnamese: 'v. thông báo n. thông báo' },
  { mandarin: '同情', pinyin: 'tóngqíng', vietnamese: 'v. thông cảm; đồng cảm' },
  { mandarin: '推', pinyin: 'tuī', vietnamese: 'v. đẩy' },
  { mandarin: '推迟', pinyin: 'tuīchí', vietnamese: 'v. trì hoãn; hoãn lại' },
  { mandarin: '脱', pinyin: 'tuō', vietnamese: 'v. cởi ra; cởi bỏ' },
  { mandarin: '袜子', pinyin: 'wàzi', vietnamese: 'n. tất; vớ' },
  { mandarin: '完全', pinyin: 'wánquán', vietnamese: 'adv. hoàn toàn; tuyệt đối' },
  { mandarin: '网球', pinyin: 'wǎngqiú', vietnamese: 'n. quần vợt, tennis' },
  { mandarin: '网站', pinyin: 'wǎngzhàn', vietnamese: 'n. trang web' },
  { mandarin: '往', pinyin: 'wǎng', vietnamese: 'prep. đến; về phía' },
  { mandarin: '往往', pinyin: 'wǎngwǎng', vietnamese: 'adv. luôn luôn, thường' },
  { mandarin: '危险', pinyin: 'wēixiǎn', vietnamese: 'adj. nguy hiểm' },
  { mandarin: '卫生间', pinyin: 'wèishēngjiān', vietnamese: 'n. nhà vệ sinh; phòng tắm' },
  { mandarin: '味道', pinyin: 'wèidào', vietnamese: 'n. hương vị; mùi vị' },
  { mandarin: '温度', pinyin: 'wēndù', vietnamese: 'n. nhiệt độ' },
  { mandarin: '文章', pinyin: 'wénzhāng', vietnamese: 'n. bài luận; bài viết' },
  { mandarin: '污染', pinyin: 'wūrǎn', vietnamese: 'v. làm ô nhiễm; vấy bẩn' },
  { mandarin: '无', pinyin: 'wú', vietnamese: 'v. không có' },
  { mandarin: '无聊', pinyin: 'wúliáo', vietnamese: 'adj. nhàm chán; vô vị' },
  { mandarin: '无论', pinyin: 'wúlùn', vietnamese: 'conj. bất kể, dù thế nào' },
  { mandarin: '误会', pinyin: 'wùhuì', vietnamese: 'v. hiểu lầm n. sự hiểu lầm' },
  { mandarin: '西红柿', pinyin: 'xīhóngshì', vietnamese: 'n. cà chua' },
  { mandarin: '吸引', pinyin: 'xīyǐn', vietnamese: 'v. thu hút; hấp dẫn' },
  { mandarin: '咸', pinyin: 'xián', vietnamese: 'adj. mặn' },
  { mandarin: '现金', pinyin: 'xiànjīn', vietnamese: 'n. tiền mặt' },
  { mandarin: '羡慕', pinyin: 'xiànmù', vietnamese: 'v. ngưỡng mộ; ghen tị' },
  { mandarin: '相反', pinyin: 'xiāngfǎn', vietnamese: 'adj. đối lập; ngược lại' },
  { mandarin: '相同', pinyin: 'xiāngtóng', vietnamese: 'adj. giống nhau' },
  { mandarin: '香', pinyin: 'xiāng', vietnamese: 'adj. thơm; ngon' },
  { mandarin: '详细', pinyin: 'xiángxì', vietnamese: 'adj. chi tiết; cẩn thận' },
  { mandarin: '响', pinyin: 'xiǎng', vietnamese: 'v. phát ra âm thanh, reo' },
  { mandarin: '橡皮', pinyin: 'xiàngpí', vietnamese: 'n. cục tẩy, gôm' },
  { mandarin: '消息', pinyin: 'xiāoxi', vietnamese: 'n. thông tin; tin tức' },
  { mandarin: '小吃', pinyin: 'xiǎochī', vietnamese: 'n. đồ ăn nhẹ; đồ ăn vặt' },
  { mandarin: '小说', pinyin: 'xiǎoshuō', vietnamese: 'n. tiểu thuyết' },
  { mandarin: '效果', pinyin: 'xiàoguǒ', vietnamese: 'n. hiệu quả; kết quả' },
  { mandarin: '笑话', pinyin: 'xiàohua', vietnamese: 'n. trò đùa; chuyện cười v. cười nhạo' },
  { mandarin: '心情', pinyin: 'xīnqíng', vietnamese: 'n. tâm trạng' },
  { mandarin: '辛苦', pinyin: 'xīnkǔ', vietnamese: 'adj. vất vả; cực nhọc' },
  { mandarin: '信封', pinyin: 'xìnfēng', vietnamese: 'n. phong bì, bao thư' },
  { mandarin: '信息', pinyin: 'xìnxī', vietnamese: 'n. thông tin; tin tức' },
  { mandarin: '信心', pinyin: 'xìnxīn', vietnamese: 'n. sự tự tin; niềm tin' },
  { mandarin: '兴奋', pinyin: 'xīngfèn', vietnamese: 'adj. hào hứng, phấn khích' },
  { mandarin: '行', pinyin: 'xíng', vietnamese: 'v. Ok! Được!' },
  { mandarin: '醒', pinyin: 'xǐng', vietnamese: 'v. tỉnh; thức dậy' },
  { mandarin: '幸福', pinyin: 'xìngfú', vietnamese: 'adj. hạnh phúc n. hạnh phúc' },
  { mandarin: '性别', pinyin: 'xìngbié', vietnamese: 'n. giới tính' },
  { mandarin: '性格', pinyin: 'xìnggé', vietnamese: 'n. tính cách; tính tình' },
  { mandarin: '修理', pinyin: 'xiūlǐ', vietnamese: 'v. sửa chữa' },
  { mandarin: '许多', pinyin: 'xǔduō', vietnamese: 'adj. nhiều; rất nhiều' },
  { mandarin: '压力', pinyin: 'yālì', vietnamese: 'n. áp lực; căng thẳng' },
  { mandarin: '牙膏', pinyin: 'yágāo', vietnamese: 'n. kem đánh răng' },
  { mandarin: '亚洲', pinyin: 'Yàzhōu', vietnamese: 'n. Châu Á' },
  { mandarin: '呀', pinyin: 'ya', vietnamese: 'mp. (thán từ) dùng ở cuối câu int. (thán từ) biểu thị sự ngạc nhiên' },
  { mandarin: '严格', pinyin: 'yángé', vietnamese: 'adj. nghiêm khắc; nghiêm ngặt' },
  { mandarin: '严重', pinyin: 'yánzhòng', vietnamese: 'adj. nghiêm trọng' },
  { mandarin: '研究', pinyin: 'yánjiū', vietnamese: 'v. điều tra; kiểm tra; xem xét' },
  { mandarin: '盐', pinyin: 'yán', vietnamese: 'n. muối' },
  { mandarin: '眼镜', pinyin: 'yǎnjìng', vietnamese: 'n. kính mắt' },
  { mandarin: '演出', pinyin: 'yǎnchū', vietnamese: 'n. buổi biểu diễn; sự trình diễn' },
  { mandarin: '演员', pinyin: 'yǎnyuán', vietnamese: 'n. diễn viên' },
  { mandarin: '阳光', pinyin: 'yángguāng', vietnamese: 'n. ánh nắng; ánh mặt trời' },
  { mandarin: '养成', pinyin: 'yǎngchéng', vietnamese: 'v. hình thành; trau dồi (thói quen)' },
  { mandarin: '样子', pinyin: 'yàngzi', vietnamese: 'n. ngoại hình; hình dạng' },
  { mandarin: '邀请', pinyin: 'yāoqǐng', vietnamese: 'v. mời' },
  { mandarin: '要是', pinyin: 'yàoshì', vietnamese: 'conj. nếu' },
  { mandarin: '钥匙', pinyin: 'yàoshi', vietnamese: 'n. chìa khóa' },
  { mandarin: '也许', pinyin: 'yěxǔ', vietnamese: 'adv. có lẽ; có thể' },
  { mandarin: '叶子', pinyin: 'yèzi', vietnamese: 'n. lá (của cây)' },
  { mandarin: '页', pinyin: 'yè', vietnamese: 'nm. trang (giấy)' },
  { mandarin: '一切', pinyin: 'yíqiè', vietnamese: 'adj. tất cả; mọi' },
  { mandarin: '以', pinyin: 'yǐ', vietnamese: 'prep. bằng cách; lấy (làm)' },
  { mandarin: '以为', pinyin: 'yǐwéi', vietnamese: 'v. nghĩ rằng; cho rằng; giả sử' },
  { mandarin: '艺术', pinyin: 'yìshù', vietnamese: 'n. nghệ thuật' },
  { mandarin: '意见', pinyin: 'yìjiàn', vietnamese: 'n. quan điểm; đề nghị; ý kiến' },
  { mandarin: '因此', pinyin: 'yīncǐ', vietnamese: 'conj. do đó; vì lý do này; do vậy' },
  { mandarin: '引起', pinyin: 'yǐnqǐ', vietnamese: 'v. mang lại; gây ra; dẫn đến' },
  { mandarin: '印象', pinyin: 'yìnxiàng', vietnamese: 'n. ấn tượng; cảm giác' },
  { mandarin: '赢', pinyin: 'yíng', vietnamese: 'v. thắng' },
  { mandarin: '应聘', pinyin: 'yìngpìn', vietnamese: 'v. ứng tuyển' },
  { mandarin: '永远', pinyin: 'yǒngyuǎn', vietnamese: 'adv. mãi mãi; vĩnh viễn' },
  { mandarin: '勇敢', pinyin: 'yǒnggǎn', vietnamese: 'adj. dũng cảm' },
  { mandarin: '优点', pinyin: 'yōudiǎn', vietnamese: 'n. ưu điểm; lợi thế' },
  { mandarin: '优秀', pinyin: 'yōuxiù', vietnamese: 'adj. xuất sắc; giỏi; ưu việt' },
  { mandarin: '幽默', pinyin: 'yōumò', vietnamese: 'adj. hài hước; dí dỏm' },
  { mandarin: '尤其', pinyin: 'yóuqí', vietnamese: 'adv. đặc biệt là' },
  { mandarin: '由', pinyin: 'yóu', vietnamese: 'prep. từ' },
  { mandarin: '由于', pinyin: 'yóuyú', vietnamese: 'prep. do; vì' },
  { mandarin: '邮局', pinyin: 'yóujú', vietnamese: 'n. bưu điện' },
  { mandarin: '友好', pinyin: 'yǒuhǎo', vietnamese: 'adj. thân thiện; hữu nghị' },
  { mandarin: '友谊', pinyin: 'yǒuyì', vietnamese: 'n. tình bạn; tình hữu nghị' },
  { mandarin: '有趣', pinyin: 'yǒuqù', vietnamese: 'adj. thú vị; hấp dẫn; vui' },
  { mandarin: '于是', pinyin: 'yúshì', vietnamese: 'conj. kết quả là; do đó' },
  { mandarin: '愉快', pinyin: 'yúkuài', vietnamese: 'adj. vui vẻ; hài lòng' },
  { mandarin: '与', pinyin: 'yǔ', vietnamese: 'prep. với; và' },
  { mandarin: '羽毛球', pinyin: 'yǔmáoqiú', vietnamese: 'n. cầu lông' },
  { mandarin: '语法', pinyin: 'yǔfǎ', vietnamese: 'n. ngữ pháp' },
  { mandarin: '语言', pinyin: 'yǔyán', vietnamese: 'n. ngôn ngữ' },
  { mandarin: '预习', pinyin: 'yùxí', vietnamese: 'v. xem trước (bài); chuẩn bị bài' },
  { mandarin: '原来', pinyin: 'yuánlái', vietnamese: 'adj. trước đây; ban đầu' },
  { mandarin: '原谅', pinyin: 'yuánliàng', vietnamese: 'v. tha thứ; bỏ qua' },
  { mandarin: '原因', pinyin: 'yuányīn', vietnamese: 'n. lý do; nguyên nhân' },
  { mandarin: '约会', pinyin: 'yuēhuì', vietnamese: 'sv. hẹn hò n. cuộc hẹn' },
  { mandarin: '阅读', pinyin: 'yuèdú', vietnamese: 'v. đọc' },
  { mandarin: '云', pinyin: 'yún', vietnamese: 'n. mây' },
  { mandarin: '允许', pinyin: 'yǔnxǔ', vietnamese: 'v. đồng ý; cho phép' },
  { mandarin: '杂志', pinyin: 'zázhì', vietnamese: 'n. tạp chí' },
  { mandarin: '咱们', pinyin: 'zánmen', vietnamese: 'pron. chúng ta (bao gồm người nghe)' },
  { mandarin: '暂时', pinyin: 'zànshí', vietnamese: 'n. tạm thời' },
  { mandarin: '脏', pinyin: 'zāng', vietnamese: 'adj. bẩn' },
  { mandarin: '责任', pinyin: 'zérèn', vietnamese: 'n. nhiệm vụ; trách nhiệm' },
  { mandarin: '增加', pinyin: 'zēngjiā', vietnamese: 'v. tăng; gia tăng' },
  { mandarin: '占线', pinyin: 'zhànxiàn', vietnamese: 'v. (đường dây) bận' },
  { mandarin: '招聘', pinyin: 'zhāopìn', vietnamese: 'v. tuyển dụng' },
  { mandarin: '照', pinyin: 'zhào', vietnamese: 'v. nhìn (vào gương)' },
  { mandarin: '真正', pinyin: 'zhēnzhèng', vietnamese: 'adj. chính hãng; thật; thực sự' },
  { mandarin: '整理', pinyin: 'zhěnglǐ', vietnamese: 'v. sắp xếp; chỉnh lý' },
  { mandarin: '正常', pinyin: 'zhèngcháng', vietnamese: 'adj. bình thường' },
  { mandarin: '正好', pinyin: 'zhènghǎo', vietnamese: 'adj. phù hợp; vừa vặn' },
  { mandarin: '正确', pinyin: 'zhèngquè', vietnamese: 'adj. đúng; chính xác' },
  { mandarin: '正式', pinyin: 'zhèngshì', vietnamese: 'adj. chính thức' },
  { mandarin: '证明', pinyin: 'zhèngmíng', vietnamese: 'v. chứng minh; chứng thực' },
  { mandarin: '之', pinyin: 'zhī', vietnamese: 'sa. (trợ từ) của, dùng để tạo thành một cấu trúc ngữ pháp' },
  { mandarin: '支持', pinyin: 'zhīchí', vietnamese: 'v. hỗ trợ; ủng hộ n. sự hỗ trợ; sự giúp đỡ' },
  { mandarin: '知识', pinyin: 'zhīshi', vietnamese: 'n. kiến thức' },
  { mandarin: '直接', pinyin: 'zhíjiē', vietnamese: 'adj. trực tiếp' },
  { mandarin: '值得', pinyin: 'zhídé', vietnamese: 'v. xứng đáng; đáng' },
  { mandarin: '职业', pinyin: 'zhíyè', vietnamese: 'n. nghề nghiệp; công việc' },
  { mandarin: '植物', pinyin: 'zhíwù', vietnamese: 'n. thực vật; cây cối' },
  { mandarin: '只好', pinyin: 'zhǐhǎo', vietnamese: 'adv. đành phải; buộc phải' },
  { mandarin: '只要', pinyin: 'zhǐyào', vietnamese: 'conj. chỉ cần' },
  { mandarin: '只有', pinyin: 'zhǐyǒu', vietnamese: 'conj. chỉ có' },
  { mandarin: '指', pinyin: 'zhǐ', vietnamese: 'v. chỉ (tay)' },
  { mandarin: '至少', pinyin: 'zhìshǎo', vietnamese: 'adv. ít nhất' },
  { mandarin: '质量', pinyin: 'zhìliàng', vietnamese: 'n. chất lượng' },
  { mandarin: '重', pinyin: 'zhòng', vietnamese: 'adj. nặng' },
  { mandarin: '重点', pinyin: 'zhòngdiǎn', vietnamese: 'n. điểm mấu chốt, trọng điểm' },
  { mandarin: '重视', pinyin: 'zhòngshì', vietnamese: 'v. coi trọng; xem trọng' },
  { mandarin: '周围', pinyin: 'zhōuwéi', vietnamese: 'n. xung quanh' },
  { mandarin: '主意', pinyin: 'zhǔyi', vietnamese: 'n. ý kiến; ý tưởng; kế hoạch' },
  { mandarin: '祝贺', pinyin: 'zhùhè', vietnamese: 'v. chúc mừng' },
  { mandarin: '著名', pinyin: 'zhùmíng', vietnamese: 'adj. nổi tiếng' },
  { mandarin: '专门', pinyin: 'zhuānmén', vietnamese: 'adv. đặc biệt; chuyên' },
  { mandarin: '专业', pinyin: 'zhuānyè', vietnamese: 'n. chuyên ngành' },
  { mandarin: '转', pinyin: 'zhuǎn', vietnamese: 'v. rẽ, quay' },
  { mandarin: '赚', pinyin: 'zhuàn', vietnamese: 'v. kiếm (lời); kiếm (tiền)' },
  { mandarin: '准确', pinyin: 'zhǔnquè', vietnamese: 'adj. chính xác' },
  { mandarin: '准时', pinyin: 'zhǔnshí', vietnamese: 'adv. đúng giờ' },
  { mandarin: '仔细', pinyin: 'zǐxì', vietnamese: 'adj. cẩn thận; tỉ mỉ' },
  { mandarin: '自然', pinyin: 'zìrán', vietnamese: 'n. thiên nhiên; tự nhiên' },
  { mandarin: '自信', pinyin: 'zìxìn', vietnamese: 'adj. tự tin' },
  { mandarin: '总结', pinyin: 'zǒngjié', vietnamese: 'v. tóm tắt; tổng kết' },
  { mandarin: '租', pinyin: 'zū', vietnamese: 'v. thuê' },
  { mandarin: '最好', pinyin: 'zuìhǎo', vietnamese: 'adv. tốt nhất là' },
  { mandarin: '最近', pinyin: 'zuìjìn', vietnamese: 'n. gần đây' },
  { mandarin: '尊重', pinyin: 'zūnzhòng', vietnamese: 'v. tôn trọng' },
  { mandarin: '左右', pinyin: 'zuǒyòu', vietnamese: 'n. khoảng; xấp xỉ' },
  { mandarin: '作家', pinyin: 'zuòjiā', vietnamese: 'n. nhà văn' },
  { mandarin: '作者', pinyin: 'zuòzhě', vietnamese: 'n. tác giả; nhà văn' },
  { mandarin: '座位', pinyin: 'zuòwèi', vietnamese: 'n. chỗ ngồi' },
];