
import { HSKWord } from './types';

export const HSK4_VOCABULARY: HSKWord[] = [
  // Bài 1 (32 từ)
  { mandarin: '法律', pinyin: 'fǎ lǜ', vietnamese: 'pháp luật' },
  { mandarin: '俩', pinyin: 'liǎ', vietnamese: 'hai, hai người' },
  { mandarin: '印象', pinyin: 'yìnxiàng', vietnamese: 'ấn tượng' },
  { mandarin: '深', pinyin: 'shēn', vietnamese: 'sâu' },
  { mandarin: '熟悉', pinyin: 'shúxī', vietnamese: 'quen thuộc' },
  { mandarin: '不仅', pinyin: 'bùjǐn', vietnamese: 'không những' },
  { mandarin: '性格', pinyin: 'xìnggé', vietnamese: 'tính cách' },
  { mandarin: '开玩笑', pinyin: 'kāiwánxiào', vietnamese: 'đùa' },
  { mandarin: '从来', pinyin: 'cónglái', vietnamese: 'từ trước tới nay' },
  { mandarin: '最好', pinyin: 'zuìhǎo', vietnamese: 'tốt nhất' },
  { mandarin: '共同', pinyin: 'gòngtóng', vietnamese: 'chung, cùng nhau' },
  { mandarin: '适合', pinyin: 'shìhé', vietnamese: 'phù hợp' },
  { mandarin: '幸福', pinyin: 'xìngfú', vietnamese: 'hạnh phúc' },
  { mandarin: '生活', pinyin: 'shēnghuó', vietnamese: 'cuộc sống' },
  { mandarin: '刚', pinyin: 'gāng', vietnamese: 'vừa mới' },
  { mandarin: '浪漫', pinyin: 'làngmàn', vietnamese: 'lãng mạn' },
  { mandarin: '够', pinyin: 'gòu', vietnamese: 'đủ' },
  { mandarin: '缺点', pinyin: 'quēdiǎn', vietnamese: 'khuyết điểm' },
  { mandarin: '接受', pinyin: 'jiēshòu', vietnamese: 'chấp nhận' },
  { mandarin: '羡慕', pinyin: 'xiànmù', vietnamese: 'ngưỡng mộ' },
  { mandarin: '爱情', pinyin: 'àiqíng', vietnamese: 'tình yêu' },
  { mandarin: '星星', pinyin: 'xīngxing', vietnamese: 'ngôi sao' },
  { mandarin: '即使', pinyin: 'jíshǐ', vietnamese: 'cho dù' },
  { mandarin: '加班', pinyin: 'jiābān', vietnamese: 'tăng ca' },
  { mandarin: '亮', pinyin: 'liàng', vietnamese: 'sáng' },
  { mandarin: '感动', pinyin: 'gǎndòng', vietnamese: 'cảm động' },
  { mandarin: '自然', pinyin: 'zìrán', vietnamese: 'tự nhiên' },
  { mandarin: '原因', pinyin: 'yuányīn', vietnamese: 'nguyên nhân' },
  { mandarin: '互相', pinyin: 'hùxiāng', vietnamese: 'lẫn nhau' },
  { mandarin: '吸引', pinyin: 'xīyǐn', vietnamese: 'thu hút' },
  { mandarin: '幽默', pinyin: 'yōumò', vietnamese: 'hài hước' },
  { mandarin: '脾气', pinyin: 'píqi', vietnamese: 'tính khí' },

  // Bài 2 (30 từ)
  { mandarin: '适应', pinyin: 'shìyìng', vietnamese: 'thích nghi' },
  { mandarin: '交', pinyin: 'jiāo', vietnamese: 'kết giao' },
  { mandarin: '平时', pinyin: 'píngshí', vietnamese: 'bình thường' },
  { mandarin: '逛街', pinyin: 'guàngjiē', vietnamese: 'dạo phố' },
  { mandarin: '短信', pinyin: 'duǎnxìn', vietnamese: 'tin nhắn' },
  { mandarin: '正好', pinyin: 'zhènghǎo', vietnamese: 'vừa vặn, đúng lúc' },
  { mandarin: '聚会', pinyin: 'jùhuì', vietnamese: 'tụ họp' },
  { mandarin: '联系', pinyin: 'liánxì', vietnamese: 'liên hệ' },
  { mandarin: '差不多', pinyin: 'chàbuduō', vietnamese: 'xấp xỉ, gần như' },
  { mandarin: '专门', pinyin: 'zhuānmén', vietnamese: 'chuyên môn, đặc biệt' },
  { mandarin: '毕业', pinyin: 'bìyè', vietnamese: 'tốt nghiệp' },
  { mandarin: '麻烦', pinyin: 'máfan', vietnamese: 'làm phiền, phiền phức' },
  { mandarin: '好像', pinyin: 'hǎoxiàng', vietnamese: 'hình như' },
  { mandarin: '重新', pinyin: 'chóngxīn', vietnamese: 'làm lại, lại lần nữa' },
  { mandarin: '尽管', pinyin: 'jǐnguǎn', vietnamese: 'cho dù' },
  { mandarin: '真正', pinyin: 'zhēnzhèng', vietnamese: 'chân chính, thật sự' },
  { mandarin: '友谊', pinyin: 'yǒuyì', vietnamese: 'tình bạn' },
  { mandarin: '丰富', pinyin: 'fēngfù', vietnamese: 'phong phú' },
  { mandarin: '无聊', pinyin: 'wúliáo', vietnamese: 'nhàm chán' },
  { mandarin: '讨厌', pinyin: 'tǎoyàn', vietnamese: 'ghét' },
  { mandarin: '却', pinyin: 'què', vietnamese: 'lại (nhưng)' },
  { mandarin: '周围', pinyin: 'zhōuwéi', vietnamese: 'xung quanh' },
  { mandarin: '交流', pinyin: 'jiāoliú', vietnamese: 'giao lưu' },
  { mandarin: '理解', pinyin: 'lǐjiě', vietnamese: 'hiểu, thông cảm' },
  { mandarin: '镜子', pinyin: 'jìngzi', vietnamese: 'cái gương' },
  { mandarin: '而', pinyin: 'ér', vietnamese: 'mà (liên từ)' },
  { mandarin: '当', pinyin: 'dāng', vietnamese: 'khi, lúc' },
  { mandarin: '困难', pinyin: 'kùnnán', vietnamese: 'khó khăn' },
  { mandarin: '及时', pinyin: 'jíshí', vietnamese: 'kịp thời' },
  { mandarin: '陪', pinyin: 'péi', vietnamese: 'cùng, theo' },

  // Bài 3 (31 từ)
  { mandarin: '挺', pinyin: 'tǐng', vietnamese: 'rất' },
  { mandarin: '紧张', pinyin: 'jǐnzhāng', vietnamese: 'căng thẳng' },
  { mandarin: '信心', pinyin: 'xìnxīn', vietnamese: 'niềm tin' },
  { mandarin: '能力', pinyin: 'nénglì', vietnamese: 'năng lực' },
  { mandarin: '招聘', pinyin: 'zhāopìn', vietnamese: 'tuyển dụng' },
  { mandarin: '提供', pinyin: 'tígōng', vietnamese: 'cung cấp' },
  { mandarin: '负责', pinyin: 'fùzé', vietnamese: 'phụ trách' },
  { mandarin: '本来', pinyin: 'běnlái', vietnamese: 'vốn dĩ' },
  { mandarin: '应聘', pinyin: 'yìngpìn', vietnamese: 'ứng tuyển' },
  { mandarin: '材料', pinyin: 'cáiliào', vietnamese: 'tài liệu' },
  { mandarin: '符合', pinyin: 'fúhé', vietnamese: 'phù hợp' },
  { mandarin: '通知', pinyin: 'tōngzhī', vietnamese: 'thông báo' },
  { mandarin: '律师', pinyin: 'lǜshī', vietnamese: 'luật sư' },
  { mandarin: '专业', pinyin: 'zhuānyè', vietnamese: 'chuyên ngành' },
  { mandarin: '另外', pinyin: 'lìngwài', vietnamese: 'ngoài ra' },
  { mandarin: '收入', pinyin: 'shōurù', vietnamese: 'thu nhập' },
  { mandarin: '咱们', pinyin: 'zánmen', vietnamese: 'chúng ta' },
  { mandarin: '安排', pinyin: 'ānpái', vietnamese: 'sắp xếp' },
  { mandarin: '首先', pinyin: 'shǒuxiān', vietnamese: 'đầu tiên' },
  { mandarin: '正式', pinyin: 'zhèngshì', vietnamese: 'chính thức' },
  { mandarin: '留', pinyin: 'liú', vietnamese: 'lưu lại' },
  { mandarin: '其次', pinyin: 'qícì', vietnamese: 'thứ hai, tiếp theo' },
  { mandarin: '诚实', pinyin: 'chéngshí', vietnamese: 'thành thật' },
  { mandarin: '改变', pinyin: 'gǎibiàn', vietnamese: 'thay đổi' },
  { mandarin: '判断', pinyin: 'pànduàn', vietnamese: 'phán đoán' },
  { mandarin: '顾客', pinyin: 'gùkè', vietnamese: 'khách hàng' },
  { mandarin: '感觉', pinyin: 'gǎnjué', vietnamese: 'cảm giác' },
  { mandarin: '准时', pinyin: 'zhǔnshí', vietnamese: 'đúng giờ' },
  { mandarin: '不管', pinyin: 'bùguǎn', vietnamese: 'cho dù' },
  { mandarin: '与', pinyin: 'yǔ', vietnamese: 'và, với' },
  { mandarin: '约会', pinyin: 'yuēhuì', vietnamese: 'hẹn hò' },

  // Bài 4 (31 từ)
  { mandarin: '提', pinyin: 'tí', vietnamese: 'nhắc đến, đề ra' },
  { mandarin: '以为', pinyin: 'yǐwéi', vietnamese: 'tưởng là' },
  { mandarin: '份', pinyin: 'fèn', vietnamese: 'phần, suất' },
  { mandarin: '完全', pinyin: 'wánquán', vietnamese: 'hoàn toàn' },
  { mandarin: '赚', pinyin: 'zhuàn', vietnamese: 'kiếm (tiền)' },
  { mandarin: '调查', pinyin: 'diàochá', vietnamese: 'điều tra' },
  { mandarin: '原来', pinyin: 'yuánlái', vietnamese: 'hóa ra, ban đầu' },
  { mandarin: '计划', pinyin: 'jìhuà', vietnamese: 'kế hoạch' },
  { mandarin: '提前', pinyin: 'tíqián', vietnamese: 'làm trước, sớm hơn' },
  { mandarin: '保证', pinyin: 'bǎozhèng', vietnamese: 'đảm bảo' },
  { mandarin: '提醒', pinyin: 'tíxǐng', vietnamese: 'nhắc nhở' },
  { mandarin: '乱', pinyin: 'luàn', vietnamese: 'loạn, bừa bộn' },
  { mandarin: '生意', pinyin: 'shēngyi', vietnamese: 'buôn bán, kinh doanh' },
  { mandarin: '谈', pinyin: 'tán', vietnamese: 'nói chuyện, đàm phán' },
  { mandarin: '并', pinyin: 'bìng', vietnamese: 'và, đồng thời' },
  { mandarin: '积累', pinyin: 'jīlěi', vietnamese: 'tích lũy' },
  { mandarin: '经验', pinyin: 'jīngyàn', vietnamese: 'kinh nghiệm' },
  { mandarin: '一切', pinyin: 'yíqiè', vietnamese: 'tất cả' },
  { mandarin: '按照', pinyin: 'ànzhào', vietnamese: 'dựa theo' },
  { mandarin: '成功', pinyin: 'chénggōng', vietnamese: 'thành công' },
  { mandarin: '顺利', pinyin: 'shùnlì', vietnamese: 'thuận lợi' },
  { mandarin: '感谢', pinyin: 'gǎnxiè', vietnamese: 'cảm ơn' },
  { mandarin: '消息', pinyin: 'xiāoxi', vietnamese: 'tin tức' },
  { mandarin: '按时', pinyin: 'ànshí', vietnamese: 'đúng hạn' },
  { mandarin: '奖金', pinyin: 'jiǎngjīn', vietnamese: 'tiền thưởng' },
  { mandarin: '工资', pinyin: 'gōngzī', vietnamese: 'tiền lương' },
  { mandarin: '方法', pinyin: 'fāngfǎ', vietnamese: 'phương pháp' },
  { mandarin: '知识', pinyin: 'zhīshi', vietnamese: 'kiến thức' },
  { mandarin: '不得不', pinyin: 'bùdébù', vietnamese: 'không thể không' },
  { mandarin: '甚至', pinyin: 'shènzhì', vietnamese: 'thậm chí' },
  { mandarin: '责任', pinyin: 'zérèn', vietnamese: 'trách nhiệm' },

  // Bài 5 (31 từ)
  { mandarin: '家具', pinyin: 'jiājù', vietnamese: 'đồ nội thất' },
  { mandarin: '沙发', pinyin: 'shāfā', vietnamese: 'ghế sofa' },
  { mandarin: '打折', pinyin: 'dǎzhé', vietnamese: 'giảm giá' },
  { mandarin: '价格', pinyin: 'jiàgé', vietnamese: 'giá cả' },
  { mandarin: '质量', pinyin: 'zhìliàng', vietnamese: 'chất lượng' },
  { mandarin: '肯定', pinyin: 'kěndìng', vietnamese: 'khẳng định, chắc chắn' },
  { mandarin: '流行', pinyin: 'liúxíng', vietnamese: 'thịnh hành' },
  { mandarin: '顺便', pinyin: 'shùnbiàn', vietnamese: 'nhân tiện' },
  { mandarin: '台', pinyin: 'tái', vietnamese: 'cái, chiếc (máy móc)' },
  { mandarin: '光', pinyin: 'guāng', vietnamese: 'chỉ, hết, sáng' },
  { mandarin: '实在', pinyin: 'shízài', vietnamese: 'thực sự' },
  { mandarin: '制冷', pinyin: 'zhìlěng', vietnamese: 'làm lạnh' },
  { mandarin: '效果', pinyin: 'xiàoguǒ', vietnamese: 'hiệu quả' },
  { mandarin: '现金', pinyin: 'xiànjīn', vietnamese: 'tiền mặt' },
  { mandarin: '邀请', pinyin: 'yāoqǐng', vietnamese: 'mời' },
  { mandarin: '葡萄', pinyin: 'pútao', vietnamese: 'nho' },
  { mandarin: '艺术', pinyin: 'yìshù', vietnamese: 'nghệ thuật' },
  { mandarin: '广告', pinyin: 'guǎnggào', vietnamese: 'quảng cáo' },
  { mandarin: '味道', pinyin: 'wèidào', vietnamese: 'mùi vị' },
  { mandarin: '优点', pinyin: 'yōudiǎn', vietnamese: 'ưu điểm' },
  { mandarin: '实际', pinyin: 'shíjì', vietnamese: 'thực tế' },
  { mandarin: '考虑', pinyin: 'kǎolǜ', vietnamese: 'suy nghĩ, cân nhắc' },
  { mandarin: '标准', pinyin: 'biāozhǔn', vietnamese: 'tiêu chuẩn' },
  { mandarin: '样子', pinyin: 'yàngzi', vietnamese: 'dáng vẻ' },
  { mandarin: '年龄', pinyin: 'niánlíng', vietnamese: 'tuổi tác' },
  { mandarin: '浪费', pinyin: 'làngfèi', vietnamese: 'lãng phí' },
  { mandarin: '购物', pinyin: 'gòuwù', vietnamese: 'mua sắm' },
  { mandarin: '尤其', pinyin: 'yóuqí', vietnamese: 'đặc biệt là' },
  { mandarin: '受到', pinyin: 'shòudào', vietnamese: 'nhận được' },
  { mandarin: '任何', pinyin: 'rènhé', vietnamese: 'bất kỳ' },
  { mandarin: '寄', pinyin: 'jì', vietnamese: 'gửi' },

  // Bài 6 (31 từ)
  { mandarin: '果汁', pinyin: 'guǒzhī', vietnamese: 'nước ép trái cây' },
  { mandarin: '售货员', pinyin: 'shòuhuòyuán', vietnamese: 'nhân viên bán hàng' },
  { mandarin: '袜子', pinyin: 'wàzi', vietnamese: 'tất, vớ' },
  { mandarin: '打扰', pinyin: 'dǎrǎo', vietnamese: 'làm phiền' },
  { mandarin: '竟然', pinyin: 'jìngrán', vietnamese: 'lại, mà lại (ngạc nhiên)' },
  { mandarin: '西红柿', pinyin: 'xīhóngshì', vietnamese: 'cà chua' },
  { mandarin: '百分之', pinyin: 'bǎifēnzhī', vietnamese: 'phần trăm' },
  { mandarin: '倍', pinyin: 'bèi', vietnamese: 'lần (gấp bội)' },
  { mandarin: '皮肤', pinyin: 'pífū', vietnamese: 'da' },
  { mandarin: '好处', pinyin: 'hǎochù', vietnamese: 'lợi ích' },
  { mandarin: '尝', pinyin: 'cháng', vietnamese: 'nếm' },
  { mandarin: '轻', pinyin: 'qīng', vietnamese: 'nhẹ' },
  { mandarin: '方面', pinyin: 'fāngmiàn', vietnamese: 'phương diện' },
  { mandarin: '值得', pinyin: 'zhídé', vietnamese: 'đáng' },
  { mandarin: '活动', pinyin: 'huódòng', vietnamese: 'hoạt động' },
  { mandarin: '内', pinyin: 'nèi', vietnamese: 'trong' },
  { mandarin: '免费', pinyin: 'miǎnfèi', vietnamese: 'miễn phí' },
  { mandarin: '修理', pinyin: 'xiūlǐ', vietnamese: 'sửa chữa' },
  { mandarin: '支持', pinyin: 'zhīchí', vietnamese: 'ủng hộ' },
  { mandarin: '举行', pinyin: 'jǔxíng', vietnamese: 'tổ chức' },
  { mandarin: '满', pinyin: 'mǎn', vietnamese: 'đầy' },
  { mandarin: '其中', pinyin: 'qízhōng', vietnamese: 'trong đó' },
  { mandarin: '小说', pinyin: 'xiǎoshuō', vietnamese: 'tiểu thuyết' },
  { mandarin: '会员卡', pinyin: 'huìyuánkǎ', vietnamese: 'thẻ hội viên' },
  { mandarin: '所有', pinyin: 'suǒyǒu', vietnamese: 'tất cả' },
  { mandarin: '获得', pinyin: 'huòdé', vietnamese: 'đạt được' },
  { mandarin: '情况', pinyin: 'qíngkuàng', vietnamese: 'tình hình' },
  { mandarin: '例如', pinyin: 'lìrú', vietnamese: 'ví dụ' },
  { mandarin: '举办', pinyin: 'jǔbàn', vietnamese: 'tổ chức' },
  { mandarin: '各', pinyin: 'gè', vietnamese: 'các, mỗi' },
  { mandarin: '降低', pinyin: 'jiàngdī', vietnamese: 'giảm thấp' },

  // Bài 7 (34 từ)
  { mandarin: '流血', pinyin: 'liúxiě', vietnamese: 'chảy máu' },
  { mandarin: '擦', pinyin: 'cā', vietnamese: 'lau' },
  { mandarin: '气候', pinyin: 'qìhòu', vietnamese: 'khí hậu' },
  { mandarin: '估计', pinyin: 'gūjì', vietnamese: 'ước tính' },
  { mandarin: '咳嗽', pinyin: 'késou', vietnamese: 'ho' },
  { mandarin: '严重', pinyin: 'yánzhòng', vietnamese: 'nghiêm trọng' },
  { mandarin: '窗户', pinyin: 'chuānghu', vietnamese: 'cửa sổ' },
  { mandarin: '空气', pinyin: 'kōngqì', vietnamese: 'không khí' },
  { mandarin: '抽烟', pinyin: 'chōuyān', vietnamese: 'hút thuốc' },
  { mandarin: '动作', pinyin: 'dòngzuò', vietnamese: 'động tác' },
  { mandarin: '帅', pinyin: 'shuài', vietnamese: 'đẹp trai' },
  { mandarin: '出现', pinyin: 'chūxiàn', vietnamese: 'xuất hiện' },
  { mandarin: '后悔', pinyin: 'hòuhuǐ', vietnamese: 'hối hận' },
  { mandarin: '来不及', pinyin: 'láibují', vietnamese: 'không kịp' },
  { mandarin: '反对', pinyin: 'fǎnduì', vietnamese: 'phản đối' },
  { mandarin: '大夫', pinyin: 'dàifu', vietnamese: 'bác sĩ' },
  { mandarin: '植物', pinyin: 'zhíwù', vietnamese: 'thực vật' },
  { mandarin: '研究', pinyin: 'yánjiū', vietnamese: 'nghiên cứu' },
  { mandarin: '超过', pinyin: 'chāoguò', vietnamese: 'vượt quá' },
  { mandarin: '散步', pinyin: 'sànbù', vietnamese: 'tản bộ' },
  { mandarin: '指', pinyin: 'zhǐ', vietnamese: 'chỉ (tay)' },
  { mandarin: '精神', pinyin: 'jīngshén', vietnamese: 'tinh thần' },
  { mandarin: '教授', pinyin: 'jiàoshòu', vietnamese: 'giáo sư' },
  { mandarin: '数字', pinyin: 'shùzì', vietnamese: 'con số' },
  { mandarin: '说明', pinyin: 'shuōmíng', vietnamese: 'giải thích' },
  { mandarin: '要是', pinyin: 'yàoshi', vietnamese: 'nếu như' },
  { mandarin: '既', pinyin: 'jì', vietnamese: 'đã (liên từ)' },
  { mandarin: '减肥', pinyin: 'jiǎnféi', vietnamese: 'giảm cân' },
  { mandarin: '辛苦', pinyin: 'xīnkǔ', vietnamese: 'vất vả' },
  { mandarin: '肚子', pinyin: 'dùzi', vietnamese: 'bụng' },
  { mandarin: '感情', pinyin: 'gǎnqíng', vietnamese: 'tình cảm' },
  { mandarin: '烦恼', pinyin: 'fánnǎo', vietnamese: 'phiền não' },
  { mandarin: '掉', pinyin: 'diào', vietnamese: 'rơi' },
  { mandarin: '跑掉', pinyin: 'pǎodiào', vietnamese: 'chạy mất' },

  // Bài 8 (29 từ)
  { mandarin: '巧克力', pinyin: 'qiǎokèlì', vietnamese: 'sô cô la' },
  { mandarin: '亲戚', pinyin: 'qīnqi', vietnamese: 'họ hàng' },
  { mandarin: '伤心', pinyin: 'shāngxīn', vietnamese: 'đau lòng' },
  { mandarin: '使', pinyin: 'shǐ', vietnamese: 'khiến, làm cho' },
  { mandarin: '心情', pinyin: 'xīnqíng', vietnamese: 'tâm trạng' },
  { mandarin: '愉快', pinyin: 'yúkuài', vietnamese: 'vui vẻ' },
  { mandarin: '景色', pinyin: 'jǐngsè', vietnamese: 'phong cảnh' },
  { mandarin: '放松', pinyin: 'fàngsōng', vietnamese: 'thư giãn' },
  { mandarin: '压力', pinyin: 'yālì', vietnamese: 'áp lực' },
  { mandarin: '回忆', pinyin: 'huíyì', vietnamese: 'hồi ức' },
  { mandarin: '发生', pinyin: 'fāshēng', vietnamese: 'xảy ra' },
  { mandarin: '成为', pinyin: 'chéngwéi', vietnamese: 'trở thành' },
  { mandarin: '只要', pinyin: 'zhǐyào', vietnamese: 'chỉ cần' },
  { mandarin: '师傅', pinyin: 'shīfu', vietnamese: 'sư phụ, bác tài' },
  { mandarin: '大使馆', pinyin: 'dàshǐguǎn', vietnamese: 'đại sứ quán' },
  { mandarin: '堵车', pinyin: 'dǔchē', vietnamese: 'tắc đường' },
  { mandarin: '距离', pinyin: 'jùlí', vietnamese: 'khoảng cách' },
  { mandarin: '耐心', pinyin: 'nàixīn', vietnamese: 'kiên nhẫn' },
  { mandarin: '生命', pinyin: 'shēngmìng', vietnamese: 'sinh mệnh' },
  { mandarin: '缺少', pinyin: 'quēshǎo', vietnamese: 'thiếu' },
  { mandarin: '到处', pinyin: 'dàochù', vietnamese: 'khắp nơi' },
  { mandarin: '态度', pinyin: 'tàidù', vietnamese: 'thái độ' },
  { mandarin: '因此', pinyin: 'yīncǐ', vietnamese: 'vì vậy' },
  { mandarin: '科学', pinyin: 'kēxué', vietnamese: 'khoa học' },
  { mandarin: '证明', pinyin: 'zhèngmíng', vietnamese: 'chứng minh' },
  { mandarin: '往往', pinyin: 'wǎngwǎng', vietnamese: 'thường hay' },
  { mandarin: '阳光', pinyin: 'yángguāng', vietnamese: 'ánh nắng' },
  { mandarin: '积极', pinyin: 'jījí', vietnamese: 'tích cực' },
  { mandarin: '特点', pinyin: 'tèdiǎn', vietnamese: 'đặc điểm' },

  // Bài 9 (31 từ)
  { mandarin: '饼干', pinyin: 'bǐnggān', vietnamese: 'bánh quy' },
  { mandarin: '难道', pinyin: 'nándào', vietnamese: 'lẽ nào' },
  { mandarin: '得', pinyin: 'děi', vietnamese: 'phải' },
  { mandarin: '坚持', pinyin: 'jiānchí', vietnamese: 'kiên trì' },
  { mandarin: '放弃', pinyin: 'fàngqì', vietnamese: 'từ bỏ' },
  { mandarin: '主意', pinyin: 'zhǔyi', vietnamese: 'ý kiến, sáng kiến' },
  { mandarin: '网球', pinyin: 'wǎngqiú', vietnamese: 'quần vợt' },
  { mandarin: '国际', pinyin: 'guójì', vietnamese: 'quốc tế' },
  { mandarin: '轻松', pinyin: 'qīngsōng', vietnamese: 'nhẹ nhàng' },
  { mandarin: '赢', pinyin: 'yíng', vietnamese: 'thắng' },
  { mandarin: '随便', pinyin: 'suíbiàn', vietnamese: 'tùy ý' },
  { mandarin: '汗', pinyin: 'hàn', vietnamese: 'mồ hôi' },
  { mandarin: '通过', pinyin: 'tōngguò', vietnamese: 'thông qua' },
  { mandarin: '篇', pinyin: 'piān', vietnamese: 'bài (lượng từ)' },
  { mandarin: '作家', pinyin: 'zuòjiā', vietnamese: 'nhà văn' },
  { mandarin: '当时', pinyin: 'dāngshí', vietnamese: 'lúc đó' },
  { mandarin: '可是', pinyin: 'kěshì', vietnamese: 'nhưng' },
  { mandarin: '正确', pinyin: 'zhèngquè', vietnamese: 'chính xác' },
  { mandarin: '理想', pinyin: 'lǐxiǎng', vietnamese: 'lý tưởng' },
  { mandarin: '勇敢', pinyin: 'yǒnggǎn', vietnamese: 'dũng cảm' },
  { mandarin: '结果', pinyin: 'jiéguǒ', vietnamese: 'kết quả' },
  { mandarin: '失败', pinyin: 'shībài', vietnamese: 'thất bại' },
  { mandarin: '过程', pinyin: 'guòchéng', vietnamese: 'quá trình' },
  { mandarin: '至少', pinyin: 'zhìshǎo', vietnamese: 'ít nhất' },
  { mandarin: '总结', pinyin: 'zǒngjié', vietnamese: 'tổng kết' },
  { mandarin: '取', pinyin: 'qǔ', vietnamese: 'lấy' },
  { mandarin: '经历', pinyin: 'jīnglì', vietnamese: 'trải nghiệm' },
  { mandarin: '许多', pinyin: 'xǔduō', vietnamese: 'rất nhiều' },
  { mandarin: '区别', pinyin: 'qūbié', vietnamese: 'khác biệt' },
  { mandarin: '暂时', pinyin: 'zànshí', vietnamese: 'tạm thời' },
  { mandarin: '面对', pinyin: 'miànduì', vietnamese: 'đối mặt' },

  // Bài 10 (30 từ)
  { mandarin: '礼拜天', pinyin: 'lǐbàitiān', vietnamese: 'chủ nhật' },
  { mandarin: '空儿', pinyin: 'kòngr', vietnamese: 'rảnh rỗi' },
  { mandarin: '母亲', pinyin: 'mǔqīn', vietnamese: 'mẹ' },
  { mandarin: '不过', pinyin: 'búguò', vietnamese: 'nhưng, có điều' },
  { mandarin: '永远', pinyin: 'yǒngyuǎn', vietnamese: 'mãi mãi' },
  { mandarin: '方向', pinyin: 'fāngxiàng', vietnamese: 'phương hướng' },
  { mandarin: '优秀', pinyin: 'yōuxiù', vietnamese: 'ưu tú' },
  { mandarin: '硕士', pinyin: 'shuòshì', vietnamese: 'thạc sĩ' },
  { mandarin: '翻译', pinyin: 'fānyì', vietnamese: 'phiên dịch' },
  { mandarin: '确实', pinyin: 'quèshí', vietnamese: 'xác thực' },
  { mandarin: '兴奋', pinyin: 'xīngfèn', vietnamese: 'hưng phấn' },
  { mandarin: '拉', pinyin: 'lā', vietnamese: 'kéo' },
  { mandarin: '建议', pinyin: 'jiànyì', vietnamese: 'kiến nghị' },
  { mandarin: '职业', pinyin: 'zhíyè', vietnamese: 'nghề nghiệp' },
  { mandarin: '关键', pinyin: 'guānjiàn', vietnamese: 'mấu chốt' },
  { mandarin: '将来', pinyin: 'jiānglái', vietnamese: 'tương lai' },
  { mandarin: '发展', pinyin: 'fāzhǎn', vietnamese: 'phát triển' },
  { mandarin: '躺', pinyin: 'tǎng', vietnamese: 'nằm' },
  { mandarin: '困', pinyin: 'kùn', vietnamese: 'buồn ngủ' },
  { mandarin: '经济', pinyin: 'jīngjì', vietnamese: 'kinh tế' },
  { mandarin: '条件', pinyin: 'tiáojiàn', vietnamese: 'điều kiện' },
  { mandarin: '富', pinyin: 'fù', vietnamese: 'giàu' },
  { mandarin: '穷', pinyin: 'qióng', vietnamese: 'nghèo' },
  { mandarin: '等', pinyin: 'děng', vietnamese: 'vân vân, đợi' },
  { mandarin: '由于', pinyin: 'yóuyú', vietnamese: 'bởi vì' },
  { mandarin: '比如', pinyin: 'bǐrú', vietnamese: 'ví dụ' },
  { mandarin: '橡皮', pinyin: 'xiàngpí', vietnamese: 'cục tẩy' },
  { mandarin: '糖', pinyin: 'táng', vietnamese: 'đường, kẹo' },
  { mandarin: '低', pinyin: 'dī', vietnamese: 'thấp' },
  { mandarin: '答案', pinyin: 'dá\'àn', vietnamese: 'đáp án' },

  // Bài 11 (30 từ)
  { mandarin: '内容', pinyin: 'nèiróng', vietnamese: 'nội dung' },
  { mandarin: '流利', pinyin: 'liúlì', vietnamese: 'lưu loát' },
  { mandarin: '厉害', pinyin: 'lìhai', vietnamese: 'lợi hại' },
  { mandarin: '语法', pinyin: 'yǔfǎ', vietnamese: 'ngữ pháp' },
  { mandarin: '准确', pinyin: 'zhǔnquè', vietnamese: 'chính xác' },
  { mandarin: '词语', pinyin: 'cíyǔ', vietnamese: 'từ ngữ' },
  { mandarin: '连', pinyin: 'lián', vietnamese: 'ngay cả' },
  { mandarin: '阅读', pinyin: 'yuèdú', vietnamese: 'đọc' },
  { mandarin: '来得及', pinyin: 'láidejí', vietnamese: 'kịp' },
  { mandarin: '来不及', pinyin: 'láibují', vietnamese: 'không kịp' },
  { mandarin: '复杂', pinyin: 'fùzá', vietnamese: 'phức tạp' },
  { mandarin: '只好', pinyin: 'zhǐhǎo', vietnamese: 'đành phải' },
  { mandarin: '填空', pinyin: 'tiánkòng', vietnamese: 'điền vào chỗ trống' },
  { mandarin: '猜', pinyin: 'cāi', vietnamese: 'đoán' },
  { mandarin: '否则', pinyin: 'fǒuzé', vietnamese: 'nếu không thì' },
  { mandarin: '客厅', pinyin: 'kètīng', vietnamese: 'phòng khách' },
  { mandarin: '无论', pinyin: 'wúlùn', vietnamese: 'bất luận' },
  { mandarin: '杂志', pinyin: 'zázhì', vietnamese: 'tạp chí' },
  { mandarin: '著名', pinyin: 'zhùmíng', vietnamese: 'nổi tiếng' },
  { mandarin: '增加', pinyin: 'zēngjiā', vietnamese: 'tăng thêm' },
  { mandarin: '文章', pinyin: 'wénzhāng', vietnamese: 'bài văn' },
  { mandarin: '之', pinyin: 'zhī', vietnamese: 'của (trợ từ)' },
  { mandarin: '然而', pinyin: 'rán\'ér', vietnamese: 'nhưng mà' },
  { mandarin: '看法', pinyin: 'kànfǎ', vietnamese: 'cách nhìn' },
  { mandarin: '相同', pinyin: 'xiāngtóng', vietnamese: 'giống nhau' },
  { mandarin: '顺序', pinyin: 'shùnxù', vietnamese: 'thứ tự' },
  { mandarin: '表示', pinyin: 'biǎoshì', vietnamese: 'biểu thị' },
  { mandarin: '养成', pinyin: 'yǎngchéng', vietnamese: 'nuôi dưỡng, hình thành' },
  { mandarin: '同时', pinyin: 'tóngshí', vietnamese: 'đồng thời' },
  { mandarin: '精彩', pinyin: 'jīngcǎi', vietnamese: 'đặc sắc' },

  // Bài 12 (33 từ)
  { mandarin: '规定', pinyin: 'guīdìng', vietnamese: 'quy định' },
  { mandarin: '死', pinyin: 'sǐ', vietnamese: 'chết, cứng nhắc' },
  { mandarin: '可惜', pinyin: 'kěxī', vietnamese: 'đáng tiếc' },
  { mandarin: '全部', pinyin: 'quánbù', vietnamese: 'toàn bộ' },
  { mandarin: '也许', pinyin: 'yěxǔ', vietnamese: 'có lẽ' },
  { mandarin: '商量', pinyin: 'shāngliang', vietnamese: 'thương lượng' },
  { mandarin: '并且', pinyin: 'bìngqiě', vietnamese: 'và, đồng thời' },
  { mandarin: '盐', pinyin: 'yán', vietnamese: 'muối' },
  { mandarin: '勺子', pinyin: 'sháozi', vietnamese: 'cái thìa' },
  { mandarin: '保护', pinyin: 'bǎohù', vietnamese: 'bảo vệ' },
  { mandarin: '作用', pinyin: 'zuòyòng', vietnamese: 'tác dụng' },
  { mandarin: '无法', pinyin: 'wúfǎ', vietnamese: 'không thể' },
  { mandarin: '无', pinyin: 'wú', vietnamese: 'không' },
  { mandarin: '节', pinyin: 'jié', vietnamese: 'tiết, đoạn' },
  { mandarin: '详细', pinyin: 'xiángxì', vietnamese: 'chi tiết' },
  { mandarin: '解释', pinyin: 'jiěshì', vietnamese: 'giải thích' },
  { mandarin: '对于', pinyin: 'duìyú', vietnamese: 'đối với' },
  { mandarin: '叶子', pinyin: 'yèzi', vietnamese: 'lá cây' },
  { mandarin: '教育', pinyin: 'jiàoyù', vietnamese: 'giáo dục' },
  { mandarin: '使用', pinyin: 'shǐyòng', vietnamese: 'sử dụng' },
  { mandarin: '语言', pinyin: 'yǔyán', vietnamese: 'ngôn ngữ' },
  { mandarin: '直接', pinyin: 'zhíjiē', vietnamese: 'trực tiếp' },
  { mandarin: '引起', pinyin: 'yǐnqǐ', vietnamese: 'dẫn đến' },
  { mandarin: '误会', pinyin: 'wùhuì', vietnamese: 'hiểu lầm' },
  { mandarin: '友好', pinyin: 'yǒuhǎo', vietnamese: 'thân thiện' },
  { mandarin: '事半功倍', pinyin: 'shìbàngōngbèi', vietnamese: 'làm ít công to' },
  { mandarin: '节约', pinyin: 'jiéyuē', vietnamese: 'tiết kiệm' },
  { mandarin: '力气', pinyin: 'lìqi', vietnamese: 'sức lực' },
  { mandarin: '相反', pinyin: 'xiāngfǎn', vietnamese: 'tương phản' },
  { mandarin: '任务', pinyin: 'rènwu', vietnamese: 'nhiệm vụ' },
  { mandarin: '意见', pinyin: 'yìjiàn', vietnamese: 'ý kiến' },
  { mandarin: '仔细', pinyin: 'zǐxì', vietnamese: 'tỉ mỉ' },
  { mandarin: '达到', pinyin: 'dádào', vietnamese: 'đạt được' },

  // Bài 13 (32 từ)
  { mandarin: '京剧', pinyin: 'jīngjù', vietnamese: 'kinh kịch' },
  { mandarin: '演员', pinyin: 'yǎnyuán', vietnamese: 'diễn viên' },
  { mandarin: '观众', pinyin: 'guānzhòng', vietnamese: 'khán giả' },
  { mandarin: '厚', pinyin: 'hòu', vietnamese: 'dày' },
  { mandarin: '演出', pinyin: 'yǎnchū', vietnamese: 'biểu diễn' },
  { mandarin: '大概', pinyin: 'dàgài', vietnamese: 'khoảng, đại khái' },
  { mandarin: '来自', pinyin: 'láizì', vietnamese: 'đến từ' },
  { mandarin: '遍', pinyin: 'biàn', vietnamese: 'lần (lượng từ)' },
  { mandarin: '偶尔', pinyin: 'ǒu\'ěr', vietnamese: 'thỉnh thoảng' },
  { mandarin: '吃惊', pinyin: 'chījīng', vietnamese: 'ngạc nhiên' },
  { mandarin: '基础', pinyin: 'jīchǔ', vietnamese: 'cơ sở' },
  { mandarin: '表演', pinyin: 'biǎoyǎn', vietnamese: 'biểu diễn' },
  { mandarin: '正常', pinyin: 'zhèngcháng', vietnamese: 'bình thường' },
  { mandarin: '申请', pinyin: 'shēnqǐng', vietnamese: 'xin, đăng ký' },
  { mandarin: '有趣', pinyin: 'yǒuqù', vietnamese: 'thú vị' },
  { mandarin: '开心', pinyin: 'kāixīn', vietnamese: 'vui vẻ' },
  { mandarin: '继续', pinyin: 'jìxù', vietnamese: 'tiếp tục' },
  { mandarin: '由', pinyin: 'yóu', vietnamese: 'do (giới từ)' },
  { mandarin: '讨论', pinyin: 'tǎolùn', vietnamese: 'thảo luận' },
  { mandarin: '大约', pinyin: 'dàyuē', vietnamese: 'khoảng chừng' },
  { mandarin: '餐厅', pinyin: 'cāntīng', vietnamese: 'nhà hàng' },
  { mandarin: '纸袋', pinyin: 'zhǐdài', vietnamese: 'túi giấy' },
  { mandarin: '互联网', pinyin: 'hùliánwǎng', vietnamese: 'internet' },
  { mandarin: '进行', pinyin: 'jìnxíng', vietnamese: 'tiến hành' },
  { mandarin: '错误', pinyin: 'cuòwù', vietnamese: 'sai lầm' },
  { mandarin: '随着', pinyin: 'suízhe', vietnamese: 'cùng với' },
  { mandarin: '十分', pinyin: 'shífēn', vietnamese: 'vô cùng' },
  { mandarin: '普遍', pinyin: 'pǔbiàn', vietnamese: 'phổ biến' },
  { mandarin: '部分', pinyin: 'bùfen', vietnamese: 'bộ phận' },
  { mandarin: '稍微', pinyin: 'shāowēi', vietnamese: 'hơi hơi' },
  { mandarin: '苦', pinyin: 'kǔ', vietnamese: 'khổ, đắng' },
  { mandarin: '省', pinyin: 'shěng', vietnamese: 'tỉnh, tiết kiệm' },

  // Bài 14 (32 từ)
  { mandarin: '出差', pinyin: 'chūchāi', vietnamese: 'đi công tác' },
  { mandarin: '毛巾', pinyin: 'máojīn', vietnamese: 'khăn mặt' },
  { mandarin: '牙膏', pinyin: 'yágāo', vietnamese: 'kem đánh răng' },
  { mandarin: '重', pinyin: 'zhòng', vietnamese: 'nặng' },
  { mandarin: '行', pinyin: 'xíng', vietnamese: 'được, đi' },
  { mandarin: '省', pinyin: 'shěng', vietnamese: 'tiết kiệm' },
  { mandarin: '污染', pinyin: 'wūrǎn', vietnamese: 'ô nhiễm' },
  { mandarin: '卫生间', pinyin: 'wèishēngjiān', vietnamese: 'nhà vệ sinh' },
  { mandarin: '脏', pinyin: 'zāng', vietnamese: 'bẩn' },
  { mandarin: '抱歉', pinyin: 'bàoqiàn', vietnamese: 'xin lỗi' },
  { mandarin: '空', pinyin: 'kōng', vietnamese: 'trống' },
  { mandarin: '盒子', pinyin: 'hézi', vietnamese: 'cái hộp' },
  { mandarin: '扔', pinyin: 'rēng', vietnamese: 'ném, vứt' },
  { mandarin: '以', pinyin: 'yǐ', vietnamese: 'lấy, để' },
  { mandarin: '速度', pinyin: 'sùdù', vietnamese: 'tốc độ' },
  { mandarin: '地球', pinyin: 'dìqiú', vietnamese: 'trái đất' },
  { mandarin: '既然', pinyin: 'jìrán', vietnamese: 'đã (liên từ)' },
  { mandarin: '停', pinyin: 'tíng', vietnamese: 'dừng' },
  { mandarin: '得意', pinyin: 'déyì', vietnamese: 'đắc ý' },
  { mandarin: '目的', pinyin: 'mùdì', vietnamese: 'mục đích' },
  { mandarin: '暖', pinyin: 'nuǎn', vietnamese: 'ấm' },
  { mandarin: '塑料袋', pinyin: 'sùliàodài', vietnamese: 'túi nilon' },
  { mandarin: '于是', pinyin: 'yúshì', vietnamese: 'thế là' },
  { mandarin: '鼓励', pinyin: 'gǔlì', vietnamese: 'cổ vũ' },
  { mandarin: '拒绝', pinyin: 'jùjué', vietnamese: 'từ chối' },
  { mandarin: '减少', pinyin: 'jiǎnshǎo', vietnamese: 'giảm bớt' },
  { mandarin: '数量', pinyin: 'shùliàng', vietnamese: 'số lượng' },
  { mandarin: '温度', pinyin: 'wēndù', vietnamese: 'nhiệt độ' },
  { mandarin: '乘坐', pinyin: 'chéngzuò', vietnamese: 'ngồi (xe, tàu)' },
  { mandarin: '丢', pinyin: 'diū', vietnamese: 'mất, vứt' },
  { mandarin: '垃圾桶', pinyin: 'lājītǒng', vietnamese: 'thùng rác' },
  { mandarin: '美丽', pinyin: 'měilì', vietnamese: 'xinh đẹp' },

  // Bài 15 (31 từ)
  { mandarin: '弹钢琴', pinyin: 'tángāngqín', vietnamese: 'chơi đàn piano' },
  { mandarin: '棒', pinyin: 'bàng', vietnamese: 'giỏi, tuyệt' },
  { mandarin: '孙子', pinyin: 'sūnzi', vietnamese: 'cháu trai' },
  { mandarin: '寒假', pinyin: 'hánjià', vietnamese: 'nghỉ đông' },
  { mandarin: '父亲', pinyin: 'fùqīn', vietnamese: 'cha' },
  { mandarin: '闹钟', pinyin: 'nàozhōng', vietnamese: 'đồng hồ báo thức' },
  { mandarin: '响', pinyin: 'xiǎng', vietnamese: 'kêu, vang' },
  { mandarin: '醒', pinyin: 'xǐng', vietnamese: 'tỉnh' },
  { mandarin: '赶', pinyin: 'gǎn', vietnamese: 'đuổi theo, vội' },
  { mandarin: '厕所', pinyin: 'cèsuǒ', vietnamese: 'nhà vệ sinh' },
  { mandarin: '批评', pinyin: 'pīpíng', vietnamese: 'phê bình' },
  { mandarin: '弄', pinyin: 'nòng', vietnamese: 'làm' },
  { mandarin: '管理', pinyin: 'guǎnlǐ', vietnamese: 'quản lý' },
  { mandarin: '打针', pinyin: 'dǎzhēn', vietnamese: 'tiêm' },
  { mandarin: '护士', pinyin: 'hùshi', vietnamese: 'y tá' },
  { mandarin: '表扬', pinyin: 'biǎoyáng', vietnamese: 'tuyên dương' },
  { mandarin: '千万', pinyin: 'qiānwàn', vietnamese: 'nhất thiết' },
  { mandarin: '怀疑', pinyin: 'huáiyí', vietnamese: 'nghi ngờ' },
  { mandarin: '故意', pinyin: 'gùyì', vietnamese: 'cố ý' },
  { mandarin: '敲', pinyin: 'qiāo', vietnamese: 'gõ' },
  { mandarin: '整理', pinyin: 'zhěnglǐ', vietnamese: 'chỉnh lý, sắp xếp' },
  { mandarin: '合适', pinyin: 'héshì', vietnamese: 'thích hợp' },
  { mandarin: '骗', pinyin: 'piàn', vietnamese: 'lừa' },
  { mandarin: '儿童', pinyin: 'értóng', vietnamese: 'nhi đồng' },
  { mandarin: '假', pinyin: 'jiǎ', vietnamese: 'giả' },
  { mandarin: '左右', pinyin: 'zuǒyòu', vietnamese: 'khoảng, trái phải' },
  { mandarin: '懒', pinyin: 'lǎn', vietnamese: 'lười' },
  { mandarin: '笨', pinyin: 'bèn', vietnamese: 'ngốc' },
  { mandarin: '粗心', pinyin: 'cūxīn', vietnamese: 'cẩu thả' },
  { mandarin: '骄傲', pinyin: 'jiāo\'ào', vietnamese: 'kiêu ngạo' },
  { mandarin: '害羞', pinyin: 'hàixiū', vietnamese: 'xấu hổ' },

  // Bài 16 (31 từ)
  { mandarin: '博士', pinyin: 'bóshì', vietnamese: 'tiến sĩ' },
  { mandarin: '签证', pinyin: 'qiānzhèng', vietnamese: 'visa' },
  { mandarin: '报名', pinyin: 'bàomíng', vietnamese: 'báo danh' },
  { mandarin: '表格', pinyin: 'biǎogé', vietnamese: 'biểu bảng' },
  { mandarin: '传真', pinyin: 'chuánzhēn', vietnamese: 'fax' },
  { mandarin: '号码', pinyin: 'hàomǎ', vietnamese: 'số' },
  { mandarin: '参观', pinyin: 'cānguān', vietnamese: 'tham quan' },
  { mandarin: '激动', pinyin: 'jīdòng', vietnamese: 'xúc động' },
  { mandarin: '小伙子', pinyin: 'xiǎohuǒzi', vietnamese: 'chàng trai trẻ' },
  { mandarin: '记者', pinyin: 'jìzhě', vietnamese: 'phóng viên' },
  { mandarin: '代表', pinyin: 'dàibiǎo', vietnamese: 'đại biểu' },
  { mandarin: '恐怕', pinyin: 'kǒngpà', vietnamese: 'e rằng' },
  { mandarin: '失望', pinyin: 'shīwàng', vietnamese: 'thất vọng' },
  { mandarin: '郊区', pinyin: 'jiāoqū', vietnamese: 'ngoại ô' },
  { mandarin: '到底', pinyin: 'dàodǐ', vietnamese: 'rốt cuộc' },
  { mandarin: '呀', pinyin: 'ya', vietnamese: 'a, nha (trợ từ)' },
  { mandarin: '导游', pinyin: 'dǎoyóu', vietnamese: 'hướng dẫn viên' },
  { mandarin: '礼貌', pinyin: 'lǐmào', vietnamese: 'lễ phép' },
  { mandarin: '原谅', pinyin: 'yuánliàng', vietnamese: 'tha thứ' },
  { mandarin: '挂', pinyin: 'guà', vietnamese: 'treo' },
  { mandarin: '同情', pinyin: 'tóngqíng', vietnamese: 'đồng tình' },
  { mandarin: '推', pinyin: 'tuī', vietnamese: 'đẩy' },
  { mandarin: '预习', pinyin: 'yùxí', vietnamese: 'chuẩn bị bài' },
  { mandarin: '重点', pinyin: 'zhòngdiǎn', vietnamese: 'trọng điểm' },
  { mandarin: '马虎', pinyin: 'mǎhu', vietnamese: 'qua loa' },
  { mandarin: '自信', pinyin: 'zìxìn', vietnamese: 'tự tin' },
  { mandarin: '冷静', pinyin: 'lěngjìng', vietnamese: 'bình tĩnh' },
  { mandarin: '输', pinyin: 'shū', vietnamese: 'thua' },
  { mandarin: '重视', pinyin: 'zhòngshì', vietnamese: 'coi trọng' },
  { mandarin: '敢', pinyin: 'gǎn', vietnamese: 'dám' },
  { mandarin: '尊重', pinyin: 'zūnzhòng', vietnamese: 'tôn trọng' },

  // Bài 17 (29 từ)
  { mandarin: '凉快', pinyin: 'liángkuai', vietnamese: 'mát mẻ' },
  { mandarin: '热闹', pinyin: 'rènao', vietnamese: 'náo nhiệt' },
  { mandarin: '云', pinyin: 'yún', vietnamese: 'mây' },
  { mandarin: '广播', pinyin: 'guǎngbō', vietnamese: 'phát thanh' },
  { mandarin: '照', pinyin: 'zhào', vietnamese: 'chiếu, chụp' },
  { mandarin: '倒', pinyin: 'dào', vietnamese: 'đổ, ngược' },
  { mandarin: '毛', pinyin: 'máo', vietnamese: 'lông' },
  { mandarin: '抱', pinyin: 'bào', vietnamese: 'ôm' },
  { mandarin: '干', pinyin: 'gàn', vietnamese: 'làm' },
  { mandarin: '严格', pinyin: 'yángé', vietnamese: 'nghiêm khắc' },
  { mandarin: '难受', pinyin: 'nánshòu', vietnamese: 'khó chịu' },
  { mandarin: '趟', pinyin: 'tàng', vietnamese: 'chuyến' },
  { mandarin: '放暑假', pinyin: 'fàngshǔjià', vietnamese: 'nghỉ hè' },
  { mandarin: '老虎', pinyin: 'lǎohǔ', vietnamese: 'con hổ' },
  { mandarin: '入口', pinyin: 'rùkǒu', vietnamese: 'lối vào' },
  { mandarin: '排队', pinyin: 'páiduì', vietnamese: 'xếp hàng' },
  { mandarin: '活泼', pinyin: 'huópō', vietnamese: 'hoạt bát' },
  { mandarin: '社会', pinyin: 'shèhuì', vietnamese: 'xã hội' },
  { mandarin: '竞争', pinyin: 'jìngzhēng', vietnamese: 'cạnh tranh' },
  { mandarin: '森林', pinyin: 'sēnlín', vietnamese: 'rừng rậm' },
  { mandarin: '剩', pinyin: 'shèng', vietnamese: 'thừa, còn lại' },
  { mandarin: '暖和', pinyin: 'nuǎnhuo', vietnamese: 'ấm áp' },
  { mandarin: '海洋', pinyin: 'hǎiyáng', vietnamese: 'đại dương' },
  { mandarin: '底', pinyin: 'dǐ', vietnamese: 'đáy' },
  { mandarin: '美人鱼', pinyin: 'měirényú', vietnamese: 'nàng tiên cá' },
  { mandarin: '公里', pinyin: 'gōnglǐ', vietnamese: 'kilomet' },
  { mandarin: '仍然', pinyin: 'réngrán', vietnamese: 'vẫn' },
  { mandarin: '排列', pinyin: 'páiliè', vietnamese: 'sắp xếp' },
  { mandarin: '梦', pinyin: 'mèng', vietnamese: 'giấc mơ' },

  // Bài 18 (32 từ)
  { mandarin: '降落', pinyin: 'jiàngluò', vietnamese: 'hạ cánh' },
  { mandarin: '火', pinyin: 'huǒ', vietnamese: 'lửa, nóng (nổi tiếng)' },
  { mandarin: '作者', pinyin: 'zuòzhě', vietnamese: 'tác giả' },
  { mandarin: '交通', pinyin: 'jiāotōng', vietnamese: 'giao thông' },
  { mandarin: '技术', pinyin: 'jìshù', vietnamese: 'kỹ thuật' },
  { mandarin: '是否', pinyin: 'shìfǒu', vietnamese: 'hay không (phải chăng)' },
  { mandarin: '秒', pinyin: 'miǎo', vietnamese: 'giây' },
  { mandarin: '方式', pinyin: 'fāngshì', vietnamese: 'phương thức' },
  { mandarin: '受不了', pinyin: 'shòubuliǎo', vietnamese: 'chịu không nổi' },
  { mandarin: '日记', pinyin: 'rìjì', vietnamese: 'nhật ký' },
  { mandarin: '安全', pinyin: 'ānquán', vietnamese: 'an toàn' },
  { mandarin: '密码', pinyin: 'mìmǎ', vietnamese: 'mật mã' },
  { mandarin: '允许', pinyin: 'yǔnxǔ', vietnamese: 'cho phép' },
  { mandarin: '座', pinyin: 'zuò', vietnamese: 'tòa (lượng từ)' },
  { mandarin: '桥', pinyin: 'qiáo', vietnamese: 'cầu' },
  { mandarin: '危险', pinyin: 'wēixiǎn', vietnamese: 'nguy hiểm' },
  { mandarin: '接着', pinyin: 'jiēzhe', vietnamese: 'tiếp theo' },
  { mandarin: '警察', pinyin: 'jǐngchá', vietnamese: 'cảnh sát' },
  { mandarin: '抓', pinyin: 'zhuā', vietnamese: 'bắt' },
  { mandarin: '咸', pinyin: 'xián', vietnamese: 'mặn' },
  { mandarin: '矿泉水', pinyin: 'kuàngquánshuǐ', vietnamese: 'nước khoáng' },
  { mandarin: '付款', pinyin: 'fùkuǎn', vietnamese: 'thanh toán' },
  { mandarin: '举', pinyin: 'jǔ', vietnamese: 'giơ, cử' },
  { mandarin: '迷路', pinyin: 'mílù', vietnamese: 'lạc đường' },
  { mandarin: '地址', pinyin: 'dìzhǐ', vietnamese: 'địa chỉ' },
  { mandarin: '地点', pinyin: 'dìdiǎn', vietnamese: 'địa điểm' },
  { mandarin: '世纪', pinyin: 'shìjì', vietnamese: 'thế kỷ' },
  { mandarin: '邮局', pinyin: 'yóujú', vietnamese: 'bưu điện' },
  { mandarin: '收', pinyin: 'shōu', vietnamese: 'thu, nhận' },
  { mandarin: '信封', pinyin: 'xìnfēng', vietnamese: 'phong bì' },
  { mandarin: '网站', pinyin: 'wǎngzhàn', vietnamese: 'trang web' },
  { mandarin: '信息', pinyin: 'xìnxī', vietnamese: 'thông tin' },

  // Bài 19 (32 từ)
  { mandarin: '学期', pinyin: 'xuéqī', vietnamese: 'học kỳ' },
  { mandarin: '出生', pinyin: 'chūshēng', vietnamese: 'ra đời' },
  { mandarin: '性别', pinyin: 'xìngbié', vietnamese: 'giới tính' },
  { mandarin: '打印', pinyin: 'dǎyìn', vietnamese: 'in ấn' },
  { mandarin: '复印', pinyin: 'fùyìn', vietnamese: 'photocopy' },
  { mandarin: '饺子', pinyin: 'jiǎozi', vietnamese: 'sủi cảo' },
  { mandarin: '刀', pinyin: 'dāo', vietnamese: 'dao' },
  { mandarin: '破', pinyin: 'pò', vietnamese: 'rách, vỡ' },
  { mandarin: '脱', pinyin: 'tuō', vietnamese: 'cởi' },
  { mandarin: '理发', pinyin: 'lǐfà', vietnamese: 'cắt tóc' },
  { mandarin: '包子', pinyin: 'bāozi', vietnamese: 'bánh bao' },
  { mandarin: '零钱', pinyin: 'língqián', vietnamese: 'tiền lẻ' },
  { mandarin: '打招呼', pinyin: 'dǎzhāohu', vietnamese: 'chào hỏi' },
  { mandarin: '戴', pinyin: 'dài', vietnamese: 'đeo, đội' },
  { mandarin: '眼镜', pinyin: 'yǎnjìng', vietnamese: 'mắt kính' },
  { mandarin: '舞蹈', pinyin: 'wǔdǎo', vietnamese: 'điệu múa' },
  { mandarin: '国籍', pinyin: 'guójí', vietnamese: 'quốc tịch' },
  { mandarin: '抬', pinyin: 'tái', vietnamese: 'khiêng, ngẩng' },
  { mandarin: '胳膊', pinyin: 'gēbo', vietnamese: 'cánh tay' },
  { mandarin: '转', pinyin: 'zhuǎn', vietnamese: 'chuyển, quay' },
  { mandarin: '租', pinyin: 'zū', vietnamese: 'thuê' },
  { mandarin: '吵', pinyin: 'chǎo', vietnamese: 'ồn ào' },
  { mandarin: '厨房', pinyin: 'chúfáng', vietnamese: 'nhà bếp' },
  { mandarin: '房东', pinyin: 'fángdōng', vietnamese: 'chủ nhà' },
  { mandarin: '占线', pinyin: 'zhànxiàn', vietnamese: 'đường dây bận' },
  { mandarin: '功夫', pinyin: 'gōngfu', vietnamese: 'công phu' },
  { mandarin: '乒乓球', pinyin: 'pīngpāngqiú', vietnamese: 'bóng bàn' },
  { mandarin: '羽毛球', pinyin: 'yǔmáoqiú', vietnamese: 'cầu lông' },
  { mandarin: '场', pinyin: 'chǎng', vietnamese: 'sân, trận' },
  { mandarin: '禁止', pinyin: 'jìnzhǐ', vietnamese: 'cấm' },
  { mandarin: '座位', pinyin: 'zuòwèi', vietnamese: 'chỗ ngồi' },
  { mandarin: '道歉', pinyin: 'dàoqiàn', vietnamese: 'xin lỗi' },

  // Bài 20 (30 từ)
  { mandarin: '加油站', pinyin: 'jiāyóuzhàn', vietnamese: 'trạm xăng' },
  { mandarin: '航班', pinyin: 'hángbān', vietnamese: 'chuyến bay' },
  { mandarin: '推迟', pinyin: 'tuīchí', vietnamese: 'hoãn lại' },
  { mandarin: '高速公路', pinyin: 'gāosùgōnglù', vietnamese: 'đường cao tốc' },
  { mandarin: '登机牌', pinyin: 'dēngjīpái', vietnamese: 'thẻ lên máy bay' },
  { mandarin: '首都', pinyin: 'shǒudū', vietnamese: 'thủ đô' },
  { mandarin: '旅行', pinyin: 'lǚxíng', vietnamese: 'du lịch' },
  { mandarin: '怪', pinyin: 'guài', vietnamese: 'trách, lạ' },
  { mandarin: '可怜', pinyin: 'kělián', vietnamese: 'đáng thương' },
  { mandarin: '对面', pinyin: 'duìmiàn', vietnamese: 'đối diện' },
  { mandarin: '烤鸭', pinyin: 'kǎoyā', vietnamese: 'vịt quay' },
  { mandarin: '祝贺', pinyin: 'zhùhè', vietnamese: 'chúc mừng' },
  { mandarin: '合格', pinyin: 'hégé', vietnamese: 'hợp lệ' },
  { mandarin: '干杯', pinyin: 'gānbēi', vietnamese: 'cạn ly' },
  { mandarin: '民族', pinyin: 'mínzú', vietnamese: 'dân tộc' },
  { mandarin: '打扮', pinyin: 'dǎban', vietnamese: 'trang điểm' },
  { mandarin: '笑话', pinyin: 'xiàohua', vietnamese: 'truyện cười' },
  { mandarin: '存', pinyin: 'cún', vietnamese: 'gửi, tồn' },
  { mandarin: '钥匙', pinyin: 'yàoshi', vietnamese: 'chìa khóa' },
  { mandarin: '究竟', pinyin: 'jiūjìng', vietnamese: 'rốt cuộc' },
  { mandarin: '棵', pinyin: 'kē', vietnamese: 'cây (lượng từ)' },
  { mandarin: '汤', pinyin: 'tāng', vietnamese: 'canh' },
  { mandarin: '对话', pinyin: 'duìhuà', vietnamese: 'đối thoại' },
  { mandarin: '普通话', pinyin: 'pǔtōnghuà', vietnamese: 'tiếng phổ thông' },
  { mandarin: '小吃', pinyin: 'xiǎochī', vietnamese: 'đồ ăn vặt' },
  { mandarin: '收拾', pinyin: 'shōushi', vietnamese: 'thu dọn' },
  { mandarin: '辣', pinyin: 'là', vietnamese: 'cay' },
  { mandarin: '香', pinyin: 'xiāng', vietnamese: 'thơm' },
  { mandarin: '酸', pinyin: 'suān', vietnamese: 'chua' },
  { mandarin: '出发', pinyin: 'chūfā', vietnamese: 'xuất phát' },
];
