import { HSKWord } from './types';

export const HSK4_VOCABULARY: HSKWord[] = [
  { mandarin: '爱情', pinyin: 'ài qíng [ái tình]', vietnamese: 'tình yêu' },
{ mandarin: '安排', pinyin: 'ān pái [an bài]', vietnamese: 'sắp xếp' },
{ mandarin: '安全', pinyin: 'ān quán [an toàn]', vietnamese: 'an toàn' },
{ mandarin: '按时', pinyin: 'àn shí', vietnamese: 'đúng hạn' },
{ mandarin: '按照', pinyin: 'àn zhào', vietnamese: 'dựa vào, theo' },
{ mandarin: '百分之', pinyin: 'bǎi fēn zhī', vietnamese: '%' },
{ mandarin: '棒', pinyin: 'bàng', vietnamese: 'cây gậy/ giỏi, tốt' },
{ mandarin: '包子', pinyin: 'bāo zi', vietnamese: 'bánh bao' },
{ mandarin: '保护', pinyin: 'bǎo hù', vietnamese: 'che chở, bảo vệ' },
{ mandarin: '保证', pinyin: 'bǎo zhèng', vietnamese: 'đảm bảo, cam đoan' },
{ mandarin: '报名', pinyin: 'bào míng', vietnamese: 'đăng kí' },
{ mandarin: '抱', pinyin: 'bào', vietnamese: 'ôm' },
{ mandarin: '抱歉', pinyin: 'bào qiàn', vietnamese: 'xin lỗi' },
{ mandarin: '倍', pinyin: 'bèi', vietnamese: 'lần' },
{ mandarin: '本来', pinyin: 'běn lái', vietnamese: 'vốn có' },
{ mandarin: '笨', pinyin: 'bèn', vietnamese: 'ngốc nghếch' },
{ mandarin: '比如', pinyin: 'bǐ rú', vietnamese: 'ví dụ như' },
{ mandarin: '毕业', pinyin: 'bì yè', vietnamese: 'tốt nghiệp' },
{ mandarin: '遍', pinyin: 'biàn', vietnamese: 'lần, lượt' },
{ mandarin: '标准', pinyin: 'biāo zhǔn', vietnamese: 'tiêu chuẩn' },
{ mandarin: '表格', pinyin: 'biǎo gé', vietnamese: 'bảng biểu' },
{ mandarin: '表示', pinyin: 'biǎo shì', vietnamese: 'biểu thị, cho thấy' },
{ mandarin: '表演', pinyin: 'biǎo yǎn', vietnamese: 'biểu diễn' },
{ mandarin: '表扬', pinyin: 'biǎo yáng', vietnamese: 'tuyên dương' },
{ mandarin: '饼干', pinyin: 'bǐng gān', vietnamese: 'bánh' },
{ mandarin: '并且', pinyin: 'bìng qiě', vietnamese: 'đồng thời' },
{ mandarin: '博士', pinyin: 'bó shì', vietnamese: 'tiến sĩ' },
{ mandarin: '不得不', pinyin: 'bù dé bù', vietnamese: 'đành' },
{ mandarin: '不管', pinyin: 'bù guǎn', vietnamese: 'bất kể' },
{ mandarin: '不过', pinyin: 'bù guò', vietnamese: 'nhưng, có điều' },
{ mandarin: '不仅', pinyin: 'bù jǐn', vietnamese: 'không những' },
{ mandarin: '部分', pinyin: 'bù fèn', vietnamese: 'bộ phận, phần' },
{ mandarin: '擦', pinyin: 'cā', vietnamese: 'lau' },
{ mandarin: '猜', pinyin: 'cāi', vietnamese: 'đoán' },
{ mandarin: '材料', pinyin: 'cái liào', vietnamese: 'tài liệu' },
{ mandarin: '参观', pinyin: 'cān guān', vietnamese: 'tham quan' },
{ mandarin: '餐厅', pinyin: 'cān tīng', vietnamese: 'căng tin, nhà ăn' },
{ mandarin: '厕所', pinyin: 'cè suǒ', vietnamese: 'phòng vệ sinh' },
{ mandarin: '差不多', pinyin: 'chà bù duō', vietnamese: 'gần như' },
{ mandarin: '长城', pinyin: 'cháng chéng', vietnamese: 'Trường Thành' },
{ mandarin: '长江', pinyin: 'cháng jiāng', vietnamese: 'Trường Giang' },
{ mandarin: '尝', pinyin: 'cháng', vietnamese: 'nếm thử' },
{ mandarin: '场', pinyin: 'chǎng', vietnamese: 'trận, suất' },
{ mandarin: '超过', pinyin: 'chāo guò', vietnamese: 'vượt trên' },
{ mandarin: '成功', pinyin: 'chéng gōng', vietnamese: 'thành công' },
{ mandarin: '成为', pinyin: 'chéng wéi', vietnamese: 'trở thành' },
{ mandarin: '诚实', pinyin: 'chéng shí', vietnamese: 'trung thực' },
{ mandarin: '乘坐', pinyin: 'chéng zuò', vietnamese: 'ngồi xe' },
{ mandarin: '吃惊', pinyin: 'chī jīng', vietnamese: 'ngạc nhiên' },
{ mandarin: '重新', pinyin: 'chóng xīn', vietnamese: 'làm lại' },
{ mandarin: '抽烟', pinyin: 'chōu yān', vietnamese: 'hút thuốc' },
{ mandarin: '出差', pinyin: 'chū chāi', vietnamese: 'đi công tác' },
{ mandarin: '出发', pinyin: 'chū fā', vietnamese: 'xuất phát' },
{ mandarin: '出生', pinyin: 'chū shēng', vietnamese: 'ra đời' },
{ mandarin: '出现', pinyin: 'chū xiàn', vietnamese: 'xuất hiện' },
{ mandarin: '厨房', pinyin: 'chú fáng', vietnamese: 'phòng bếp' },
{ mandarin: '传真', pinyin: 'chuán zhēn', vietnamese: 'fax, bản fax' },
{ mandarin: '窗户', pinyin: 'chuāng hù', vietnamese: 'cửa sổ' },
{ mandarin: '词语', pinyin: 'cí yǔ', vietnamese: 'từ ngữ' },
{ mandarin: '从来', pinyin: 'cóng lái', vietnamese: 'từ trước đến nay' },
{ mandarin: '粗心', pinyin: 'cū xīn', vietnamese: 'thô lỗ, cẩu thả' },
{ mandarin: '存', pinyin: 'cún', vietnamese: 'giữ, tiết kiệm, tồn' },
{ mandarin: '错误', pinyin: 'cuò wù', vietnamese: 'sai lầm' },
{ mandarin: '答案', pinyin: 'dá àn', vietnamese: 'đáp án' },
{ mandarin: '打扮', pinyin: 'dǎ bàn', vietnamese: 'trau chuốt, trang điểm' },
{ mandarin: '打扰', pinyin: 'dǎ rǎo', vietnamese: 'làm phiền' },
{ mandarin: '打印', pinyin: 'dǎ yìn', vietnamese: 'in ấn' },
{ mandarin: '打招呼', pinyin: 'dǎ zhāo hū', vietnamese: 'chào hỏi' },
{ mandarin: '打折', pinyin: 'dǎ zhé', vietnamese: 'giảm giá' },
{ mandarin: '打针', pinyin: 'dǎ zhēn', vietnamese: 'tiêm' },
{ mandarin: '大概', pinyin: 'dà gài', vietnamese: 'khoảng' },
{ mandarin: '大使馆', pinyin: 'dà shǐ guǎn', vietnamese: 'đại sứ quán' },
{ mandarin: '大约', pinyin: 'dà yuē', vietnamese: 'khoảng' },
{ mandarin: '大夫', pinyin: 'dài fū', vietnamese: 'bác sĩ, đại phu' },
{ mandarin: '戴', pinyin: 'dài', vietnamese: 'đeo' },
{ mandarin: '当', pinyin: 'dāng', vietnamese: 'làm' },
{ mandarin: '当时', pinyin: 'dāng shí', vietnamese: 'lúc đó' },
{ mandarin: '刀', pinyin: 'dāo', vietnamese: 'cái dao' },
{ mandarin: '导游', pinyin: 'dǎo yóu', vietnamese: 'hướng dẫn viên du lịch' },
{ mandarin: '到处', pinyin: 'dào chù', vietnamese: 'khắp nơi' },
{ mandarin: '到底', pinyin: 'dào dǐ', vietnamese: 'cuối cùng' },
{ mandarin: '倒', pinyin: 'dǎo', vietnamese: 'đổ, ngã' },
{ mandarin: '道歉', pinyin: 'dào qiàn', vietnamese: 'xin lỗi' },
{ mandarin: '得意', pinyin: 'dé yì', vietnamese: 'đắc ý' },
{ mandarin: '得（助动词）', pinyin: 'de （ zhù dòng cí ）', vietnamese: 'trợ từ' },
{ mandarin: '登机牌', pinyin: 'dēng jī pái', vietnamese: 'thẻ lên tàu' },
{ mandarin: '等（助词）', pinyin: 'děng （ zhù cí ）', vietnamese: 'vân vân' },
{ mandarin: '低', pinyin: 'dī', vietnamese: 'thấp' },
{ mandarin: '底', pinyin: 'dǐ', vietnamese: 'đáy' },
{ mandarin: '地点', pinyin: 'dì diǎn', vietnamese: 'địa điểm' },
{ mandarin: '地球', pinyin: 'dì qiú', vietnamese: 'địa cầu' },
{ mandarin: '地址', pinyin: 'dì zhǐ', vietnamese: 'địa chỉ' },
{ mandarin: '调查', pinyin: 'diào chá', vietnamese: 'điều tra' },
{ mandarin: '掉', pinyin: 'diào', vietnamese: 'rơi' },
{ mandarin: '丢', pinyin: 'diū', vietnamese: 'mất' },
{ mandarin: '动作', pinyin: 'dòng zuò', vietnamese: 'động tác' },
{ mandarin: '堵车', pinyin: 'dǔ chē', vietnamese: 'tắc đường' },
{ mandarin: '肚子', pinyin: 'dù zi', vietnamese: 'bụng' },
{ mandarin: '短信', pinyin: 'duǎn xìn', vietnamese: 'tin nhắn' },
{ mandarin: '对话', pinyin: 'duì huà', vietnamese: 'hội thoại, đối thoại' },
{ mandarin: '对面', pinyin: 'duì miàn', vietnamese: 'đối diện' },
{ mandarin: '对于', pinyin: 'duì yú', vietnamese: 'về (vấn đề gì đó)' },
{ mandarin: '儿童', pinyin: 'ér tóng', vietnamese: 'trẻ con' },
{ mandarin: '而', pinyin: 'ér', vietnamese: 'còn' },
{ mandarin: '发生', pinyin: 'fā shēng', vietnamese: 'xảy ra' },
{ mandarin: '发展', pinyin: 'fā zhǎn', vietnamese: 'phát triển' },
{ mandarin: '法律', pinyin: 'fǎ lǜ', vietnamese: 'pháp luật' },
{ mandarin: '翻译', pinyin: 'fān yì', vietnamese: 'phiên dịch' },
{ mandarin: '烦恼', pinyin: 'fán nǎo', vietnamese: 'phiền não' },
{ mandarin: '反对', pinyin: 'fǎn duì', vietnamese: 'phản đối' },
{ mandarin: '方法', pinyin: 'fāng fǎ', vietnamese: 'phương pháp' },
{ mandarin: '方面', pinyin: 'fāng miàn', vietnamese: 'phương diện' },
{ mandarin: '方向', pinyin: 'fāng xiàng', vietnamese: 'phương hướng' },
{ mandarin: '房东', pinyin: 'fáng dōng', vietnamese: 'chủ nhà' },
{ mandarin: '放弃', pinyin: 'fàng qì', vietnamese: 'vứt bỏ, từ bỏ' },
{ mandarin: '放暑假', pinyin: 'fàng shǔ jià', vietnamese: 'nghỉ hè' },
{ mandarin: '放松', pinyin: 'fàng sōng', vietnamese: 'thư giãn' },
{ mandarin: '份', pinyin: 'fèn', vietnamese: 'phần' },
{ mandarin: '丰富', pinyin: 'fēng fù', vietnamese: 'phong phú' },
{ mandarin: '否则', pinyin: 'fǒu zé', vietnamese: 'nếu không thì' },
{ mandarin: '符合', pinyin: 'fú hé', vietnamese: 'phù hợp' },
{ mandarin: '父亲', pinyin: 'fù qīn', vietnamese: 'bố' },
{ mandarin: '付款', pinyin: 'fù kuǎn', vietnamese: 'thanh toán' },
{ mandarin: '负责', pinyin: 'fù zé', vietnamese: 'phụ trách' },
{ mandarin: '复印', pinyin: 'fù yìn', vietnamese: 'phô tô' },
{ mandarin: '复杂', pinyin: 'fù zá', vietnamese: 'phức tạp' },
{ mandarin: '富', pinyin: 'fù', vietnamese: 'giàu' },
{ mandarin: '改变', pinyin: 'gǎi biàn', vietnamese: 'thay đổi' },
{ mandarin: '干杯', pinyin: 'gān bēi', vietnamese: 'cạn ly' },
{ mandarin: '赶', pinyin: 'gǎn', vietnamese: 'đuổi theo' },
{ mandarin: '敢', pinyin: 'gǎn', vietnamese: 'dám' },
{ mandarin: '感动', pinyin: 'gǎn dòng', vietnamese: 'cảm động' },
{ mandarin: '感觉', pinyin: 'gǎn jué', vietnamese: 'cảm giác' },
{ mandarin: '感情', pinyin: 'gǎn qíng', vietnamese: 'tình cảm' },
{ mandarin: '感谢', pinyin: 'gǎn xiè', vietnamese: 'cảm ơn' },
{ mandarin: '干', pinyin: 'gān', vietnamese: 'khô' },
{ mandarin: '刚', pinyin: 'gāng', vietnamese: 'vừa mới' },
{ mandarin: '高速公路', pinyin: 'gāo sù gōng lù', vietnamese: 'đường cao tốc' },
{ mandarin: '胳膊', pinyin: 'gē bo', vietnamese: 'cánh tay' },
{ mandarin: '各', pinyin: 'gè', vietnamese: 'các' },
{ mandarin: '工资', pinyin: 'gōng zī', vietnamese: 'lương' },
{ mandarin: '公里', pinyin: 'gōng lǐ', vietnamese: 'km' },
{ mandarin: '功夫', pinyin: 'gōng fū', vietnamese: 'công phu' },
{ mandarin: '共同', pinyin: 'gòng tóng', vietnamese: 'giống nhau' },
{ mandarin: '购物', pinyin: 'gòu wù', vietnamese: 'mua sắm' },
{ mandarin: '够', pinyin: 'gòu', vietnamese: 'đủ' },
{ mandarin: '估计', pinyin: 'gū jì', vietnamese: 'ước lượng' },
{ mandarin: '鼓励', pinyin: 'gǔ lì', vietnamese: 'cổ vũ' },
{ mandarin: '故意', pinyin: 'gù yì', vietnamese: 'cố ý' },
{ mandarin: '顾客', pinyin: 'gù kè', vietnamese: 'khách hàng' },
{ mandarin: '挂', pinyin: 'guà', vietnamese: 'treo, ngắt điện thoại' },
{ mandarin: '关键', pinyin: 'guān jiàn', vietnamese: 'mấu chốt' },
{ mandarin: '观众', pinyin: 'guān zhòng', vietnamese: 'khán giả' },
{ mandarin: '管理', pinyin: 'guǎn lǐ', vietnamese: 'quản lý' },
{ mandarin: '光', pinyin: 'guāng', vietnamese: 'chỉ, hết' },
{ mandarin: '广播', pinyin: 'guǎng bō', vietnamese: 'phát thanh' },
{ mandarin: '广告', pinyin: 'guǎng gào', vietnamese: 'quảng cáo' },
{ mandarin: '逛', pinyin: 'guàng', vietnamese: 'đi dạo' },
{ mandarin: '规定', pinyin: 'guī dìng', vietnamese: 'qui định' },
{ mandarin: '国籍', pinyin: 'guó jí', vietnamese: 'quốc tịch' },
{ mandarin: '国际', pinyin: 'guó jì', vietnamese: 'quốc tế' },
{ mandarin: '果汁', pinyin: 'guǒ zhī', vietnamese: 'nước hoa quả' },
{ mandarin: '过程', pinyin: 'guò chéng', vietnamese: 'quá trình' },
{ mandarin: '海洋', pinyin: 'hǎi yáng', vietnamese: 'đại dương' },
{ mandarin: '害羞', pinyin: 'hài xiū', vietnamese: 'xấu hổ' },
{ mandarin: '寒假', pinyin: 'hán jià', vietnamese: 'kì nghỉ đông' },
{ mandarin: '汗', pinyin: 'hàn', vietnamese: 'mồ hôi' },
{ mandarin: '航班', pinyin: 'háng bān', vietnamese: 'chuyến bay' },
{ mandarin: '好处', pinyin: 'hǎo chù', vietnamese: 'cái tốt' },
{ mandarin: '好像', pinyin: 'hǎo xiàng', vietnamese: 'dường như' },
{ mandarin: '号码', pinyin: 'hào mǎ', vietnamese: 'số' },
{ mandarin: '合格', pinyin: 'hé gé', vietnamese: 'đạt yêu cầu' },
{ mandarin: '合适', pinyin: 'hé shì', vietnamese: 'thích hợp' },
{ mandarin: '盒子', pinyin: 'hé zi', vietnamese: 'cái hộp' },
{ mandarin: '后悔', pinyin: 'hòu huǐ', vietnamese: 'hối hận' },
{ mandarin: '厚', pinyin: 'hòu', vietnamese: 'dày' },
{ mandarin: '互联网', pinyin: 'hù lián wǎng', vietnamese: 'mạng internet' },
{ mandarin: '互相', pinyin: 'hù xiāng', vietnamese: 'lẫn nhau' },
{ mandarin: '护士', pinyin: 'hù shì', vietnamese: 'y tá' },
{ mandarin: '怀疑', pinyin: 'huái yí', vietnamese: 'nghi ngờ' },
{ mandarin: '回忆', pinyin: 'huí yì', vietnamese: 'hồi ức, nhớ lại' },
{ mandarin: '活动', pinyin: 'huó dòng', vietnamese: 'hoạt động' },
{ mandarin: '活泼', pinyin: 'huó pō', vietnamese: 'hoạt bát' },
{ mandarin: '火', pinyin: 'huǒ', vietnamese: 'lửa' },
{ mandarin: '获得', pinyin: 'huò dé', vietnamese: 'giành được' },
{ mandarin: '积极', pinyin: 'jī jí', vietnamese: 'tích cực' },
{ mandarin: '积累', pinyin: 'jī lěi', vietnamese: 'tích lũy' },
{ mandarin: '基础', pinyin: 'jī chǔ', vietnamese: 'cơ sở, căn bản' },
{ mandarin: '激动', pinyin: 'jī dòng', vietnamese: 'xúc động' },
{ mandarin: '及时', pinyin: 'jí shí', vietnamese: 'kịp thời' },
{ mandarin: '即使', pinyin: 'jí shǐ', vietnamese: 'cho dù' },
{ mandarin: '计划', pinyin: 'jì huà', vietnamese: 'kế hoạch' },
{ mandarin: '记者', pinyin: 'jì zhě', vietnamese: 'phóng viên' },
{ mandarin: '技术', pinyin: 'jì shù', vietnamese: 'kỹ thuật' },
{ mandarin: '既然', pinyin: 'jì rán', vietnamese: 'đã….' },
{ mandarin: '继续', pinyin: 'jì xù', vietnamese: 'tiếp tục' },
{ mandarin: '寄', pinyin: 'jì', vietnamese: 'gửi' },
{ mandarin: '加班', pinyin: 'jiā bān', vietnamese: 'tăng ca' },
{ mandarin: '加油站', pinyin: 'jiā yóu zhàn', vietnamese: 'cây xăng' },
{ mandarin: '家具', pinyin: 'jiā jù', vietnamese: 'đồ gia dụng' },
{ mandarin: '假', pinyin: 'jiǎ', vietnamese: 'giả' },
{ mandarin: '价格', pinyin: 'jià gé', vietnamese: 'giá cả' },
{ mandarin: '坚持', pinyin: 'jiān chí', vietnamese: 'kiên trì' },
{ mandarin: '减肥', pinyin: 'jiǎn féi', vietnamese: 'giảm béo' },
{ mandarin: '减少', pinyin: 'jiǎn shǎo', vietnamese: 'cắt giảm' },
{ mandarin: '建议', pinyin: 'jiàn yì', vietnamese: 'kiến nghị' },
{ mandarin: '将来', pinyin: 'jiāng lái', vietnamese: 'tương lai' },
{ mandarin: '奖金', pinyin: 'jiǎng jīn', vietnamese: 'học bổng' },
{ mandarin: '降低', pinyin: 'jiàng dī', vietnamese: 'hạ thấp' },
{ mandarin: '降落', pinyin: 'jiàng luò', vietnamese: 'hạ cánh' },
{ mandarin: '交', pinyin: 'jiāo', vietnamese: 'giao' },
{ mandarin: '交流', pinyin: 'jiāo liú', vietnamese: 'giao lưu' },
{ mandarin: '交通', pinyin: 'jiāo tōng', vietnamese: 'giao thông' },
{ mandarin: '郊区', pinyin: 'jiāo qū', vietnamese: 'ngoại ô' },
{ mandarin: '骄傲', pinyin: 'jiāo ào', vietnamese: 'tự hào, kiêu ngạo' },
{ mandarin: '饺子', pinyin: 'jiǎo zi', vietnamese: 'sủi cảo' },
{ mandarin: '教授', pinyin: 'jiào shòu', vietnamese: 'giáo sư' },
{ mandarin: '教育', pinyin: 'jiào yù', vietnamese: 'giáo dục' },
{ mandarin: '接受', pinyin: 'jiē shòu', vietnamese: 'tiếp nhận' },
{ mandarin: '接着', pinyin: 'jiē zhe', vietnamese: 'tiếp theo' },
{ mandarin: '节', pinyin: 'jié', vietnamese: 'tiết' },
{ mandarin: '节约', pinyin: 'jié yuē', vietnamese: 'tiết kiệm' },
{ mandarin: '结果', pinyin: 'jié guǒ', vietnamese: 'kết quả' },
{ mandarin: '解释', pinyin: 'jiě shì', vietnamese: 'giải thích' },
{ mandarin: '尽管', pinyin: 'jǐn guǎn', vietnamese: 'tuy rằng' },
{ mandarin: '紧张', pinyin: 'jǐn zhāng', vietnamese: 'căng thẳng' },
{ mandarin: '进行', pinyin: 'jìn xíng', vietnamese: 'tiến hành' },
{ mandarin: '禁止', pinyin: 'jìn zhǐ', vietnamese: 'cấm' },
{ mandarin: '京剧', pinyin: 'jīng jù', vietnamese: 'kinh kịch' },
{ mandarin: '经济', pinyin: 'jīng jì', vietnamese: 'kinh tế' },
{ mandarin: '经历', pinyin: 'jīng lì', vietnamese: 'trải qua, kinh qua' },
{ mandarin: '经验', pinyin: 'jīng yàn', vietnamese: 'kinh nghiệm' },
{ mandarin: '精彩', pinyin: 'jīng cǎi', vietnamese: 'hấp dẫn' },
{ mandarin: '景色', pinyin: 'jǐng sè', vietnamese: 'cảnh sắc' },
{ mandarin: '警察', pinyin: 'jǐng chá', vietnamese: 'cảnh sát' },
{ mandarin: '竞争', pinyin: 'jìng zhēng', vietnamese: 'cạnh tranh' },
{ mandarin: '竟然', pinyin: 'jìng rán', vietnamese: 'vậy mà lại' },
{ mandarin: '镜子', pinyin: 'jìng zi', vietnamese: 'kính, gương' },
{ mandarin: '究竟', pinyin: 'jiū jìng', vietnamese: 'rốt cuộc' },
{ mandarin: '举', pinyin: 'jǔ', vietnamese: 'giơ, nâng' },
{ mandarin: '举办', pinyin: 'jǔ bàn', vietnamese: 'tổ chức' },
{ mandarin: '举行', pinyin: 'jǔ xíng', vietnamese: 'tổ chức' },
{ mandarin: '拒绝', pinyin: 'jù jué', vietnamese: 'từ chối' },
{ mandarin: '距离', pinyin: 'jù lí', vietnamese: 'khoảng cách' },
{ mandarin: '聚会', pinyin: 'jù huì', vietnamese: 'tụ tập' },
{ mandarin: '开玩笑', pinyin: 'kāi wán xiào', vietnamese: 'đùa' },
{ mandarin: '开心', pinyin: 'kāi xīn', vietnamese: 'vui vẻ' },
{ mandarin: '看法', pinyin: 'kàn fǎ', vietnamese: 'quan điểm' },
{ mandarin: '考虑', pinyin: 'kǎo lǜ', vietnamese: 'suy nghĩ' },
{ mandarin: '烤鸭', pinyin: 'kǎo yā', vietnamese: 'vịt quay' },
{ mandarin: '科学', pinyin: 'kē xué', vietnamese: 'khoa học' },
{ mandarin: '棵', pinyin: 'kē', vietnamese: 'lượng từ cho cây' },
{ mandarin: '咳嗽', pinyin: 'ké sou', vietnamese: 'ho' },
{ mandarin: '可怜', pinyin: 'kě lián', vietnamese: 'đáng thương' },
{ mandarin: '可是', pinyin: 'kě shì', vietnamese: 'nhưng' },
{ mandarin: '可惜', pinyin: 'kě xī', vietnamese: 'đáng tiếc' },
{ mandarin: '客厅', pinyin: 'kè tīng', vietnamese: 'phòng khách' },
{ mandarin: '肯定', pinyin: 'kěn dìng', vietnamese: 'khẳng định' },
{ mandarin: '空', pinyin: 'kōng', vietnamese: 'trống rỗng' },
{ mandarin: '空气', pinyin: 'kōng qì', vietnamese: 'không khí' },
{ mandarin: '恐怕', pinyin: 'kǒng pà', vietnamese: 'e rằng' },
{ mandarin: '苦', pinyin: 'kǔ', vietnamese: 'khổ, đắng' },
{ mandarin: '矿泉水', pinyin: 'kuàng quán shuǐ', vietnamese: 'nước khoáng' },
{ mandarin: '困', pinyin: 'kùn', vietnamese: 'buồn ngủ' },
{ mandarin: '困难', pinyin: 'kùn nán', vietnamese: 'khó khăn' },
{ mandarin: '垃圾桶', pinyin: 'lā jī tǒng', vietnamese: 'thùng rác' },
{ mandarin: '拉', pinyin: 'lā', vietnamese: 'kéo' },
{ mandarin: '辣', pinyin: 'là', vietnamese: 'cay' },
{ mandarin: '来不及', pinyin: 'lái bù jí', vietnamese: 'không kịp' },
{ mandarin: '来得及', pinyin: 'lái de jí', vietnamese: 'kịp' },
{ mandarin: '来自', pinyin: 'lái zì', vietnamese: 'đến từ' },
{ mandarin: '懒', pinyin: 'lǎn', vietnamese: 'lười biếng' },
{ mandarin: '浪费', pinyin: 'làng fèi', vietnamese: 'lãng phí' },
{ mandarin: '浪漫', pinyin: 'làng màn', vietnamese: 'lãng mạn' },
{ mandarin: '老虎', pinyin: 'lǎo hǔ', vietnamese: 'hổ' },
{ mandarin: '冷静', pinyin: 'lěng jìng', vietnamese: 'bình tĩnh' },
{ mandarin: '礼拜天', pinyin: 'lǐ bài tiān', vietnamese: 'chủ nhật' },
{ mandarin: '礼貌', pinyin: 'lǐ mào', vietnamese: 'lễ phép, lịch sự' },
{ mandarin: '理发', pinyin: 'lǐ fà', vietnamese: 'cắt tóc' },
{ mandarin: '理解', pinyin: 'lǐ jiě', vietnamese: 'lý giải, hiểu' },
{ mandarin: '理想', pinyin: 'lǐ xiǎng', vietnamese: 'lý tưởng' },
{ mandarin: '力气', pinyin: 'lì qì', vietnamese: 'sức lực' },
{ mandarin: '厉害', pinyin: 'lì hài', vietnamese: 'lợi hại' },
{ mandarin: '例如', pinyin: 'lì rú', vietnamese: 'ví dụ' },
{ mandarin: '俩', pinyin: 'liǎ', vietnamese: 'hai người' },
{ mandarin: '连', pinyin: 'lián', vietnamese: 'liên kết, nối' },
{ mandarin: '联系', pinyin: 'lián xì', vietnamese: 'liên hệ' },
{ mandarin: '凉快', pinyin: 'liáng kuài', vietnamese: 'mát mẻ' },
{ mandarin: '零钱', pinyin: 'líng qián', vietnamese: 'tiền lẻ' },
{ mandarin: '另外', pinyin: 'lìng wài', vietnamese: 'ngoài ra, còn lại' },
{ mandarin: '留', pinyin: 'liú', vietnamese: 'lưu lại, ở lại' },
{ mandarin: '流利', pinyin: 'liú lì', vietnamese: 'lưu loát' },
{ mandarin: '流行', pinyin: 'liú xíng', vietnamese: 'thịnh hành' },
{ mandarin: '旅行', pinyin: 'lǚ xíng', vietnamese: 'du lịch' },
{ mandarin: '律师', pinyin: 'lǜ shī', vietnamese: 'luật sư' },
{ mandarin: '乱', pinyin: 'luàn', vietnamese: 'loạn' },
{ mandarin: '麻烦', pinyin: 'má fan', vietnamese: 'phiền phức, làm phiền' },
{ mandarin: '马虎', pinyin: 'mǎ hu', vietnamese: 'qua loa' },
{ mandarin: '满', pinyin: 'mǎn', vietnamese: 'đầy' },
{ mandarin: '毛', pinyin: 'máo', vietnamese: 'lông' },
{ mandarin: '毛巾', pinyin: 'máo jīn', vietnamese: 'khăn bông' },
{ mandarin: '美丽', pinyin: 'měi lì', vietnamese: 'đẹp' },
{ mandarin: '梦', pinyin: 'mèng', vietnamese: 'giấc mơ, mơ' },
{ mandarin: '迷路', pinyin: 'mí lù', vietnamese: 'lạc đường' },
{ mandarin: '密码', pinyin: 'mì mǎ', vietnamese: 'mật khẩu' },
{ mandarin: '免费', pinyin: 'miǎn fèi', vietnamese: 'miễn phí' },
{ mandarin: '秒', pinyin: 'miǎo', vietnamese: 'giây' },
{ mandarin: '民族', pinyin: 'mín zú', vietnamese: 'dân tộc' },
{ mandarin: '母亲', pinyin: 'mǔ qin', vietnamese: 'mẹ' },
{ mandarin: '目的', pinyin: 'mù dì', vietnamese: 'mục đích' },
{ mandarin: '耐心', pinyin: 'nài xīn', vietnamese: 'nhẫn nại' },
{ mandarin: '难道', pinyin: 'nán dào', vietnamese: 'lẽ nào' },
{ mandarin: '难受', pinyin: 'nán shòu', vietnamese: 'buồn' },
{ mandarin: '内', pinyin: 'nèi', vietnamese: 'bên trong' },
{ mandarin: '内容', pinyin: 'nèi róng', vietnamese: 'nội dung' },
{ mandarin: '能力', pinyin: 'néng lì', vietnamese: 'năng lực' },
{ mandarin: '年龄', pinyin: 'nián líng', vietnamese: 'tuổi tác' },
{ mandarin: '弄', pinyin: 'nòng', vietnamese: 'làm' },
{ mandarin: '暖和', pinyin: 'nuǎn huo', vietnamese: 'ấm áp' },
{ mandarin: '偶尔', pinyin: 'ǒu ěr', vietnamese: 'đôi khi' },
{ mandarin: '排队', pinyin: 'pái duì', vietnamese: 'xếp hàng' },
{ mandarin: '排列', pinyin: 'pái liè', vietnamese: 'sắp xếp, xếp' },
{ mandarin: '判断', pinyin: 'pàn duàn', vietnamese: 'phán đoán' },
{ mandarin: '陪', pinyin: 'péi', vietnamese: 'cùng' },
{ mandarin: '批评', pinyin: 'pī píng', vietnamese: 'phê bình' },
{ mandarin: '皮肤', pinyin: 'pí fū', vietnamese: 'da' },
{ mandarin: '脾气', pinyin: 'pí qì', vietnamese: 'tính khí' },
{ mandarin: '篇', pinyin: 'piān', vietnamese: 'lượng từ cho bài viết' },
{ mandarin: '骗', pinyin: 'piàn', vietnamese: 'lừa' },
{ mandarin: '乒乓球', pinyin: 'pīng pāng qiú', vietnamese: 'bóng bàn' },
{ mandarin: '平时', pinyin: 'píng shí', vietnamese: 'bình thường' },
{ mandarin: '破', pinyin: 'pò', vietnamese: 'rách, nổ' },
{ mandarin: '葡萄', pinyin: 'pú táo', vietnamese: 'nho' },
{ mandarin: '普遍', pinyin: 'pǔ biàn', vietnamese: 'phổ biến' },
{ mandarin: '普通话', pinyin: 'pǔ tōng huà', vietnamese: 'tiếng phổ thông' },
{ mandarin: '其次', pinyin: 'qí cì', vietnamese: 'tiếp theo' },
{ mandarin: '其中', pinyin: 'qí zhōng', vietnamese: 'trong đó' },
{ mandarin: '气候', pinyin: 'qì hòu', vietnamese: 'khí hậu' },
{ mandarin: '千万', pinyin: 'qiān wàn', vietnamese: 'nhất thiết' },
{ mandarin: '签证', pinyin: 'qiān zhèng', vietnamese: 'visa' },
{ mandarin: '敲', pinyin: 'qiāo', vietnamese: 'gõ' },
{ mandarin: '桥', pinyin: 'qiáo', vietnamese: 'cầu' },
{ mandarin: '巧克力', pinyin: 'qiǎo kè lì', vietnamese: 'sô cô la' },
{ mandarin: '亲戚', pinyin: 'qīn qi', vietnamese: 'họ hàng' },
{ mandarin: '轻', pinyin: 'qīng', vietnamese: 'nhẹ' },
{ mandarin: '轻松', pinyin: 'qīng sōng', vietnamese: 'thoải mái' },
{ mandarin: '情况', pinyin: 'qíng kuàng', vietnamese: 'tình hình' },
{ mandarin: '穷', pinyin: 'qióng', vietnamese: 'nghèo' },
{ mandarin: '区别', pinyin: 'qū bié', vietnamese: 'khác biệt' },
{ mandarin: '取', pinyin: 'qǔ', vietnamese: 'lấy' },
{ mandarin: '全部', pinyin: 'quán bù', vietnamese: 'toàn bộ' },
{ mandarin: '缺点', pinyin: 'quē diǎn', vietnamese: 'khuyết điểm' },
{ mandarin: '缺少', pinyin: 'quē shǎo', vietnamese: 'thiếu' },
{ mandarin: '却', pinyin: 'què', vietnamese: 'lại, nhưng' },
{ mandarin: '确实', pinyin: 'què shí', vietnamese: 'thật sự' },
{ mandarin: '然而', pinyin: 'rán ér', vietnamese: 'vậy mà' },
{ mandarin: '热闹', pinyin: 'rè nào', vietnamese: 'náo nhiệt' },
{ mandarin: '任何', pinyin: 'rèn hé', vietnamese: 'bất kì' },
{ mandarin: '任务', pinyin: 'rèn wù', vietnamese: 'nhiệm vụ' },
{ mandarin: '扔', pinyin: 'rēng', vietnamese: 'ném' },
{ mandarin: '仍然', pinyin: 'réng rán', vietnamese: 'vẫn' },
{ mandarin: '日记', pinyin: 'rì jì', vietnamese: 'nhật kí' },
{ mandarin: '入口', pinyin: 'rù kǒu', vietnamese: 'cửa vào' },
{ mandarin: '散步', pinyin: 'sàn bù', vietnamese: 'tản bộ' },
{ mandarin: '森林', pinyin: 'sēn lín', vietnamese: 'rừng sâu' },
{ mandarin: '沙发', pinyin: 'shā fā', vietnamese: 'ghế sô pha' },
{ mandarin: '伤心', pinyin: 'shāng xīn', vietnamese: 'tổn thương' },
{ mandarin: '商量', pinyin: 'shāng liáng', vietnamese: 'thương lượng, bàn bạc' },
{ mandarin: '稍微', pinyin: 'shāo wēi', vietnamese: 'một chút' },
{ mandarin: '勺子', pinyin: 'sháo zi', vietnamese: 'cái thìa' },
{ mandarin: '社会', pinyin: 'shè huì', vietnamese: 'xã hội' },
{ mandarin: '申请', pinyin: 'shēn qǐng', vietnamese: 'xin' },
{ mandarin: '深', pinyin: 'shēn', vietnamese: 'sâu' },
{ mandarin: '甚至', pinyin: 'shèn zhì', vietnamese: 'thậm chí' },
{ mandarin: '生活', pinyin: 'shēng huó', vietnamese: 'cuộc sống' },
{ mandarin: '生命', pinyin: 'shēng mìng', vietnamese: 'tính mạng' },
{ mandarin: '生意', pinyin: 'shēng yì', vietnamese: 'kinh doanh' },
{ mandarin: '省', pinyin: 'shěng', vietnamese: 'tỉnh thành' },
{ mandarin: '剩', pinyin: 'shèng', vietnamese: 'thừa' },
{ mandarin: '失败', pinyin: 'shī bài', vietnamese: 'thất bại' },
{ mandarin: '失望', pinyin: 'shī wàng', vietnamese: 'thất vọng' },
{ mandarin: '师傅', pinyin: 'shī fù', vietnamese: 'sư phụ' },
{ mandarin: '十分', pinyin: 'shí fēn', vietnamese: 'vô cùng' },
{ mandarin: '实际', pinyin: 'shí jì', vietnamese: 'thực tế' },
{ mandarin: '实在', pinyin: 'shí zài', vietnamese: 'thật sự' },
{ mandarin: '使', pinyin: 'shǐ', vietnamese: 'khiến cho' },
{ mandarin: '使用', pinyin: 'shǐ yòng', vietnamese: 'sử dụng' },
{ mandarin: '世纪', pinyin: 'shì jì', vietnamese: 'thế kỉ' },
{ mandarin: '是否', pinyin: 'shì fǒu', vietnamese: 'liệu có phải' },
{ mandarin: '适合', pinyin: 'shì hé', vietnamese: 'thích hợp' },
{ mandarin: '适应', pinyin: 'shì yìng', vietnamese: 'thích nghi' },
{ mandarin: '收', pinyin: 'shōu', vietnamese: 'nhận' },
{ mandarin: '收入', pinyin: 'shōu rù', vietnamese: 'thu nhập' },
{ mandarin: '收拾', pinyin: 'shōu shí', vietnamese: 'dọn dẹp' },
{ mandarin: '首都', pinyin: 'shǒu dū', vietnamese: 'thủ đô' },
{ mandarin: '首先', pinyin: 'shǒu xiān', vietnamese: 'đầu tiên' },
{ mandarin: '受不了', pinyin: 'shòu bù liǎo', vietnamese: 'không chịu nổi' },
{ mandarin: '受到', pinyin: 'shòu dào', vietnamese: 'nhận được' },
{ mandarin: '售货员', pinyin: 'shòu huò yuán', vietnamese: 'nhân viên bán vé' },
{ mandarin: '输', pinyin: 'shū', vietnamese: 'thua' },
{ mandarin: '熟悉', pinyin: 'shú xī', vietnamese: 'quen thuộc' },
{ mandarin: '数量', pinyin: 'shù liàng', vietnamese: 'số lượng' },
{ mandarin: '数字', pinyin: 'shù zi', vietnamese: 'con cố' },
{ mandarin: '帅', pinyin: 'shuài', vietnamese: 'đẹp trai' },
{ mandarin: '顺便', pinyin: 'shùn biàn', vietnamese: 'nhân tiện' },
{ mandarin: '顺利', pinyin: 'shùn lì', vietnamese: 'thuận lợi' },
{ mandarin: '顺序', pinyin: 'shùn xù', vietnamese: 'thứ tự' },
{ mandarin: '说明', pinyin: 'shuō míng', vietnamese: 'nói rõ' },
{ mandarin: '硕士', pinyin: 'shuò shì', vietnamese: 'thạc sĩ' },
{ mandarin: '死', pinyin: 'sǐ', vietnamese: 'chết' },
{ mandarin: '速度', pinyin: 'sù dù', vietnamese: 'tốc độ' },
{ mandarin: '塑料袋', pinyin: 'sù liào dài', vietnamese: 'túi ni lông' },
{ mandarin: '酸', pinyin: 'suān', vietnamese: 'chua' },
{ mandarin: '随便', pinyin: 'suí biàn', vietnamese: 'tùy tiện, tự nhiên' },
{ mandarin: '随着', pinyin: 'suí zhe', vietnamese: 'cùng với' },
{ mandarin: '孙子', pinyin: 'sūn zi', vietnamese: 'cháu trai' },
{ mandarin: '所有', pinyin: 'suǒ yǒu', vietnamese: 'tất cả' },
{ mandarin: '台', pinyin: 'tái', vietnamese: 'cái, chiếc' },
{ mandarin: '抬', pinyin: 'tái', vietnamese: 'ngẩng' },
{ mandarin: '态度', pinyin: 'tài dù', vietnamese: 'thái độ' },
{ mandarin: '谈', pinyin: 'tán', vietnamese: 'nói chuyện' },
{ mandarin: '弹钢琴', pinyin: 'tán gāng qín', vietnamese: 'chơi piano' },
{ mandarin: '汤', pinyin: 'tāng', vietnamese: 'canh' },
{ mandarin: '糖', pinyin: 'táng', vietnamese: 'đường' },
{ mandarin: '躺', pinyin: 'tǎng', vietnamese: 'nằm' },
{ mandarin: '趟', pinyin: 'tàng', vietnamese: 'chuyến' },
{ mandarin: '讨论', pinyin: 'tǎo lùn', vietnamese: 'thảo luận' },
{ mandarin: '讨厌', pinyin: 'tǎo yàn', vietnamese: 'ghét' },
{ mandarin: '特点', pinyin: 'tè diǎn', vietnamese: 'đặc điểm' },
{ mandarin: '提', pinyin: 'tí', vietnamese: 'đề ra' },
{ mandarin: '提供', pinyin: 'tí gōng', vietnamese: 'cung cấp' },
{ mandarin: '提前', pinyin: 'tí qián', vietnamese: 'trước thời hạn' },
{ mandarin: '提醒', pinyin: 'tí xǐng', vietnamese: 'nhắc nhở' },
{ mandarin: '填空', pinyin: 'tián kòng', vietnamese: 'điền trống' },
{ mandarin: '条件', pinyin: 'tiáo jiàn', vietnamese: 'điều kiện' },
{ mandarin: '停', pinyin: 'tíng', vietnamese: 'dừng' },
{ mandarin: '挺', pinyin: 'tǐng', vietnamese: 'rất' },
{ mandarin: '通过', pinyin: 'tōng guò', vietnamese: 'thông qua' },
{ mandarin: '通知', pinyin: 'tōng zhī', vietnamese: 'thông báo' },
{ mandarin: '同情', pinyin: 'tóng qíng', vietnamese: 'đồng tình' },
{ mandarin: '同时', pinyin: 'tóng shí', vietnamese: 'đồng thời' },
{ mandarin: '推', pinyin: 'tuī', vietnamese: 'đẩy' },
{ mandarin: '推迟', pinyin: 'tuī chí', vietnamese: 'kéo dài thời gian' },
{ mandarin: '脱', pinyin: 'tuō', vietnamese: 'cởi' },
{ mandarin: '袜子', pinyin: 'wà zi', vietnamese: 'tất chân' },
{ mandarin: '完全', pinyin: 'wán quán', vietnamese: 'hoàn toàn' },
{ mandarin: '网球', pinyin: 'wǎng qiú', vietnamese: 'tennis' },
{ mandarin: '网站', pinyin: 'wǎng zhàn', vietnamese: 'trang mạng' },
{ mandarin: '往往', pinyin: 'wǎng wǎng', vietnamese: 'thường (quá khứ)' },
{ mandarin: '危险', pinyin: 'wēi xiǎn', vietnamese: 'nguy hiểm' },
{ mandarin: '卫生间', pinyin: 'wèi shēng jiān', vietnamese: 'phòng vệ sinh' },
{ mandarin: '味道', pinyin: 'wèi dào', vietnamese: 'mùi vị' },
{ mandarin: '温度', pinyin: 'wēn dù', vietnamese: 'nhiệt độ' },
{ mandarin: '文章', pinyin: 'wén zhāng', vietnamese: 'bài văn' },
{ mandarin: '污染', pinyin: 'wū rǎn', vietnamese: 'ô nhiễm' },
{ mandarin: '无', pinyin: 'wú', vietnamese: 'không' },
{ mandarin: '无聊', pinyin: 'wú liáo', vietnamese: 'nhàm chán' },
{ mandarin: '无论', pinyin: 'wú lùn', vietnamese: 'bất luận' },
{ mandarin: '误会', pinyin: 'wù huì', vietnamese: 'hiểu lầm' },
{ mandarin: '西红柿', pinyin: 'xī hóng shì', vietnamese: 'cà chua' },
{ mandarin: '吸引', pinyin: 'xī yǐn', vietnamese: 'thu hút' },
{ mandarin: '咸', pinyin: 'xián', vietnamese: 'mặn' },
{ mandarin: '现金', pinyin: 'xiàn jīn', vietnamese: 'tiền mặt' },
{ mandarin: '羡慕', pinyin: 'xiàn mù', vietnamese: 'ngưỡng mộ' },
{ mandarin: '相反', pinyin: 'xiāng fǎn', vietnamese: 'ngược lại' },
{ mandarin: '相同', pinyin: 'xiāng tóng', vietnamese: 'giống nhau' },
{ mandarin: '香', pinyin: 'xiāng', vietnamese: 'thơm' },
{ mandarin: '详细', pinyin: 'xiáng xì', vietnamese: 'tỉ mỉ' },
{ mandarin: '响', pinyin: 'xiǎng', vietnamese: 'kêu' },
{ mandarin: '橡皮', pinyin: 'xiàng pí', vietnamese: 'cục tẩy' },
{ mandarin: '消息', pinyin: 'xiāo xi', vietnamese: 'thông tin, tin' },
{ mandarin: '小吃', pinyin: 'xiǎo chī', vietnamese: 'đồ ăn vặt' },
{ mandarin: '小伙子', pinyin: 'xiǎo huǒ zi', vietnamese: 'anh chàng' },
{ mandarin: '小说', pinyin: 'xiǎo shuō', vietnamese: 'tiểu thuyết' },
{ mandarin: '笑话', pinyin: 'xiào huà', vietnamese: 'truyện cười' },
{ mandarin: '效果', pinyin: 'xiào guǒ', vietnamese: 'hiệu quả' },
{ mandarin: '心情', pinyin: 'xīn qíng', vietnamese: 'tâm trạng' },
{ mandarin: '辛苦', pinyin: 'xīn kǔ', vietnamese: 'vất vả' },
{ mandarin: '信封', pinyin: 'xìn fēng', vietnamese: 'bức thư' },
{ mandarin: '信息', pinyin: 'xìn xī', vietnamese: 'thông tin' },
{ mandarin: '信心', pinyin: 'xìn xīn', vietnamese: 'niềm tin' },
{ mandarin: '兴奋', pinyin: 'xīng fèn', vietnamese: 'hưng phấn, hứng khởi' },
{ mandarin: '行', pinyin: 'xíng', vietnamese: 'được' },
{ mandarin: '醒', pinyin: 'xǐng', vietnamese: 'tỉnh' },
{ mandarin: '幸福', pinyin: 'xìng fú', vietnamese: 'hạnh phúc' },
{ mandarin: '性别', pinyin: 'xìng bié', vietnamese: 'giới tính' },
{ mandarin: '性格', pinyin: 'xìng gé', vietnamese: 'tính cách' },
{ mandarin: '修理', pinyin: 'xiū lǐ', vietnamese: 'sửa chữa' },
{ mandarin: '许多', pinyin: 'xǔ duō', vietnamese: 'rất nhiều' },
{ mandarin: '学期', pinyin: 'xué qī', vietnamese: 'học kì' },
{ mandarin: '压力', pinyin: 'yā lì', vietnamese: 'áp lực' },
{ mandarin: '呀', pinyin: 'yā', vietnamese: 'a' },
{ mandarin: '牙膏', pinyin: 'yá gāo', vietnamese: 'kem đánh răng' },
{ mandarin: '亚洲', pinyin: 'yà zhōu', vietnamese: 'châu Á' },
{ mandarin: '严格', pinyin: 'yán gé', vietnamese: 'nghiêm khắc' },
{ mandarin: '严重', pinyin: 'yán zhòng', vietnamese: 'nghiêm trọng' },
{ mandarin: '研究', pinyin: 'yán jiū', vietnamese: 'nghiên cứu' },
{ mandarin: '盐', pinyin: 'yán', vietnamese: 'muối' },
{ mandarin: '眼镜', pinyin: 'yǎn jìng', vietnamese: 'kính mắt' },
{ mandarin: '演出', pinyin: 'yǎn chū', vietnamese: 'buổi diễn' },
{ mandarin: '演员', pinyin: 'yǎn yuán', vietnamese: 'diễn viên' },
{ mandarin: '阳光', pinyin: 'yáng guāng', vietnamese: 'ánh nắng' },
{ mandarin: '养成', pinyin: 'yǎng chéng', vietnamese: 'nuôi dưỡng, hình thành' },
{ mandarin: '样子', pinyin: 'yàng zi', vietnamese: 'kiểu dáng, dáng vẻ' },
{ mandarin: '邀请', pinyin: 'yāo qǐng', vietnamese: 'mời' },
{ mandarin: '要是', pinyin: 'yào shì', vietnamese: 'nếu' },
{ mandarin: '钥匙', pinyin: 'yào shi', vietnamese: 'chìa khóa' },
{ mandarin: '也许', pinyin: 'yě xǔ', vietnamese: 'có lẽ' },
{ mandarin: '叶子', pinyin: 'yè zi', vietnamese: 'chiếc lá' },
{ mandarin: '页', pinyin: 'yè', vietnamese: 'trang mạng' },
{ mandarin: '一切', pinyin: 'yī qiè', vietnamese: 'tất cả' },
{ mandarin: '以', pinyin: 'yǐ', vietnamese: 'lấy, với' },
{ mandarin: '以为', pinyin: 'yǐ wéi', vietnamese: 'tưởng rằng' },
{ mandarin: '艺术', pinyin: 'yì shù', vietnamese: 'nghệ thuật' },
{ mandarin: '意见', pinyin: 'yì jiàn', vietnamese: 'ý kiến' },
{ mandarin: '因此', pinyin: 'yīn cǐ', vietnamese: 'cho nên' },
{ mandarin: '引起', pinyin: 'yǐn qǐ', vietnamese: 'dẫn đến, gây ra' },
{ mandarin: '印象', pinyin: 'yìn xiàng', vietnamese: 'ấn tượng' },
{ mandarin: '赢', pinyin: 'yíng', vietnamese: 'thắng' },
{ mandarin: '应聘', pinyin: 'yìng pìn', vietnamese: 'ứng tuyển' },
{ mandarin: '永远', pinyin: 'yǒng yuǎn', vietnamese: 'mãi mãi' },
{ mandarin: '勇敢', pinyin: 'yǒng gǎn', vietnamese: 'dũng cảm' },
{ mandarin: '优点', pinyin: 'yōu diǎn', vietnamese: 'ưu điểm' },
{ mandarin: '优秀', pinyin: 'yōu xiù', vietnamese: 'ưu tú' },
{ mandarin: '幽默', pinyin: 'yōu mò', vietnamese: 'hài hước' },
{ mandarin: '尤其', pinyin: 'yóu qí', vietnamese: 'đặc biệt là' },
{ mandarin: '由', pinyin: 'yóu', vietnamese: 'do' },
{ mandarin: '由于', pinyin: 'yóu yú', vietnamese: 'do' },
{ mandarin: '邮局', pinyin: 'yóu jú', vietnamese: 'bưu điện' },
{ mandarin: '友好', pinyin: 'yǒu hǎo', vietnamese: 'hữu hảo' },
{ mandarin: '友谊', pinyin: 'yǒu yì', vietnamese: 'hữu nghị' },
{ mandarin: '有趣', pinyin: 'yǒu qù', vietnamese: 'hứng thú' },
{ mandarin: '于是', pinyin: 'yú shì', vietnamese: 'thế là' },
{ mandarin: '愉快', pinyin: 'yú kuài', vietnamese: 'vui vẻ' },
{ mandarin: '与', pinyin: 'yǔ', vietnamese: 'và' },
{ mandarin: '羽毛球', pinyin: 'yǔ máo qiú', vietnamese: 'cầu lông' },
{ mandarin: '语法', pinyin: 'yǔ fǎ', vietnamese: 'ngữ pháp' },
{ mandarin: '语言', pinyin: 'yǔ yán', vietnamese: 'ngôn ngữ' },
{ mandarin: '预习', pinyin: 'yù xí', vietnamese: 'chuẩn bị trước' },
{ mandarin: '原来', pinyin: 'yuán lái', vietnamese: 'hóa ra, vốn, cũ' },
{ mandarin: '原谅', pinyin: 'yuán liàng', vietnamese: 'tha thứ' },
{ mandarin: '原因', pinyin: 'yuán yīn', vietnamese: 'nguyên nhân' },
{ mandarin: '约会', pinyin: 'yuē huì', vietnamese: 'hẹn, cuộc hẹn' },
{ mandarin: '阅读', pinyin: 'yuè dú', vietnamese: 'đọc hiểu' },
{ mandarin: '云', pinyin: 'yún', vietnamese: 'mây' },
{ mandarin: '允许', pinyin: 'yǔn xǔ', vietnamese: 'cho phép' },
{ mandarin: '杂志', pinyin: 'zá zhì', vietnamese: 'tạp chí' },
{ mandarin: '咱们', pinyin: 'zán men', vietnamese: 'chúng ta' },
{ mandarin: '暂时', pinyin: 'zàn shí', vietnamese: 'tạm thời' },
{ mandarin: '脏', pinyin: 'zāng', vietnamese: 'bẩn' },
{ mandarin: '责任', pinyin: 'zé rèn', vietnamese: 'trách nhiệm' },
{ mandarin: '增加', pinyin: 'zēng jiā', vietnamese: 'tăng thêm' },
{ mandarin: '占线', pinyin: 'zhàn xiàn', vietnamese: 'máy bận' },
{ mandarin: '招聘', pinyin: 'zhāo pìn', vietnamese: 'tuyển dụng' },
{ mandarin: '照', pinyin: 'zhào', vietnamese: 'chiếu, chụp' },
{ mandarin: '真正', pinyin: 'zhēn zhèng', vietnamese: 'thật' },
{ mandarin: '整理', pinyin: 'zhěng lǐ', vietnamese: 'chỉnh sửa' },
{ mandarin: '正常', pinyin: 'zhèng cháng', vietnamese: 'bình thường' },
{ mandarin: '正好', pinyin: 'zhèng hǎo', vietnamese: 'vừa hay' },
{ mandarin: '正确', pinyin: 'zhèng què', vietnamese: 'chính xác' },
{ mandarin: '正式', pinyin: 'zhèng shì', vietnamese: 'chính thức' },
{ mandarin: '证明', pinyin: 'zhèng míng', vietnamese: 'chứng minh' },
{ mandarin: '之', pinyin: 'zhī', vietnamese: 'của' },
{ mandarin: '支持', pinyin: 'zhī chí', vietnamese: 'ủng hộ' },
{ mandarin: '知识', pinyin: 'zhī shí', vietnamese: 'tri thức, kiến thức' },
{ mandarin: '直接', pinyin: 'zhí jiē', vietnamese: 'trực tiếp' },
{ mandarin: '值得', pinyin: 'zhí dé', vietnamese: 'đáng' },
{ mandarin: '职业', pinyin: 'zhí yè', vietnamese: 'nghề nghiệp' },
{ mandarin: '植物', pinyin: 'zhí wù', vietnamese: 'thực vật' },
{ mandarin: '只好', pinyin: 'zhǐ hǎo', vietnamese: 'đành' },
{ mandarin: '只要', pinyin: 'zhǐ yào', vietnamese: 'chỉ cần' },
{ mandarin: '指', pinyin: 'zhǐ', vietnamese: 'chỉ' },
{ mandarin: '至少', pinyin: 'zhì shǎo', vietnamese: 'chí ít' },
{ mandarin: '质量', pinyin: 'zhì liàng', vietnamese: 'chất lượng' },
{ mandarin: '重', pinyin: 'zhòng', vietnamese: 'nặng' },
{ mandarin: '重点', pinyin: 'zhòng diǎn', vietnamese: 'trọng điểm' },
{ mandarin: '重视', pinyin: 'zhòng shì', vietnamese: 'coi trọng' },
{ mandarin: '周围', pinyin: 'zhōu wéi', vietnamese: 'xung quanh' },
{ mandarin: '主意', pinyin: 'zhǔ yì', vietnamese: 'chủ ý' },
{ mandarin: '祝贺', pinyin: 'zhù hè', vietnamese: 'chúc mừng' },
{ mandarin: '著名', pinyin: 'zhù míng', vietnamese: 'nổi tiếng' },
{ mandarin: '专门', pinyin: 'zhuān mén', vietnamese: 'chuyên môn' },
{ mandarin: '专业', pinyin: 'zhuān yè', vietnamese: 'chuyên ngành' },
{ mandarin: '转', pinyin: 'zhuǎn', vietnamese: 'chuyển' },
{ mandarin: '赚', pinyin: 'zhuàn', vietnamese: 'kiếm' },
{ mandarin: '准确', pinyin: 'zhǔn què', vietnamese: 'chính xác' },
{ mandarin: '准时', pinyin: 'zhǔn shí', vietnamese: 'đúng giờ' },
{ mandarin: '仔细', pinyin: 'zǐ xì', vietnamese: 'cẩn thận' },
{ mandarin: '自然', pinyin: 'zì rán', vietnamese: 'tự nhiên' },
{ mandarin: '自信', pinyin: 'zì xìn', vietnamese: 'tự tin' },
{ mandarin: '总结', pinyin: 'zǒng jié', vietnamese: 'tổng kết' },
{ mandarin: '租', pinyin: 'zū', vietnamese: 'thuê' },
{ mandarin: '最好', pinyin: 'zuì hǎo', vietnamese: 'tốt nhất' },
{ mandarin: '尊重', pinyin: 'zūn zhòng', vietnamese: 'tôn trọng' },
{ mandarin: '左右', pinyin: 'zuǒ yòu', vietnamese: 'khoảng' },
{ mandarin: '作家', pinyin: 'zuò jiā', vietnamese: 'tác gia' },
{ mandarin: '作用', pinyin: 'zuò yòng', vietnamese: 'tác dụng' },
{ mandarin: '作者', pinyin: 'zuò zhě', vietnamese: 'tác giả' },
{ mandarin: '座', pinyin: 'zuò', vietnamese: 'tòa' },
{ mandarin: '座位', pinyin: 'zuò wèi', vietnamese: 'chỗ ngồi' },
];