

import { HSKWord } from './types';

export const TIENG_TRUNG_3_VOCABULARY: HSKWord[] = [
  { mandarin: '门', pinyin: 'mén', vietnamese: 'cửa' },
  { mandarin: '外', pinyin: 'wài', vietnamese: 'bên ngoài' },
  { mandarin: '怎么', pinyin: 'zěnme', vietnamese: 'thế nào, làm sao' },
  { mandarin: '姐姐', pinyin: 'jiějie', vietnamese: 'chị gái' },
  { mandarin: '好吃', pinyin: 'hǎochī', vietnamese: 'ngon (đồ ăn)' },
  { mandarin: '自行车', pinyin: 'zìxíngchē', vietnamese: 'xe đạp' },
  { mandarin: '蓝色', pinyin: 'lánsè', vietnamese: 'màu xanh dương' },
  { mandarin: '羊肉', pinyin: 'yángròu', vietnamese: 'thịt dê' },
  { mandarin: '一般', pinyin: 'yìbān', vietnamese: 'bình thường, thông thường' },
  { mandarin: '面条', pinyin: 'miàntiáo', vietnamese: 'mì sợi' },
  { mandarin: '打篮球', pinyin: 'dǎ lánqiú', vietnamese: 'chơi bóng rổ' },
  { mandarin: '因为...所以', pinyin: 'yīnwèi... suǒyǐ', vietnamese: 'bởi vì... cho nên' },
  { mandarin: '游泳', pinyin: 'yóuyǒng', vietnamese: 'bơi lội' },
  { mandarin: '经常', pinyin: 'jīngcháng', vietnamese: 'thường xuyên' },

  { mandarin: '小时', pinyin: 'xiǎoshí', vietnamese: 'giờ' },
  { mandarin: '公共汽车', pinyin: 'gōnggòng qìchē', vietnamese: 'xe buýt' },
  { mandarin: '过', pinyin: 'guò', vietnamese: 'qua, đi qua; trải qua' },
  { mandarin: '机场', pinyin: 'jīchǎng', vietnamese: 'sân bay' },
  { mandarin: '路', pinyin: 'lù', vietnamese: 'đường' },
  { mandarin: '教室', pinyin: 'jiàoshì', vietnamese: 'phòng học' },
  { mandarin: '离', pinyin: 'lí', vietnamese: 'cách, cách xa' },
  { mandarin: '远', pinyin: 'yuǎn', vietnamese: 'xa' },
  { mandarin: '近', pinyin: 'jìn', vietnamese: 'gần' },
  { mandarin: '快', pinyin: 'kuài', vietnamese: 'nhanh' },
  { mandarin: '走', pinyin: 'zǒu', vietnamese: 'đi, đi bộ' },
  { mandarin: '到', pinyin: 'dào', vietnamese: 'đến' },
  { mandarin: '出差', pinyin: 'chūchāi', vietnamese: 'đi công tác' },

  { mandarin: '给', pinyin: 'gěi', vietnamese: 'cho' },
  { mandarin: '吧', pinyin: 'ba', vietnamese: 'nhé, thôi (trợ từ ngữ khí)' },
  { mandarin: '等', pinyin: 'děng', vietnamese: 'đợi, chờ' },
  { mandarin: '找', pinyin: 'zhǎo', vietnamese: 'tìm' },
  { mandarin: '事', pinyin: 'shì', vietnamese: 'việc, sự việc' },
  { mandarin: '情', pinyin: 'qíng', vietnamese: 'tình cảm, tình hình' },
  { mandarin: '白', pinyin: 'bái', vietnamese: 'trắng' },
  { mandarin: '黑', pinyin: 'hēi', vietnamese: 'đen' },
  { mandarin: '参加', pinyin: 'cānjiā', vietnamese: 'tham gia' },
  { mandarin: '晚会', pinyin: 'wǎnhuì', vietnamese: 'buổi tối, dạ hội' },
  { mandarin: '应该', pinyin: 'yīnggāi', vietnamese: 'nên' },
  { mandarin: '让', pinyin: 'ràng', vietnamese: 'nhường, để cho' },
  { mandarin: '再', pinyin: 'zài', vietnamese: 'lại, nữa' },
  { mandarin: '告诉', pinyin: 'gàosu', vietnamese: 'nói, bảo, kể' },
  { mandarin: '客人', pinyin: 'kèren', vietnamese: 'khách' },

  { mandarin: '错', pinyin: 'cuò', vietnamese: 'sai' },
  { mandarin: '上班', pinyin: 'shàngbān', vietnamese: 'đi làm' },
  { mandarin: '下班', pinyin: 'xiàbān', vietnamese: 'tan làm' },
  { mandarin: '从', pinyin: 'cóng', vietnamese: 'từ' },
  { mandarin: '题', pinyin: 'tí', vietnamese: 'đề, câu hỏi' },
  { mandarin: '问题', pinyin: 'wèntí', vietnamese: 'câu hỏi, vấn đề' },
  { mandarin: '跳舞', pinyin: 'tiàowǔ', vietnamese: 'nhảy múa' },
  { mandarin: '第', pinyin: 'dì', vietnamese: 'thứ, số' },
  { mandarin: '希望', pinyin: 'xīwàng', vietnamese: 'hi vọng' },
  { mandarin: '欢迎', pinyin: 'huānyíng', vietnamese: 'chào đón' },
  { mandarin: '懂', pinyin: 'dǒng', vietnamese: 'hiểu' },
  { mandarin: '完', pinyin: 'wán', vietnamese: 'xong, hết' },

  { mandarin: '绿色', pinyin: 'lǜsè', vietnamese: 'màu xanh lá' },
  { mandarin: '黑色', pinyin: 'hēisè', vietnamese: 'màu đen' },
  { mandarin: '白色', pinyin: 'báisè', vietnamese: 'màu trắng' },
  { mandarin: '蓝色', pinyin: 'lánsè', vietnamese: 'màu xanh dương' },
  { mandarin: '红色', pinyin: 'hóngsè', vietnamese: 'màu đỏ' },
  { mandarin: '休息', pinyin: 'xiūxi', vietnamese: 'nghỉ ngơi' },
  { mandarin: '帮助', pinyin: 'bāngzhù', vietnamese: 'giúp đỡ' },
  { mandarin: '玩儿', pinyin: 'wánr', vietnamese: 'chơi' },
  { mandarin: '手机', pinyin: 'shǒujī', vietnamese: 'điện thoại' },
  { mandarin: '别', pinyin: 'bié', vietnamese: 'đừng' },
  { mandarin: '药', pinyin: 'yào', vietnamese: 'thuốc' },
  { mandarin: '眼睛', pinyin: 'yǎnjing', vietnamese: 'mắt' },
  { mandarin: '正在', pinyin: 'zhèngzài', vietnamese: 'đang' },
  { mandarin: '洗', pinyin: 'xǐ', vietnamese: 'rửa, giặt' },

  { mandarin: '左边', pinyin: 'zuǒbiān', vietnamese: 'bên trái' },
  { mandarin: '右边', pinyin: 'yòubiān', vietnamese: 'bên phải' },
  { mandarin: '说话', pinyin: 'shuōhuà', vietnamese: 'nói chuyện' },
  { mandarin: '可能', pinyin: 'kěnéng', vietnamese: 'có thể' },
  { mandarin: '上个月', pinyin: 'shàng ge yuè', vietnamese: 'tháng trước' },
  { mandarin: '姓', pinyin: 'xìng', vietnamese: 'họ' },
  { mandarin: '刚', pinyin: 'gāng', vietnamese: 'vừa mới' },
  { mandarin: '男孩', pinyin: 'nánhái', vietnamese: 'bé trai' },
  { mandarin: '唱歌', pinyin: 'chànggē', vietnamese: 'hát' },
  { mandarin: '比', pinyin: 'bǐ', vietnamese: 'so với, hơn' },
  { mandarin: '便宜', pinyin: 'piányi', vietnamese: 'rẻ' },
  { mandarin: '西瓜', pinyin: 'xīguā', vietnamese: 'dưa hấu' },
  { mandarin: '香蕉', pinyin: 'xiāngjiāo', vietnamese: 'chuối' },

  { mandarin: '弟弟', pinyin: 'dìdi', vietnamese: 'em trai' },
  { mandarin: '希望', pinyin: 'xīwàng', vietnamese: 'hi vọng' },
  { mandarin: '应该', pinyin: 'yīnggāi', vietnamese: 'nên' },
  { mandarin: '进', pinyin: 'jìn', vietnamese: 'vào' },
  { mandarin: '穿', pinyin: 'chuān', vietnamese: 'mặc (quần áo)' },
  { mandarin: '一般', pinyin: 'yìbān', vietnamese: 'bình thường, nói chung' },
  { mandarin: '近', pinyin: 'jìn', vietnamese: 'gần' },
  { mandarin: '最近', pinyin: 'zuìjìn', vietnamese: 'gần đây' },
  { mandarin: '比较', pinyin: 'bǐjiào', vietnamese: 'tương đối, khá' },
  { mandarin: '得', pinyin: 'de', vietnamese: '(trợ từ kết cấu)' },
  { mandarin: '麻烦', pinyin: 'máfan', vietnamese: 'phiền phức, làm phiền' },
  { mandarin: '妻子', pinyin: 'qīzi', vietnamese: 'vợ' },
  { mandarin: '冬天', pinyin: 'dōngtiān', vietnamese: 'mùa đông' },
  { mandarin: '雪', pinyin: 'xuě', vietnamese: 'tuyết' },
  { mandarin: '零', pinyin: 'líng', vietnamese: 'số không' },
  { mandarin: '度', pinyin: 'dù', vietnamese: 'độ (nhiệt độ)' },

  { mandarin: '手', pinyin: 'shǒu', vietnamese: 'tay' },
  { mandarin: '拿', pinyin: 'ná', vietnamese: 'cầm, lấy' },
  { mandarin: '离', pinyin: 'lí', vietnamese: 'cách' },
  { mandarin: '着', pinyin: 'zhe', vietnamese: '(trợ từ tiếp diễn)' },
  { mandarin: '迟到', pinyin: 'chídào', vietnamese: 'đến muộn' },
  { mandarin: '爱笑', pinyin: 'àixiào', vietnamese: 'thích cười' },
  { mandarin: '聊天', pinyin: 'liáotiān', vietnamese: 'nói chuyện phiếm, tán gẫu' },
  { mandarin: '宾馆', pinyin: 'bīnguǎn', vietnamese: 'nhà nghỉ, khách sạn' },
  { mandarin: '一直', pinyin: 'yìzhí', vietnamese: 'luôn luôn, thẳng' },
  { mandarin: '往', pinyin: 'wǎng', vietnamese: 'về phía, tới' },

  { mandarin: '百', pinyin: 'bǎi', vietnamese: 'trăm' },
  { mandarin: '过', pinyin: 'guò', vietnamese: '(trợ từ kinh nghiệm)' },
  { mandarin: '次', pinyin: 'cì', vietnamese: 'lần' },
  { mandarin: '虽然...但是', pinyin: 'suīrán... dànshì', vietnamese: 'mặc dù... nhưng' },
  { mandarin: '有意思', pinyin: 'yǒuyìsi', vietnamese: 'thú vị' },
  { mandarin: '安排', pinyin: 'ānpái', vietnamese: 'sắp xếp, bố trí' },
  { mandarin: '凤凰古镇', pinyin: 'Fènghuáng Gǔzhèn', vietnamese: 'Phượng Hoàng Cổ Trấn' },
  { mandarin: '晴天', pinyin: 'qíngtiān', vietnamese: 'trời nắng, ngày nắng' },

  { mandarin: '新年', pinyin: 'xīnnián', vietnamese: 'năm mới' },
  { mandarin: '大家', pinyin: 'dàjiā', vietnamese: 'mọi người' },
  { mandarin: '过', pinyin: 'guò', vietnamese: 'ăn (Tết, lễ), trải qua' },
  { mandarin: '日', pinyin: 'rì', vietnamese: 'ngày' },
  { mandarin: '票', pinyin: 'piào', vietnamese: 'vé' },
  { mandarin: '网上', pinyin: 'wǎngshàng', vietnamese: 'trên mạng' },
  { mandarin: '春节', pinyin: 'chūnjié', vietnamese: 'Tết Nguyên Đán' },
  { mandarin: '更', pinyin: 'gèng', vietnamese: 'hơn, càng' },
  { mandarin: '祝', pinyin: 'zhù', vietnamese: 'chúc' },
  { mandarin: '健康', pinyin: 'jiànkāng', vietnamese: 'sức khỏe' },
  { mandarin: '万事如意', pinyin: 'wànshì rúyì', vietnamese: 'vạn sự như ý' },
  { mandarin: '阴', pinyin: 'yīn', vietnamese: 'râm, âm u' },
  { mandarin: '打算', pinyin: 'dǎsuàn', vietnamese: 'dự định' },
  { mandarin: '日用品', pinyin: 'rìyòngpǐn', vietnamese: 'đồ dùng hàng ngày' },
  { mandarin: '记得', pinyin: 'jìde', vietnamese: 'nhớ' },
  { mandarin: '雨伞', pinyin: 'yǔsǎn', vietnamese: 'ô, dù' },
  { mandarin: '火车站', pinyin: 'huǒchēzhàn', vietnamese: 'ga xe lửa' },
  { mandarin: '要...了', pinyin: 'yào... le', vietnamese: 'sắp... rồi' },
];