
import { HSKWord } from './types';

export const TIENG_TRUNG_4_VOCABULARY: HSKWord[] = [
  // Bài 1 (20 từ)
  { mandarin: '高铁', pinyin: 'gāotiě', vietnamese: 'cao tốc' },
  { mandarin: '游戏', pinyin: 'yóuxì', vietnamese: 'trò chơi' },
  { mandarin: '作业', pinyin: 'zuòyè', vietnamese: 'bài tập' },
  { mandarin: '天堂', pinyin: 'tiāntáng', vietnamese: 'thiên đàng' },
  { mandarin: '苏杭', pinyin: 'Sū Háng', vietnamese: 'Tô Châu, Hàng Châu' },
  { mandarin: '地图', pinyin: 'dìtú', vietnamese: 'bản đồ' },
  { mandarin: '要紧', pinyin: 'yàojǐn', vietnamese: 'quan trọng/gấp' },
  { mandarin: '期末', pinyin: 'qīmò', vietnamese: 'cuối kì' },
  { mandarin: '着急', pinyin: 'zháojí', vietnamese: 'lo lắng, vội vàng' },
  { mandarin: '用功', pinyin: 'yònggōng', vietnamese: 'siêng năng, chăm chỉ' },
  { mandarin: '提', pinyin: 'tí', vietnamese: 'nêu ra, xách, nâng' },
  { mandarin: '周末', pinyin: 'zhōumò', vietnamese: 'cuối tuần' },
  { mandarin: '打算', pinyin: 'dǎsuàn', vietnamese: 'dự định' },
  { mandarin: '风景', pinyin: 'fēngjǐng', vietnamese: 'phong cảnh' },
  { mandarin: '一直', pinyin: 'yìzhí', vietnamese: 'luôn, một mạch' },
  { mandarin: '出发', pinyin: 'chūfā', vietnamese: 'xuất phát' },
  { mandarin: '水果', pinyin: 'shuǐguǒ', vietnamese: 'trái cây' },
  { mandarin: '面包', pinyin: 'miànbāo', vietnamese: 'bánh mì' },
  { mandarin: '香蕉', pinyin: 'xiāngjiāo', vietnamese: 'chuối' },
  { mandarin: '担心', pinyin: 'dānxīn', vietnamese: 'lo lắng' },
  // Bài 2 (18 từ)
  { mandarin: '拿', pinyin: 'ná', vietnamese: 'cầm, lấy' },
  { mandarin: '玩儿', pinyin: 'wánr', vietnamese: 'chơi' },
  { mandarin: '该', pinyin: 'gāi', vietnamese: 'nên, cần' },
  { mandarin: '辆', pinyin: 'liàng', vietnamese: 'lượng từ chiếc (xe)' },
  { mandarin: '楼', pinyin: 'lóu', vietnamese: 'lầu, tòa nhà' },
  { mandarin: '把', pinyin: 'bǎ', vietnamese: 'lượng từ (cho vật có cán/tay cầm)' },
  { mandarin: '伞', pinyin: 'sǎn', vietnamese: 'dù, ô' },
  { mandarin: '照相机', pinyin: 'zhàoxiāngjī', vietnamese: 'máy ảnh' },
  { mandarin: '嗯', pinyin: 'ēn', vietnamese: 'ừ, à (đồng ý)' },
  { mandarin: '极了', pinyin: 'jí le', vietnamese: 'cực kỳ, hết sức' },
  { mandarin: '特别', pinyin: 'tèbié', vietnamese: 'đặc biệt' },
  { mandarin: '不过', pinyin: 'búguò', vietnamese: 'nhưng mà, chẳng qua là' },
  { mandarin: '容易', pinyin: 'róngyì', vietnamese: 'dễ dàng' },
  { mandarin: '难', pinyin: 'nán', vietnamese: 'khó' },
  { mandarin: '也许', pinyin: 'yěxǔ', vietnamese: 'có lẽ, có thể' },
  { mandarin: '其实', pinyin: 'qíshí', vietnamese: 'thật ra, thực tế' },
  { mandarin: '香山', pinyin: 'Xiāngshān', vietnamese: 'Hương Sơn' },
  { mandarin: '红叶', pinyin: 'hóngyè', vietnamese: 'lá đỏ (lá phong)' },
];
