import { HSKWord } from './types';

export const TIENG_TRUNG_5_VOCABULARY: HSKWord[] = [
  // Bài 1
  { mandarin: '图书馆', pinyin: 'túshūguǎn', vietnamese: 'thư viện' },
  { mandarin: '借', pinyin: 'jiè', vietnamese: 'mượn' },
  { mandarin: '还', pinyin: 'huán', vietnamese: 'trả' },
  { mandarin: '关', pinyin: 'guān', vietnamese: 'đóng/tắt' },
  { mandarin: '会议', pinyin: 'huìyì', vietnamese: 'cuộc họp' },
  { mandarin: '词典', pinyin: 'cídiǎn', vietnamese: 'từ điển' },
  { mandarin: '困', pinyin: 'kùn', vietnamese: 'buồn ngủ' },
  { mandarin: '躺', pinyin: 'tǎng', vietnamese: 'nằm' },
  { mandarin: '过期', pinyin: 'guòqī', vietnamese: 'quá hạn' },
  { mandarin: '空调', pinyin: 'kōngtiáo', vietnamese: 'máy điều hòa' },
  { mandarin: '结束', pinyin: 'jiéshù', vietnamese: 'kết thúc' },
  { mandarin: '忘记', pinyin: 'wàngjì', vietnamese: 'quên' },
  { mandarin: '左右', pinyin: 'zuǒyòu', vietnamese: 'khoảng' },
  { mandarin: '心意', pinyin: 'xīnyì', vietnamese: 'tấm lòng' },
  { mandarin: '敬', pinyin: 'jìng', vietnamese: 'kính (mời)' },
  { mandarin: '双', pinyin: 'shuāng', vietnamese: 'đôi' },
  { mandarin: '筷子', pinyin: 'kuàizi', vietnamese: 'đũa' },
  { mandarin: '啤酒', pinyin: 'píjiǔ', vietnamese: 'bia' },
  { mandarin: '瓶子', pinyin: 'píngzi', vietnamese: 'chai / lọ' },
  { mandarin: '留', pinyin: 'liú', vietnamese: 'ở lại / giữ lại' },
  { mandarin: '忙碌', pinyin: 'mánglù', vietnamese: 'bận rộn' },
  { mandarin: '习惯', pinyin: 'xíguàn', vietnamese: 'thói quen' },
  { mandarin: '地铁', pinyin: 'dìtiě', vietnamese: 'tàu điện ngầm' },
  { mandarin: '笔记本', pinyin: 'bǐjìběn', vietnamese: 'vở / máy tính xách tay' },
  { mandarin: '客户', pinyin: 'kèhù', vietnamese: 'khách hàng' },
  { mandarin: '联系', pinyin: 'liánxì', vietnamese: 'liên lạc' },
  { mandarin: '领工资', pinyin: 'lǐng gōngzī', vietnamese: 'nhận lương' },
  { mandarin: '坏', pinyin: 'huài', vietnamese: 'cực kì, quá sức （adj + 坏）' },
  { mandarin: '赶', pinyin: 'gǎn', vietnamese: 'khẩn trương, vội vã' },
  // Bài 2
  { mandarin: '机票', pinyin: 'jī piào', vietnamese: 'Vé máy bay' },
  { mandarin: '期末', pinyin: 'qī mò', vietnamese: 'Cuối kỳ' },
  { mandarin: '赶', pinyin: 'gǎn', vietnamese: 'Đuổi theo, vội vã, tranh thủ (thời gian)' },
  { mandarin: '为了', pinyin: 'wèi le', vietnamese: 'Để, vì, để cho (biểu thị mục đích)' },
  { mandarin: '生气', pinyin: 'shēngqì', vietnamese: 'tức giận' },
  { mandarin: '堵车', pinyin: 'dǔchē', vietnamese: 'tắc xe' },
  { mandarin: '发现', pinyin: 'fāxiàn', vietnamese: 'phát hiện' },
  { mandarin: '护照', pinyin: 'hùzhào', vietnamese: 'hộ chiếu' },
  { mandarin: '只好', pinyin: 'zhǐhǎo', vietnamese: 'đành phải' },
  { mandarin: '司机', pinyin: 'sījī', vietnamese: 'tài xế' },
  { mandarin: '行李箱', pinyin: 'xínglixiāng', vietnamese: 'vali' },
  { mandarin: '估计', pinyin: 'gūjì', vietnamese: 'ước tính, đoán' },
  { mandarin: '报告', pinyin: 'bàogào', vietnamese: 'báo cáo' },
  { mandarin: '交', pinyin: 'jiāo', vietnamese: 'nộp' },
  { mandarin: '注意', pinyin: 'zhùyì', vietnamese: 'chú ý' },
  { mandarin: '争取', pinyin: 'zhēngqǔ', vietnamese: 'tranh thủ, cố gắng' },
  { mandarin: '实习', pinyin: 'shíxí', vietnamese: 'thực tập' },
  { mandarin: '留学', pinyin: 'liúxué', vietnamese: 'du học' },
  { mandarin: '研究生', pinyin: 'yánjiūshēng', vietnamese: 'nghiên cứu sinh' },
  { mandarin: '需要', pinyin: 'xūyào', vietnamese: 'cần' },
  { mandarin: '黑板', pinyin: 'hēibǎn', vietnamese: 'bảng đen' },
  { mandarin: '答卷', pinyin: 'dájuàn', vietnamese: 'tờ bài làm, bài thi' },
  { mandarin: '紧张', pinyin: 'jǐnzhāng', vietnamese: 'lo lắng, căng thẳng' },
  { mandarin: '其中', pinyin: 'qízhōng', vietnamese: 'trong đó' },
  { mandarin: '翻译', pinyin: 'fānyì', vietnamese: 'dịch, biên dịch' },
  // Bài 3
  { mandarin: '麻烦', pinyin: 'máfàn', vietnamese: 'phiền phức' },
  { mandarin: '顾', pinyin: 'gù', vietnamese: 'lo, chú ý' },
  { mandarin: '留下', pinyin: 'liúxià', vietnamese: 'để lại, ở lại' },
  { mandarin: '终于', pinyin: 'zhōngyú', vietnamese: 'cuối cùng, rốt cuộc' },
  { mandarin: '电梯', pinyin: 'diàntī', vietnamese: 'thang máy' },
  { mandarin: '楼梯', pinyin: 'lóutī', vietnamese: 'thang bộ' },
  { mandarin: '贴', pinyin: 'tiē', vietnamese: 'dán' },
  { mandarin: '对面', pinyin: 'duìmiàn', vietnamese: 'đối diện' },
  { mandarin: '商场', pinyin: 'shāngchǎng', vietnamese: 'trung tâm mua sắm / mall' },
  { mandarin: '购物', pinyin: 'gòuwù', vietnamese: 'mua sắm' },
  { mandarin: '外套', pinyin: 'wàitào', vietnamese: 'áo khoác, áo choàng' },
  { mandarin: '包裹', pinyin: 'bāoguǒ', vietnamese: 'bưu phẩm' },
  { mandarin: '关照', pinyin: 'guānzhào', vietnamese: 'chiếu cố' },
  { mandarin: '加入', pinyin: 'jiārù', vietnamese: 'gia nhập' },
  { mandarin: '经营部', pinyin: 'jīngyíngbù', vietnamese: 'Phòng kinh doanh' },
  { mandarin: '遇到', pinyin: 'yùdào', vietnamese: 'gặp phải' },
  { mandarin: '尝试', pinyin: 'chángshì', vietnamese: 'thử (thưởng thức)' },
  { mandarin: '经验', pinyin: 'jīngyàn', vietnamese: 'kinh nghiệm' },
  { mandarin: '熟悉', pinyin: 'shúxī', vietnamese: 'làm quen' },
  { mandarin: '快递', pinyin: 'kuàidì', vietnamese: 'chuyển phát nhanh' },
  { mandarin: '深刻', pinyin: 'shēnkè', vietnamese: 'sâu sắc' },
  { mandarin: '印象', pinyin: 'yìnxiàng', vietnamese: 'ấn tượng' },
  { mandarin: '缆车', pinyin: 'lǎnchē', vietnamese: 'cáp treo' },
  { mandarin: '吃力', pinyin: 'chīlì', vietnamese: 'cố sức (mệt), vất vả' },
  { mandarin: '过去', pinyin: 'guòqù', vietnamese: 'qua bên kia, đó/ quá khứ' },
  { mandarin: '愿意', pinyin: 'yuànyì', vietnamese: 'sẵn lòng' },
  // Bài 4
  { mandarin: '总是', pinyin: 'zǒngshì', vietnamese: 'luôn luôn' },
  { mandarin: '叔叔', pinyin: 'shūshu', vietnamese: 'chú' },
  { mandarin: '阿姨', pinyin: 'āyí', vietnamese: 'dì' },
  { mandarin: '来不及', pinyin: 'láibují', vietnamese: 'không kịp' },
  { mandarin: '来得及', pinyin: 'láidejí', vietnamese: 'kịp' },
  { mandarin: '打扫', pinyin: 'dǎsǎo', vietnamese: 'quét dọn' },
  { mandarin: '冰箱', pinyin: 'bīngxiāng', vietnamese: 'tủ lạnh' },
  { mandarin: '布置', pinyin: 'bùzhì', vietnamese: 'trang trí, sắp xếp' },
  { mandarin: '纪念', pinyin: 'jìniàn', vietnamese: 'kỷ niệm' },
  { mandarin: '庆祝', pinyin: 'qìngzhù', vietnamese: 'ăn mừng' },
  { mandarin: '举办', pinyin: 'jǔbàn', vietnamese: 'tổ chức' },
  { mandarin: '了解', pinyin: 'liǎojiě', vietnamese: 'tìm hiểu' },
  { mandarin: '自助餐', pinyin: 'zìzhùcān', vietnamese: 'buffet' },
  { mandarin: '菜单', pinyin: 'càidān', vietnamese: 'thực đơn' },
  { mandarin: '一般', pinyin: 'yìbān', vietnamese: 'thông thường' },
  { mandarin: '简单', pinyin: 'jiǎndān', vietnamese: 'đơn giản' },
  { mandarin: '西红柿', pinyin: 'xīhóngshì', vietnamese: 'cà chua' },
  { mandarin: '炒', pinyin: 'chǎo', vietnamese: 'xào' },
  { mandarin: '月亮', pinyin: 'yuèliang', vietnamese: 'mặt trăng' },
  { mandarin: '盘子', pinyin: 'pánzi', vietnamese: 'cái dĩa' },
  // Bài 5
  { mandarin: '发音', pinyin: 'fāyīn', vietnamese: 'phát âm' },
  { mandarin: '留学', pinyin: 'liúxué', vietnamese: 'du học' },
  { mandarin: '安排', pinyin: 'ānpái', vietnamese: 'sắp xếp' },
  { mandarin: '极了', pinyin: 'jíle', vietnamese: 'quá, cực kỳ' },
  { mandarin: '注意', pinyin: 'zhùyì', vietnamese: 'chú ý' },
  { mandarin: '发', pinyin: 'fā', vietnamese: 'gửi' },
  { mandarin: '提高', pinyin: 'tígāo', vietnamese: 'nâng cao' },
  { mandarin: '决定', pinyin: 'juédìng', vietnamese: 'quyết định' },
  { mandarin: '方法', pinyin: 'fāngfǎ', vietnamese: 'phương pháp, cách' },
  { mandarin: '按时', pinyin: 'ànshí', vietnamese: 'đúng giờ' },
  { mandarin: '花', pinyin: 'huā', vietnamese: 'tiêu, tốn' },
  { mandarin: '新闻', pinyin: 'xīnwén', vietnamese: 'tin tức' },
  { mandarin: '世界', pinyin: 'shìjiè', vietnamese: 'thế giới' },
  { mandarin: '要求', pinyin: 'yāoqiú', vietnamese: 'yêu cầu' },
  { mandarin: '其他', pinyin: 'qítā', vietnamese: 'những cái khác/ the rest' },
  { mandarin: '按照', pinyin: 'ànzhào', vietnamese: 'căn cứ, dựa theo' },
  { mandarin: '提醒', pinyin: 'tíxǐng', vietnamese: 'nhắc nhở' },
  { mandarin: '传统', pinyin: 'chuántǒng', vietnamese: 'truyền thống/ bảo thủ' },
  { mandarin: '放假', pinyin: 'fàng jià', vietnamese: 'nghỉ, nghỉ phép' },
  { mandarin: '丰富', pinyin: 'fēngfù', vietnamese: 'phong phú' },
  { mandarin: '街道', pinyin: 'jièdào', vietnamese: 'đường phố' },
  { mandarin: '活动', pinyin: 'huódòng', vietnamese: 'hoạt động' },
  { mandarin: '增加', pinyin: 'zēngjiā', vietnamese: 'gia tăng' },
  { mandarin: '怪不得', pinyin: 'guàibùdé', vietnamese: 'hèn chi' },
  { mandarin: '除了...以外', pinyin: 'chúle... yǐwài', vietnamese: 'ngoài...ra, cũng/đều' },
  // Bài 6
  { mandarin: '机会', pinyin: 'jīhuì', vietnamese: 'cơ hội' },
  { mandarin: '皮鞋', pinyin: 'píxié', vietnamese: 'giày da' },
  { mandarin: '可爱', pinyin: 'kěài', vietnamese: 'đáng yêu, dễ thương' },
  { mandarin: '忙碌', pinyin: 'mánglù', vietnamese: 'bận rộn' },
  { mandarin: '选择', pinyin: 'xuǎnzé', vietnamese: 'chọn lựa' },
  { mandarin: '城市', pinyin: 'chéngshì', vietnamese: 'thành phố' },
  { mandarin: '年纪', pinyin: 'niánjì', vietnamese: 'tuổi tác' },
  { mandarin: '压力', pinyin: 'yālì', vietnamese: 'áp lực' },
  { mandarin: '农村', pinyin: 'nóngcūn', vietnamese: 'nông thôn' },
  { mandarin: '重新', pinyin: 'chóngxīn', vietnamese: 'làm lại' },
  { mandarin: '公斤', pinyin: 'gōngjīn', vietnamese: 'kilogram' },
  { mandarin: '头发', pinyin: 'tóufā', vietnamese: 'tóc' },
  { mandarin: '鼻子', pinyin: 'bízi', vietnamese: 'mũi' },
  { mandarin: '帽子', pinyin: 'màozi', vietnamese: 'mũ, nón' },
  { mandarin: '顶', pinyin: 'dǐng', vietnamese: 'lượng từ cho mũ' },
  { mandarin: '戴', pinyin: 'dài', vietnamese: 'đội, đeo' },
  { mandarin: '检查', pinyin: 'jiǎnchá', vietnamese: 'kiểm tra' },
  { mandarin: '货', pinyin: 'huò', vietnamese: 'hàng hóa' },
  { mandarin: '无数', pinyin: 'wúshù', vietnamese: 'vô số' },
  { mandarin: '距离', pinyin: 'jùlí', vietnamese: 'khoảng cách' },
  { mandarin: '关系', pinyin: 'guānxì', vietnamese: 'mối quan hệ' },
  { mandarin: '善良', pinyin: 'shànliáng', vietnamese: 'hiền lành' },
  { mandarin: '问好', pinyin: 'wènhǎo', vietnamese: 'hỏi thăm' },
  { mandarin: '词语', pinyin: 'cíyǔ', vietnamese: 'từ ngữ' },
  // Bài 7
  { mandarin: '舒服', pinyin: 'shūfu', vietnamese: 'thoải mái' },
  { mandarin: '丈夫', pinyin: 'zhàngfu', vietnamese: 'chồng' },
  { mandarin: '妻子', pinyin: 'qīzi', vietnamese: 'vợ' },
  { mandarin: '夫妻俩', pinyin: 'fùqīliǎ', vietnamese: 'hai vợ chồng' },
  { mandarin: '假期', pinyin: 'jiàqī', vietnamese: 'kỳ nghỉ' },
  { mandarin: '健康', pinyin: 'jiànkāng', vietnamese: 'sức khỏe, khỏe mạnh' },
  { mandarin: '办法', pinyin: 'bànfǎ', vietnamese: 'phương pháp, cách' },
  { mandarin: '治', pinyin: 'zhì', vietnamese: 'chữa, trị' },
  { mandarin: '邻居', pinyin: 'línjū', vietnamese: 'láng giềng' },
  { mandarin: '认真', pinyin: 'rènzhēn', vietnamese: 'nghiêm túc' },
  { mandarin: '三天打鱼两天晒网', pinyin: 'sān tiān dǎ yú liǎng tiān shài wǎng', vietnamese: 'bữa đực bữa cái' },
  { mandarin: '态度', pinyin: 'tàidù', vietnamese: 'thái độ' },
  { mandarin: '用功', pinyin: 'yònggōng', vietnamese: 'chăm chỉ' },
  { mandarin: '计划', pinyin: 'jìhuà', vietnamese: 'kế hoạch' },
  { mandarin: '游览', pinyin: 'yóulǎn', vietnamese: 'du ngoạn' },
  { mandarin: '名胜古迹', pinyin: 'míng shèng gǔ jī', vietnamese: 'danh lam thắng cảnh' },
  { mandarin: '老家', pinyin: 'lǎojiā', vietnamese: 'quê nhà' },
  { mandarin: '老', pinyin: 'lǎo', vietnamese: 'cũ (sắc thái, tình cảm)' },
  { mandarin: '旧', pinyin: 'jiù', vietnamese: 'cũ (tính chất)' },
  { mandarin: '网课', pinyin: 'wǎngkè', vietnamese: 'lớp học online' },
  { mandarin: '碰', pinyin: 'pèng', vietnamese: 'đụng, va phải' },
  { mandarin: '报名', pinyin: 'bàomíng', vietnamese: 'ghi danh' },
  { mandarin: '谈', pinyin: 'tán', vietnamese: 'nói về, bàn về' },
  { mandarin: '饮食', pinyin: 'yǐnshí', vietnamese: 'ẩm thực, ăn uống' },
  { mandarin: '合理', pinyin: 'hélǐ', vietnamese: 'hợp lý' },
  { mandarin: '匆忙', pinyin: 'cōngmáng', vietnamese: 'vội vàng' },
  { mandarin: '根据', pinyin: 'gēnjù', vietnamese: 'căn cứ' },
  // Bài 8
  { mandarin: '增加', pinyin: 'zēngjiā', vietnamese: 'gia tăng, làm tăng' },
  { mandarin: '鼻子', pinyin: 'bízi', vietnamese: 'cái mũi' },
  { mandarin: '推荐', pinyin: 'tuījiàn', vietnamese: 'đề cử (giới thiệu)' },
  { mandarin: '自我', pinyin: 'zìwǒ', vietnamese: 'bản thân' },
  { mandarin: '专业', pinyin: 'zhuānyè', vietnamese: 'chuyên ngành' },
  { mandarin: '成绩', pinyin: 'chéngjì', vietnamese: 'thành tích, kết quả' },
  { mandarin: '选修', pinyin: 'xuǎnxiū', vietnamese: 'chọn học' },
  { mandarin: '抽时间', pinyin: 'chōu shíjiān', vietnamese: 'tranh thủ thời gian' },
  { mandarin: '知识', pinyin: 'zhīshi', vietnamese: 'kiến thức' },
  { mandarin: '只', pinyin: 'zhī', vietnamese: 'con (động vật), cái' },
  { mandarin: '嘴', pinyin: 'zuǐ', vietnamese: 'cái miệng' },
  { mandarin: '竹子', pinyin: 'zhúzi', vietnamese: 'tre' },
  { mandarin: '段', pinyin: 'duàn', vietnamese: 'khoảng, đoạn' },
  { mandarin: '奇怪', pinyin: 'qíguài', vietnamese: 'kỳ lạ' },
  { mandarin: '适合', pinyin: 'shìhé', vietnamese: 'phù hợp' },
  { mandarin: '跟...有关', pinyin: 'gēn ...yǒuguān', vietnamese: 'có liên quan đến' },
  { mandarin: '特点', pinyin: 'tèdiǎn', vietnamese: 'đặc điểm' },
  { mandarin: '收入', pinyin: 'shōurù', vietnamese: 'thu nhập' },
  { mandarin: '勉强', pinyin: 'miǎnqiǎng', vietnamese: 'miễn cưỡng' },
  { mandarin: '影响', pinyin: 'yǐngxiǎng', vietnamese: 'ảnh hưởng' },
  { mandarin: '看重', pinyin: 'kànzhòng', vietnamese: 'xem trọng' },
  { mandarin: '不但...而且', pinyin: 'bùdàn... érqiě...', vietnamese: 'Không những … mà còn' },
  { mandarin: '关于', pinyin: 'guānyú', vietnamese: 'về' },
  { mandarin: '了', pinyin: 'liǎo', vietnamese: 'xong, rồi (kết quả / khả năng)' },
  { mandarin: '哪怕...也/都...', pinyin: 'nǎpà...... yě/dōu.....', vietnamese: 'Cho dù ... cũng...' },
  // Bài 9
  { mandarin: '声音', pinyin: 'shēngyīn', vietnamese: 'âm thanh, tiếng' },
  { mandarin: '当', pinyin: 'dāng', vietnamese: 'làm một nghề nghiệp, chức vụ nào đó' },
  { mandarin: '中间', pinyin: 'zhōngjiān', vietnamese: 'chính giữa' },
  { mandarin: '应该', pinyin: 'yīnggāi', vietnamese: 'nên, cần phải' },
  { mandarin: '熟悉', pinyin: 'shúxī', vietnamese: 'thân thuộc, thân quen' },
  { mandarin: '翻译', pinyin: 'fānyì', vietnamese: 'phiên dịch' },
  { mandarin: '呆', pinyin: 'dāi', vietnamese: 'ở lại' },
  { mandarin: '派', pinyin: 'pài', vietnamese: 'cử, phái' },
  { mandarin: '挺...的', pinyin: 'tǐng...de', vietnamese: 'khá là' },
  { mandarin: '郊游', pinyin: 'jiāoyóu', vietnamese: 'đi chơi ở ngoại ô, picnic' },
  { mandarin: '帅', pinyin: 'shuài', vietnamese: 'đẹp trai' },
  { mandarin: '好像', pinyin: 'hǎoxiàng', vietnamese: 'dường như, giống như' },
  { mandarin: '耳朵', pinyin: 'ěrduo', vietnamese: 'tai' },
  { mandarin: '脸', pinyin: 'liǎn', vietnamese: 'mặt' },
  { mandarin: '学会', pinyin: 'xuéhuì', vietnamese: 'học được, biết' },
  { mandarin: '谦虚', pinyin: 'qiānxū', vietnamese: 'khiêm tốn' },
  { mandarin: '进步', pinyin: 'jìnbù', vietnamese: 'tiến bộ' },
  { mandarin: '处事', pinyin: 'chǔshì', vietnamese: 'xử sự' },
  { mandarin: '请教', pinyin: 'qǐngjiào', vietnamese: 'nhờ ai đó chỉ bảo' },
  { mandarin: '当然', pinyin: 'dāngrán', vietnamese: 'đương nhiên' },
  // Bài 10
  { mandarin: '熟悉', pinyin: 'shúxī', vietnamese: 'quen thuộc, làm quen' },
  { mandarin: '困难', pinyin: 'kùnnán', vietnamese: 'khó khăn' },
  { mandarin: '难题', pinyin: 'nántí', vietnamese: 'vấn đề khó' },
  { mandarin: '影响', pinyin: 'yǐngxiǎng', vietnamese: 'ảnh hưởng' },
  { mandarin: '年轻人', pinyin: 'niánqīng rén', vietnamese: 'người trẻ' },
  { mandarin: '早晚', pinyin: 'zǎowǎn', vietnamese: 'sớm muộn' },
  { mandarin: '互相', pinyin: 'hùxiāng', vietnamese: 'lẫn nhau' },
  { mandarin: '吸引', pinyin: 'xīyǐn', vietnamese: 'thu hút' },
  { mandarin: '接触', pinyin: 'jiēchù', vietnamese: 'tiếp xúc' },
  { mandarin: '解决', pinyin: 'jiějué', vietnamese: 'giải quyết' },
  { mandarin: '谈恋爱', pinyin: 'tán liàn’ài', vietnamese: 'yêu nhau' },
  { mandarin: '变化', pinyin: 'biànhuà', vietnamese: 'thay đổi' },
  { mandarin: '难过', pinyin: 'nánguò', vietnamese: 'buồn, buồn phiền' },
  { mandarin: '批评', pinyin: 'pīpíng', vietnamese: 'phê bình' },
  { mandarin: '偷', pinyin: 'tōu', vietnamese: 'lấy cắp, trộm' },
  { mandarin: '丢', pinyin: 'diū', vietnamese: 'đánh rơi, làm mất' },
  { mandarin: '照相机', pinyin: 'zhàoxiàngjī', vietnamese: 'máy chụp hình' },
  { mandarin: '照片', pinyin: 'zhàopiàn', vietnamese: 'hình chụp' },
  { mandarin: '签', pinyin: 'qiān', vietnamese: 'ký' },
  { mandarin: '负责', pinyin: 'fùzé', vietnamese: 'phụ trách, chịu trách nhiệm' },
  { mandarin: '手续', pinyin: 'shǒuxù', vietnamese: 'thủ tục' },
  { mandarin: '着急', pinyin: 'zháojí', vietnamese: 'sốt ruột' },
  { mandarin: '灰心', pinyin: 'huīxīn', vietnamese: 'nản lòng' },
  { mandarin: '真正', pinyin: 'zhēnzhèng', vietnamese: 'thật sự, chân chính' },
  { mandarin: '相信', pinyin: 'xiāngxìn', vietnamese: 'tin rằng' },
  { mandarin: '被', pinyin: 'bèi', vietnamese: 'bị (bị động)' },
];
