

import { HSKWord } from './types';

export const TIENG_TRUNG_3_VOCABULARY: HSKWord[] = [
  // Bài 1 (1-17)
  { mandarin: '周末', pinyin: 'zhōumò', vietnamese: 'Cuối tuần' },
  { mandarin: '打算', pinyin: 'dǎsuan', vietnamese: 'Dự định, tính toán' },
  { mandarin: '啊', pinyin: 'a', vietnamese: 'Trợ từ cuối câu' },
  { mandarin: '跟', pinyin: 'gēn', vietnamese: 'Với, cùng' },
  { mandarin: '小丽', pinyin: 'Xiǎolì', vietnamese: 'Tiểu Lệ' },
  { mandarin: '小刚', pinyin: 'Xiǎogāng', vietnamese: 'Tiểu Cương' },
  { mandarin: '一直', pinyin: 'yīzhí', vietnamese: 'Luôn luôn, mãi, thẳng' },
  { mandarin: '游戏', pinyin: 'yóuxì', vietnamese: 'Trò chơi' },
  { mandarin: '作业', pinyin: 'zuòyè', vietnamese: 'Bài tập' },
  { mandarin: '着急', pinyin: 'zháojí', vietnamese: 'Lo lắng, sốt ruột' },
  { mandarin: '复习', pinyin: 'fùxí', vietnamese: 'Ôn tập' },
  { mandarin: '南方', pinyin: 'nánfāng', vietnamese: 'Miền Nam' },
  { mandarin: '北方', pinyin: 'běifāng', vietnamese: 'Miền Bắc' },
  { mandarin: '面包', pinyin: 'miànbāo', vietnamese: 'Bánh mì' },
  { mandarin: '带', pinyin: 'dài', vietnamese: 'Mang, đem theo' },
  { mandarin: '地图', pinyin: 'dìtú', vietnamese: 'Bản đồ' },
  { mandarin: '搬', pinyin: 'bān', vietnamese: 'Chuyển (nhà, đồ đạc)' },
  // Bài 2 (18-35)
  { mandarin: '腿', pinyin: 'tuǐ', vietnamese: 'Chân' },
  { mandarin: '疼', pinyin: 'téng', vietnamese: 'Đau' },
  { mandarin: '脚', pinyin: 'jiǎo', vietnamese: 'Bàn chân, chân' },
  { mandarin: '树', pinyin: 'shù', vietnamese: 'Cây' },
  { mandarin: '容易', pinyin: 'róngyì', vietnamese: 'Dễ dàng' },
  { mandarin: '难', pinyin: 'nán', vietnamese: 'Khó' },
  { mandarin: '太太', pinyin: 'tàitai', vietnamese: 'Vợ, quý bà' },
  { mandarin: '秘书', pinyin: 'mìshū', vietnamese: 'Thư ký' },
  { mandarin: '经理', pinyin: 'jīnglǐ', vietnamese: 'Giám đốc, quản lý' },
  { mandarin: '办公室', pinyin: 'bàngōngshì', vietnamese: 'Văn phòng' },
  { mandarin: '辆', pinyin: 'liàng', vietnamese: 'Chiếc, cái (xe)' },
  { mandarin: '楼', pinyin: 'lóu', vietnamese: 'Tầng, lầu' },
  { mandarin: '拿', pinyin: 'ná', vietnamese: 'Cầm, lấy' },
  { mandarin: '把', pinyin: 'bǎ', vietnamese: 'Nắm, chiếc (lượng từ)' },
  { mandarin: '雨伞', pinyin: 'yǔsǎn', vietnamese: 'Ô/Dù' },
  { mandarin: '胖', pinyin: 'pàng', vietnamese: 'Béo, mập' },
  { mandarin: '瘦', pinyin: 'shòu', vietnamese: 'Gầy, ốm' },
  { mandarin: '其实', pinyin: 'qíshí', vietnamese: 'Thật ra, kỳ thực' },
  // Bài 3 (36-52)
  { mandarin: '还是', pinyin: 'háishì', vietnamese: 'Vẫn là, hay là' },
  { mandarin: '爬山', pinyin: 'páshān', vietnamese: 'Leo núi' },
  { mandarin: '小心', pinyin: 'xiǎoxīn', vietnamese: 'Cẩn thận' },
  { mandarin: '条', pinyin: 'tiáo', vietnamese: 'Cái, chiếc (vật dài)' },
  { mandarin: '裤子', pinyin: 'kùzi', vietnamese: 'Quần' },
  { mandarin: '衬衫', pinyin: 'chènshān', vietnamese: 'Áo sơ mi' },
  { mandarin: '记得', pinyin: 'jìde', vietnamese: 'Nhớ' },
  { mandarin: '元', pinyin: 'yuán', vietnamese: 'Đồng (tiền)' },
  { mandarin: '新鲜', pinyin: 'xīnxiān', vietnamese: 'Tươi, tươi mới' },
  { mandarin: '甜', pinyin: 'tián', vietnamese: 'Ngọt' },
  { mandarin: '只', pinyin: 'zhǐ', vietnamese: 'Chỉ' },
  { mandarin: '放', pinyin: 'fàng', vietnamese: 'Đặt, để, thả' },
  { mandarin: '饮料', pinyin: 'yǐnliào', vietnamese: 'Đồ uống' },
  { mandarin: '或者', pinyin: 'huòzhě', vietnamese: 'Hoặc là' },
  { mandarin: '舒服', pinyin: 'shūfu', vietnamese: 'Thoải mái, dễ chịu' },
  { mandarin: '花', pinyin: 'huā', vietnamese: 'Hoa' },
  { mandarin: '绿', pinyin: 'lǜ', vietnamese: 'Màu xanh lá cây' },
  // Bài 4 (53-68)
  { mandarin: '比赛', pinyin: 'bǐsài', vietnamese: 'Thi đấu, cuộc thi' },
  { mandarin: '照片', pinyin: 'zhàopiàn', vietnamese: 'Ảnh, hình ảnh' },
  { mandarin: '年纪', pinyin: 'niánjì', vietnamese: 'Tuổi tác' },
  { mandarin: '又', pinyin: 'yòu', vietnamese: 'Lại, vừa' },
  { mandarin: '聪明', pinyin: 'cōngming', vietnamese: 'Thông minh' },
  { mandarin: '热情', pinyin: 'rèqíng', vietnamese: 'Nhiệt tình' },
  { mandarin: '努力', pinyin: 'nǔlì', vietnamese: 'Cố gắng, nỗ lực' },
  { mandarin: '总是', pinyin: 'zǒngshì', vietnamese: 'Luôn luôn' },
  { mandarin: '回答', pinyin: 'huídá', vietnamese: 'Trả lời' },
  { mandarin: '站', pinyin: 'zhàn', vietnamese: 'Đứng, trạm' },
  { mandarin: '饿', pinyin: 'è', vietnamese: 'Đói' },
  { mandarin: '超市', pinyin: 'chāoshì', vietnamese: 'Siêu thị' },
  { mandarin: '蛋糕', pinyin: 'dàngāo', vietnamese: 'Bánh gato/kem' },
  { mandarin: '年轻', pinyin: 'niánqīng', vietnamese: 'Trẻ, trẻ tuổi' },
  { mandarin: '认真', pinyin: 'rènzhēn', vietnamese: 'Nghiêm túc, chăm chỉ' },
  { mandarin: '客人', pinyin: 'kèren', vietnamese: 'Khách, khách hàng' },
  // Bài 5 (69-83)
  { mandarin: '发烧', pinyin: 'fāshāo', vietnamese: 'Sốt' },
  { mandarin: '为', pinyin: 'wèi', vietnamese: 'Vì, cho' },
  { mandarin: '照顾', pinyin: 'zhàogù', vietnamese: 'Chăm sóc' },
  { mandarin: '用', pinyin: 'yòng', vietnamese: 'Dùng, sử dụng' },
  { mandarin: '感冒', pinyin: 'gǎnmào', vietnamese: 'Cảm cúm' },
  { mandarin: '张先生', pinyin: 'Zhāng Xiānsheng', vietnamese: 'Ông Trương' },
  { mandarin: '季节', pinyin: 'jìjié', vietnamese: 'Mùa' },
  { mandarin: '当然', pinyin: 'dāngrán', vietnamese: 'Đương nhiên, tất nhiên' },
  { mandarin: '春天', pinyin: 'chūntiān', vietnamese: 'Mùa xuân' },
  { mandarin: '草', pinyin: 'cǎo', vietnamese: 'Cỏ' },
  { mandarin: '夏天', pinyin: 'xiàtiān', vietnamese: 'Mùa hè' },
  { mandarin: '裙子', pinyin: 'qúnzi', vietnamese: 'Váy, đầm' },
  { mandarin: '最近', pinyin: 'zuìjìn', vietnamese: 'Gần đây' },
  { mandarin: '越来', pinyin: 'yuèlái', vietnamese: 'Càng ngày càng' },
  { mandarin: '月', pinyin: 'yuè', vietnamese: 'Tháng' }, // Added to balance if needed, based on context often appearing
  // Bài 6 (84-99)
  { mandarin: '眼睛', pinyin: 'yǎnjing', vietnamese: 'Mắt' },
  { mandarin: '突然', pinyin: 'tūrán', vietnamese: 'Đột nhiên' },
  { mandarin: '离开', pinyin: 'líkāi', vietnamese: 'Rời khỏi' },
  { mandarin: '清楚', pinyin: 'qīngchu', vietnamese: 'Rõ ràng' },
  { mandarin: '刚才', pinyin: 'gāngcái', vietnamese: 'Vừa nãy, lúc nãy' },
  { mandarin: '帮忙', pinyin: 'bāngmáng', vietnamese: 'Giúp đỡ' },
  { mandarin: '特别', pinyin: 'tèbié', vietnamese: 'Đặc biệt' },
  { mandarin: '讲', pinyin: 'jiǎng', vietnamese: 'Giảng, nói' },
  { mandarin: '明白', pinyin: 'míngbai', vietnamese: 'Hiểu rõ, rõ ràng' },
  { mandarin: '锻炼', pinyin: 'duànliàn', vietnamese: 'Rèn luyện, tập luyện' },
  { mandarin: '音乐', pinyin: 'yīnyuè', vietnamese: 'Âm nhạc' },
  { mandarin: '公园', pinyin: 'gōngyuán', vietnamese: 'Công viên' },
  { mandarin: '聊天', pinyin: 'liáotiān', vietnamese: 'Trò chuyện' },
  { mandarin: '睡着', pinyin: 'shuìzháo', vietnamese: 'Ngủ thiếp đi' },
  { mandarin: '更', pinyin: 'gèng', vietnamese: 'Hơn, hơn nữa' },
  // Bài 7 (100-111)
  { mandarin: '同事', pinyin: 'tóngshì', vietnamese: 'Đồng nghiệp' },
  { mandarin: '以前', pinyin: 'yǐqián', vietnamese: 'Trước đây' },
  { mandarin: '银行', pinyin: 'yínháng', vietnamese: 'Ngân hàng' },
  { mandarin: '久', pinyin: 'jiǔ', vietnamese: 'Lâu' },
  { mandarin: '感兴趣', pinyin: 'gǎnxìngqù', vietnamese: 'Cảm thấy hứng thú' },
  { mandarin: '结婚', pinyin: 'jiéhūn', vietnamese: 'Kết hôn' },
  { mandarin: '欢迎', pinyin: 'huānyíng', vietnamese: 'Chào mừng, hoan nghênh' },
  { mandarin: '迟到', pinyin: 'chídào', vietnamese: 'Đến muộn' },
  { mandarin: '半', pinyin: 'bàn', vietnamese: 'Một nửa' },
  { mandarin: '接', pinyin: 'jiē', vietnamese: 'Đón, nhận' },
  { mandarin: '刻', pinyin: 'kè', vietnamese: 'Khắc (15 phút)' },
  { mandarin: '差', pinyin: 'chà', vietnamese: 'Thiếu, kém, tồi' },
  // Bài 8 (112-128)
  { mandarin: '又', pinyin: 'yòu', vietnamese: 'Lại (lặp lại)' },
  { mandarin: '满意', pinyin: 'mǎnyì', vietnamese: 'Hài lòng' },
  { mandarin: '电梯', pinyin: 'diàntī', vietnamese: 'Thang máy' },
  { mandarin: '层', pinyin: 'céng', vietnamese: 'Tầng' },
  { mandarin: '害怕', pinyin: 'hàipà', vietnamese: 'Sợ hãi' },
  { mandarin: '熊猫', pinyin: 'xióngmāo', vietnamese: 'Gấu trúc' },
  { mandarin: '见面', pinyin: 'jiànmiàn', vietnamese: 'Gặp mặt' },
  { mandarin: '安静', pinyin: 'ānjìng', vietnamese: 'Yên tĩnh' },
  { mandarin: '可乐', pinyin: 'kělè', vietnamese: 'Coca-Cola' },
  { mandarin: '一会儿', pinyin: 'yīhuìr', vietnamese: 'Một lát, một lúc' },
  { mandarin: '马上', pinyin: 'mǎshàng', vietnamese: 'Ngay lập tức' },
  { mandarin: '洗手间', pinyin: 'xǐshǒujiān', vietnamese: 'Nhà vệ sinh' },
  { mandarin: '老', pinyin: 'lǎo', vietnamese: 'Già, cũ' },
  { mandarin: '几乎', pinyin: 'jīhū', vietnamese: 'Hầu như, gần như' },
  { mandarin: '变化', pinyin: 'biànhuà', vietnamese: 'Thay đổi, biến hóa' },
  { mandarin: '健康', pinyin: 'jiànkāng', vietnamese: 'Sức khỏe' },
  { mandarin: '重要', pinyin: 'zhòngyào', vietnamese: 'Quan trọng' },
  // Bài 9 (129-143)
  { mandarin: '中文', pinyin: 'Zhōngwén', vietnamese: 'Tiếng Trung' },
  { mandarin: '班', pinyin: 'bān', vietnamese: 'Lớp học' },
  { mandarin: '一样', pinyin: 'yīyàng', vietnamese: 'Giống nhau' },
  { mandarin: '大山', pinyin: 'Dàshān', vietnamese: 'Đại Sơn' },
  { mandarin: '李静', pinyin: 'Lǐ Jìng', vietnamese: 'Lý Tĩnh' },
  { mandarin: '最后', pinyin: 'zuìhòu', vietnamese: 'Cuối cùng' },
  { mandarin: '放心', pinyin: 'fàngxīn', vietnamese: 'Yên tâm' },
  { mandarin: '一定', pinyin: 'yīdìng', vietnamese: 'Nhất định' },
  { mandarin: '担心', pinyin: 'dānxīn', vietnamese: 'Lo lắng' },
  { mandarin: '比较', pinyin: 'bǐjiào', vietnamese: 'Khá là, tương đối' },
  { mandarin: '了解', pinyin: 'liǎojiě', vietnamese: 'Hiểu rõ, tìm hiểu' },
  { mandarin: '先', pinyin: 'xiān', vietnamese: 'Trước tiên' },
  { mandarin: '中间', pinyin: 'zhōngjiān', vietnamese: 'Ở giữa' },
  { mandarin: '参加', pinyin: 'cānjiā', vietnamese: 'Tham gia' },
  { mandarin: '影响', pinyin: 'yǐngxiǎng', vietnamese: 'Ảnh hưởng' },
  // Bài 10 (144-158)
  { mandarin: '个子', pinyin: 'gèzi', vietnamese: 'Chiều cao, vóc dáng' },
  { mandarin: '矮', pinyin: 'ǎi', vietnamese: 'Lùn, thấp' },
  { mandarin: '历史', pinyin: 'lìshǐ', vietnamese: 'Lịch sử' },
  { mandarin: '体育', pinyin: 'tǐyù', vietnamese: 'Thể thao, thể dục' },
  { mandarin: '数学', pinyin: 'shùxué', vietnamese: 'Toán học' },
  { mandarin: '方便', pinyin: 'fāngbiàn', vietnamese: 'Thuận tiện, tiện lợi' },
  { mandarin: '自行车', pinyin: 'zìxíngchē', vietnamese: 'Xe đạp' },
  { mandarin: '骑', pinyin: 'qí', vietnamese: 'Cưỡi, đi xe' },
  { mandarin: '旧', pinyin: 'jiù', vietnamese: 'Cũ' },
  { mandarin: '换', pinyin: 'huàn', vietnamese: 'Đổi, thay' },
  { mandarin: '地方', pinyin: 'dìfang', vietnamese: 'Địa phương, nơi chốn' },
  { mandarin: '中介', pinyin: 'zhōngjiè', vietnamese: 'Môi giới, trung gian' },
  { mandarin: '主要', pinyin: 'zhǔyào', vietnamese: 'Chủ yếu' },
  { mandarin: '环境', pinyin: 'huánjìng', vietnamese: 'Môi trường' },
  { mandarin: '附近', pinyin: 'fùjìn', vietnamese: 'Gần đây, lân cận' },
  // Bài 11 (159-176)
  { mandarin: '图书馆', pinyin: 'túshūguǎn', vietnamese: 'Thư viện' },
  { mandarin: '借', pinyin: 'jiè', vietnamese: 'Mượn' },
  { mandarin: '词典', pinyin: 'cídiǎn', vietnamese: 'Từ điển' },
  { mandarin: '还', pinyin: 'huán', vietnamese: 'Trả lại' },
  { mandarin: '灯', pinyin: 'dēng', vietnamese: 'Đèn' },
  { mandarin: '会议', pinyin: 'huìyì', vietnamese: 'Hội nghị, cuộc họp' },
  { mandarin: '结束', pinyin: 'jiéshù', vietnamese: 'Kết thúc, chấm dứt' },
  { mandarin: '忘记', pinyin: 'wàngjì', vietnamese: 'Quên' },
  { mandarin: '空调', pinyin: 'kōngtiáo', vietnamese: 'Máy điều hòa' },
  { mandarin: '关', pinyin: 'guān', vietnamese: 'Đóng, tắt' },
  { mandarin: '地铁', pinyin: 'dìtiě', vietnamese: 'Tàu điện ngầm' },
  { mandarin: '双', pinyin: 'shuāng', vietnamese: 'Đôi, cặp' },
  { mandarin: '筷子', pinyin: 'kuàizi', vietnamese: 'Đũa' },
  { mandarin: '啤酒', pinyin: 'píjiǔ', vietnamese: 'Bia' },
  { mandarin: '口', pinyin: 'kǒu', vietnamese: 'Miệng' },
  { mandarin: '瓶子', pinyin: 'píngzi', vietnamese: 'Cái chai, lọ' },
  { mandarin: '笔记本', pinyin: 'bǐjìběn', vietnamese: 'Máy tính xách tay, sổ tay' },
  { mandarin: '电子邮件', pinyin: 'diànzǐ yóujiàn', vietnamese: 'Thư điện tử, email' },
  { mandarin: '习惯', pinyin: 'xíguàn', vietnamese: 'Thói quen, quen' },
  // Bài 12 (177-190)
  { mandarin: '太阳', pinyin: 'tàiyáng', vietnamese: 'Mặt trời' },
  { mandarin: '西', pinyin: 'xī', vietnamese: 'Phía tây' },
  { mandarin: '生气', pinyin: 'shēngqì', vietnamese: 'Tức giận' },
  { mandarin: '行李箱', pinyin: 'xínglixiāng', vietnamese: 'Vali hành lý' },
  { mandarin: '自己', pinyin: 'zìjǐ', vietnamese: 'Chính mình' },
  { mandarin: '包', pinyin: 'bāo', vietnamese: 'Cái túi, gói, bọc' },
  { mandarin: '发现', pinyin: 'fāxiàn', vietnamese: 'Phát hiện' },
  { mandarin: '护照', pinyin: 'hùzhào', vietnamese: 'Hộ chiếu' },
  { mandarin: '飞机', pinyin: 'fēijī', vietnamese: 'Máy bay' },
  { mandarin: '司机', pinyin: 'sījī', vietnamese: 'Tài xế, lái xe' },
  { mandarin: '教', pinyin: 'jiāo', vietnamese: 'Dạy' },
  { mandarin: '画', pinyin: 'huà', vietnamese: 'Vẽ' },
  { mandarin: '需要', pinyin: 'xūyào', vietnamese: 'Cần, cần phải' },
  { mandarin: '黑板', pinyin: 'hēibǎn', vietnamese: 'Bảng đen' },
  // Bài 13 (191-205)
  { mandarin: '终于', pinyin: 'zhōngyú', vietnamese: 'Cuối cùng, sau cùng' },
  { mandarin: '爷爷', pinyin: 'yéye', vietnamese: 'Ông nội' },
  { mandarin: '礼物', pinyin: 'lǐwù', vietnamese: 'Quà, quà tặng' },
  { mandarin: '奶奶', pinyin: 'nǎinai', vietnamese: 'Bà nội' },
  { mandarin: '遇到', pinyin: 'yùdào', vietnamese: 'Gặp, gặp phải' },
  { mandarin: '一边', pinyin: 'yìbiān', vietnamese: 'Vừa... vừa...' },
  { mandarin: '过去', pinyin: 'guòqù', vietnamese: 'Quá khứ' },
  { mandarin: '一般', pinyin: 'yìbān', vietnamese: 'Bình thường, phổ biến' },
  { mandarin: '愿意', pinyin: 'yuànyì', vietnamese: 'Bằng lòng, sẵn lòng' },
  { mandarin: '起来', pinyin: 'qǐlái', vietnamese: 'Lên (bổ ngữ xu hướng)' },
  { mandarin: '应该', pinyin: 'yīnggāi', vietnamese: 'Nên, phải' },
  { mandarin: '生活', pinyin: 'shēnghuó', vietnamese: 'Cuộc sống, sinh hoạt' },
  { mandarin: '校长', pinyin: 'xiàozhǎng', vietnamese: 'Hiệu trưởng' },
  { mandarin: '坏', pinyin: 'huài', vietnamese: 'Xấu, hỏng, tồi' },
  { mandarin: '经常', pinyin: 'jīngcháng', vietnamese: 'Thường xuyên' },
  // Bài 14 (206-222)
  { mandarin: '打扫', pinyin: 'dǎsǎo', vietnamese: 'Quét dọn, dọn dẹp' },
  { mandarin: '干净', pinyin: 'gānjìng', vietnamese: 'Sạch sẽ' },
  { mandarin: '然后', pinyin: 'ránhòu', vietnamese: 'Sau đó' },
  { mandarin: '冰箱', pinyin: 'bīngxiāng', vietnamese: 'Tủ lạnh' },
  { mandarin: '洗澡', pinyin: 'xǐzǎo', vietnamese: 'Tắm' },
  { mandarin: '节目', pinyin: 'jiémù', vietnamese: 'Chương trình' },
  { mandarin: '月亮', pinyin: 'yuèliang', vietnamese: 'Mặt trăng' },
  { mandarin: '像', pinyin: 'xiàng', vietnamese: 'Giống như' },
  { mandarin: '盘子', pinyin: 'pánzi', vietnamese: 'Cái đĩa' },
  { mandarin: '刮风', pinyin: 'guāfēng', vietnamese: 'Gió thổi, có gió' },
  { mandarin: '叔叔', pinyin: 'shūshu', vietnamese: 'Chú, bác' },
  { mandarin: '阿姨', pinyin: 'āyí', vietnamese: 'Cô, dì, thím' },
  { mandarin: '故事', pinyin: 'gùshi', vietnamese: 'Câu chuyện' },
  { mandarin: '声音', pinyin: 'shēngyīn', vietnamese: 'Âm thanh, tiếng nói' },
  { mandarin: '菜单', pinyin: 'càidān', vietnamese: 'Thực đơn' },
  { mandarin: '简单', pinyin: 'jiǎndān', vietnamese: 'Đơn giản' },
  { mandarin: '香蕉', pinyin: 'xiāngjiāo', vietnamese: 'Chuối' },
  // Bài 15 (223-239)
  { mandarin: '留学', pinyin: 'liúxué', vietnamese: 'Du học' },
  { mandarin: '水平', pinyin: 'shuǐpíng', vietnamese: 'Trình độ' },
  { mandarin: '提高', pinyin: 'tígāo', vietnamese: 'Nâng cao, cải thiện' },
  { mandarin: '练习', pinyin: 'liànxí', vietnamese: 'Luyện tập, bài tập' },
  { mandarin: '完成', pinyin: 'wánchéng', vietnamese: 'Hoàn thành' },
  { mandarin: '句子', pinyin: 'jùzi', vietnamese: 'Câu' },
  { mandarin: '其他', pinyin: 'qítā', vietnamese: 'Cái khác' },
  { mandarin: '发', pinyin: 'fā', vietnamese: 'Gửi, phát ra' },
  { mandarin: '要求', pinyin: 'yāoqiú', vietnamese: 'Yêu cầu' },
  { mandarin: '注意', pinyin: 'zhùyì', vietnamese: 'Chú ý' },
  { mandarin: '小云', pinyin: 'Xiǎoyún', vietnamese: 'Tiểu Vân' },
  { mandarin: '上网', pinyin: 'shàngwǎng', vietnamese: 'Lên mạng' },
  { mandarin: '除了', pinyin: 'chúle', vietnamese: 'Ngoài... ra' },
  { mandarin: '新闻', pinyin: 'xīnwén', vietnamese: 'Tin tức' },
  { mandarin: '花', pinyin: 'huā', vietnamese: 'Tiêu (tiền)' },
  { mandarin: '极了', pinyin: 'jíle', vietnamese: 'Cực kỳ, vô cùng' },
  { mandarin: '节日', pinyin: 'jiérì', vietnamese: 'Ngày lễ, lễ hội' },
  { mandarin: '举行', pinyin: 'jǔxíng', vietnamese: 'Tổ chức' },
  { mandarin: '世界', pinyin: 'shìjiè', vietnamese: 'Thế giới' },
  { mandarin: '街道', pinyin: 'jiēdào', vietnamese: 'Đường phố' },
  { mandarin: '各', pinyin: 'gè', vietnamese: 'Mỗi, các' },
  { mandarin: '文化', pinyin: 'wénhuà', vietnamese: 'Văn hóa' },
  // Bài 16 (240-254)
  { mandarin: '城市', pinyin: 'chéngshì', vietnamese: 'Thành phố' },
  { mandarin: '如果', pinyin: 'rúguǒ', vietnamese: 'Nếu, nếu như' },
  { mandarin: '认为', pinyin: 'rènwéi', vietnamese: 'Cho rằng, nhận thấy' },
  { mandarin: '皮鞋', pinyin: 'píxié', vietnamese: 'Giày da' },
  { mandarin: '帽子', pinyin: 'màozi', vietnamese: 'Cái mũ' },
  { mandarin: '长', pinyin: 'cháng', vietnamese: 'Dài' },
  { mandarin: '可爱', pinyin: 'kě\'ài', vietnamese: 'Đáng yêu, dễ thương' },
  { mandarin: '米', pinyin: 'mǐ', vietnamese: 'Mét, gạo' },
  { mandarin: '公斤', pinyin: 'gōngjīn', vietnamese: 'Kilogram' },
  { mandarin: '鼻子', pinyin: 'bízi', vietnamese: 'Mũi' },
  { mandarin: '头发', pinyin: 'tóufa', vietnamese: 'Tóc' },
  { mandarin: '检查', pinyin: 'jiǎnchá', vietnamese: 'Kiểm tra' },
  { mandarin: '刷牙', pinyin: 'shuāyá', vietnamese: 'Đánh răng' },
  { mandarin: '关系', pinyin: 'guānxì', vietnamese: 'Quan hệ' },
  { mandarin: '别人', pinyin: 'biérén', vietnamese: 'Người khác' },
  { mandarin: '词语', pinyin: 'cíyǔ', vietnamese: 'Từ ngữ' },
  // Bài 17 (255-268)
  { mandarin: '请假', pinyin: 'qǐngjià', vietnamese: 'Xin nghỉ phép' },
  { mandarin: '一共', pinyin: 'yígòng', vietnamese: 'Tổng cộng' },
  { mandarin: '邻居', pinyin: 'línjū', vietnamese: 'Hàng xóm' },
  { mandarin: '后来', pinyin: 'hòulái', vietnamese: 'Sau này, về sau' },
  { mandarin: '爱好', pinyin: 'àihào', vietnamese: 'Sở thích' },
  { mandarin: '办法', pinyin: 'bànfǎ', vietnamese: 'Cách, biện pháp' },
  { mandarin: '饱', pinyin: 'bǎo', vietnamese: 'No' },
  { mandarin: '为了', pinyin: 'wèile', vietnamese: 'Vì, để' },
  { mandarin: '决定', pinyin: 'juédìng', vietnamese: 'Quyết định' },
  { mandarin: '冬天', pinyin: 'dōngtiān', vietnamese: 'Mùa đông' },
  { mandarin: '必须', pinyin: 'bìxū', vietnamese: 'Nhất định phải' },
  { mandarin: '根据', pinyin: 'gēnjù', vietnamese: 'Căn cứ vào, theo' },
  { mandarin: '情况', pinyin: 'qíngkuàng', vietnamese: 'Tình hình' },
  { mandarin: '渴', pinyin: 'kě', vietnamese: 'Khát' },
  // Bài 18 (269-285)
  { mandarin: '向', pinyin: 'xiàng', vietnamese: 'Hướng về, đối với' },
  { mandarin: '万', pinyin: 'wàn', vietnamese: 'Vạn, mười nghìn' },
  { mandarin: '只', pinyin: 'zhī', vietnamese: 'Chỉ (lượng từ)' },
  { mandarin: '嘴', pinyin: 'zuǐ', vietnamese: 'Miệng' },
  { mandarin: '动物', pinyin: 'dòngwù', vietnamese: 'Động vật' },
  { mandarin: '段', pinyin: 'duàn', vietnamese: 'Đoạn (lượng từ)' },
  { mandarin: '不但。。。而且', pinyin: 'bú dàn... ér qiě', vietnamese: 'Không những... mà còn' },
  { mandarin: '有名', pinyin: 'yǒumíng', vietnamese: 'Nổi tiếng' },
  { mandarin: '同意', pinyin: 'tóngyì', vietnamese: 'Đồng ý' },
  { mandarin: '相信', pinyin: 'xiāngxìn', vietnamese: 'Tin tưởng' },
  { mandarin: '关于', pinyin: 'guānyú', vietnamese: 'Về, liên quan đến' },
  { mandarin: '机会', pinyin: 'jīhuì', vietnamese: 'Cơ hội' },
  { mandarin: '国家', pinyin: 'guójiā', vietnamese: 'Quốc gia' },
  { mandarin: '种', pinyin: 'zhǒng', vietnamese: 'Loại, giống' },
  { mandarin: '特点', pinyin: 'tèdiǎn', vietnamese: 'Đặc điểm' },
  { mandarin: '奇怪', pinyin: 'qíguài', vietnamese: 'Kỳ lạ, quái lạ' },
  { mandarin: '地', pinyin: 'de', vietnamese: 'Trợ từ kết cấu' },
  // Bài 19 (286-300)
  { mandarin: '耳朵', pinyin: 'ěrduo', vietnamese: 'Tai, lỗ tai' },
  { mandarin: '脸', pinyin: 'liǎn', vietnamese: 'Mặt' },
  { mandarin: '短', pinyin: 'duǎn', vietnamese: 'Ngắn' },
  { mandarin: '马', pinyin: 'mǎ', vietnamese: 'Ngựa' },
  { mandarin: '张', pinyin: 'zhāng', vietnamese: 'Trương (lượng từ)' },
  { mandarin: '位', pinyin: 'wèi', vietnamese: 'Vị (lượng từ)' },
  { mandarin: '蓝', pinyin: 'lán', vietnamese: 'Màu xanh lam' },
  { mandarin: '秋天', pinyin: 'qiūtiān', vietnamese: 'Mùa thu' },
  { mandarin: '过', pinyin: 'guò', vietnamese: 'Qua, trải qua' },
  { mandarin: '鸟', pinyin: 'niǎo', vietnamese: 'Chim' },
  { mandarin: '哭', pinyin: 'kū', vietnamese: 'Khóc' },
  { mandarin: '黄河', pinyin: 'Huáng Hé', vietnamese: 'Sông Hoàng Hà' },
  { mandarin: '船', pinyin: 'chuán', vietnamese: 'Thuyền' },
  { mandarin: '经过', pinyin: 'jīngguò', vietnamese: 'Đi qua, trải qua' },
  // Bài 20 (301-314)
  { mandarin: '照相机', pinyin: 'zhàoxiàngjī', vietnamese: 'Máy ảnh' },
  { mandarin: '被', pinyin: 'bèi', vietnamese: 'Bị, được' },
  { mandarin: '难过', pinyin: 'nánguò', vietnamese: 'Buồn bã, khó chịu' },
  { mandarin: '东', pinyin: 'dōng', vietnamese: 'Phía đông' },
  { mandarin: '信用卡', pinyin: 'xìnyòngkǎ', vietnamese: 'Thẻ tín dụng' },
  { mandarin: '关心', pinyin: 'guānxīn', vietnamese: 'Quan tâm' },
  { mandarin: '只有。。。才', pinyin: 'zhǐyǒu... cái', vietnamese: 'Chỉ có... mới...' },
  { mandarin: '成绩', pinyin: 'chéngjì', vietnamese: 'Thành tích' },
  { mandarin: '碗', pinyin: 'wǎn', vietnamese: 'Cái chén, bát' },
  { mandarin: '分', pinyin: 'fēn', vietnamese: 'Phút, điểm số' },
  { mandarin: '解决', pinyin: 'jiějué', vietnamese: 'Giải quyết' },
  { mandarin: '试', pinyin: 'shì', vietnamese: 'Thử' },
  { mandarin: '真正', pinyin: 'zhēnzhèng', vietnamese: 'Thực sự, chân chính' },
  { mandarin: '多么', pinyin: 'duōme', vietnamese: 'Biết bao' },
];
