import { HSKWord } from './types';

export const TIENG_TRUNG_5_VOCABULARY: HSKWord[] = [
  // Bài 1
  { mandarin: '图书馆', pinyin: 'túshūguǎn', vietnamese: 'thư viện' },
  { mandarin: '借', pinyin: 'jiè', vietnamese: 'mượn' },
  { mandarin: '还', pinyin: 'huán', vietnamese: 'trả' },
  { mandarin: '关', pinyin: 'guān', vietnamese: 'đóng/tắt' },
  { mandarin: '会议', pinyin: 'huìyì', vietnamese: 'cuộc họp' },
  { mandarin: '词典', pinyin: 'cídiǎn', vietnamese: 'từ điển' },
  { mandarin: '困', pinyin: 'kùn', vietnamese: 'buồn ngủ' },
  { mandarin: '躺', pinyin: 'tǎng', vietnamese: 'nằm' },
  { mandarin: '过期', pinyin: 'guòqī', vietnamese: 'quá hạn' },
  { mandarin: '空调', pinyin: 'kōngtiáo', vietnamese: 'máy điều hòa' },
  { mandarin: '结束', pinyin: 'jiéshù', vietnamese: 'kết thúc' },
  { mandarin: '忘记', pinyin: 'wàngjì', vietnamese: 'quên' },
  { mandarin: '左右', pinyin: 'zuǒyòu', vietnamese: 'khoảng' },
  { mandarin: '心意', pinyin: 'xīnyì', vietnamese: 'tấm lòng' },
  { mandarin: '敬', pinyin: 'jìng', vietnamese: 'kính (mời)' },
  { mandarin: '双', pinyin: 'shuāng', vietnamese: 'đôi' },
  { mandarin: '筷子', pinyin: 'kuàizi', vietnamese: 'đũa' },
  { mandarin: '啤酒', pinyin: 'píjiǔ', vietnamese: 'bia' },
  { mandarin: '瓶子', pinyin: 'píngzi', vietnamese: 'chai / lọ' },
  { mandarin: '留', pinyin: 'liú', vietnamese: 'ở lại / giữ lại' },
  { mandarin: '忙碌', pinyin: 'mánglù', vietnamese: 'bận rộn' },
  { mandarin: '习惯', pinyin: 'xíguàn', vietnamese: 'thói quen' },
  { mandarin: '地铁', pinyin: 'dìtiě', vietnamese: 'tàu điện ngầm' },
  { mandarin: '笔记本', pinyin: 'bǐjìběn', vietnamese: 'vở / máy tính xách tay' },
  { mandarin: '客户', pinyin: 'kèhù', vietnamese: 'khách hàng' },
  { mandarin: '联系', pinyin: 'liánxì', vietnamese: 'liên lạc' },
  { mandarin: '领工资', pinyin: 'lǐng gōngzī', vietnamese: 'nhận lương' },
  { mandarin: '坏', pinyin: 'huài', vietnamese: 'cực kì, quá sức （adj + 坏）' },
  { mandarin: '赶', pinyin: 'gǎn', vietnamese: 'khẩn trương, vội vã' },
  // Bài 2
  { mandarin: '机票', pinyin: 'jī piào', vietnamese: 'Vé máy bay' },
  { mandarin: '期末', pinyin: 'qī mò', vietnamese: 'Cuối kỳ' },
  { mandarin: '赶', pinyin: 'gǎn', vietnamese: 'Đuổi theo, vội vã, tranh thủ (thời gian)' },
  { mandarin: '为了', pinyin: 'wèi le', vietnamese: 'Để, vì, để cho (biểu thị mục đích)' },
  { mandarin: '生气', pinyin: 'shēngqì', vietnamese: 'tức giận' },
  { mandarin: '堵车', pinyin: 'dǔchē', vietnamese: 'tắc xe' },
  { mandarin: '发现', pinyin: 'fāxiàn', vietnamese: 'phát hiện' },
  { mandarin: '护照', pinyin: 'hùzhào', vietnamese: 'hộ chiếu' },
  { mandarin: '只好', pinyin: 'zhǐhǎo', vietnamese: 'đành phải' },
  { mandarin: '司机', pinyin: 'sījī', vietnamese: 'tài xế' },
  { mandarin: '行李箱', pinyin: 'xínglixiāng', vietnamese: 'vali' },
  { mandarin: '估计', pinyin: 'gūjì', vietnamese: 'ước tính, đoán' },
  { mandarin: '报告', pinyin: 'bàogào', vietnamese: 'báo cáo' },
  { mandarin: '交', pinyin: 'jiāo', vietnamese: 'nộp' },
  { mandarin: '注意', pinyin: 'zhùyì', vietnamese: 'chú ý' },
  { mandarin: '争取', pinyin: 'zhēngqǔ', vietnamese: 'tranh thủ, cố gắng' },
  { mandarin: '实习', pinyin: 'shíxí', vietnamese: 'thực tập' },
  { mandarin: '留学', pinyin: 'liúxué', vietnamese: 'du học' },
  { mandarin: '研究生', pinyin: 'yánjiūshēng', vietnamese: 'nghiên cứu sinh' },
  { mandarin: '需要', pinyin: 'xūyào', vietnamese: 'cần' },
  { mandarin: '黑板', pinyin: 'hēibǎn', vietnamese: 'bảng đen' },
  { mandarin: '答卷', pinyin: 'dájuàn', vietnamese: 'tờ bài làm, bài thi' },
  { mandarin: '紧张', pinyin: 'jǐnzhāng', vietnamese: 'lo lắng, căng thẳng' },
  { mandarin: '其中', pinyin: 'qízhōng', vietnamese: 'trong đó' },
  { mandarin: '翻译', pinyin: 'fānyì', vietnamese: 'dịch, biên dịch' },
  // Bài 3
  { mandarin: '麻烦', pinyin: 'máfàn', vietnamese: 'phiền phức' },
  { mandarin: '顾', pinyin: 'gù', vietnamese: 'lo, chú ý' },
  { mandarin: '留下', pinyin: 'liúxià', vietnamese: 'để lại, ở lại' },
  { mandarin: '终于', pinyin: 'zhōngyú', vietnamese: 'cuối cùng, rốt cuộc' },
  { mandarin: '电梯', pinyin: 'diàntī', vietnamese: 'thang máy' },
  { mandarin: '楼梯', pinyin: 'lóutī', vietnamese: 'thang bộ' },
  { mandarin: '贴', pinyin: 'tiē', vietnamese: 'dán' },
  { mandarin: '对面', pinyin: 'duìmiàn', vietnamese: 'đối diện' },
  { mandarin: '商场', pinyin: 'shāngchǎng', vietnamese: 'trung tâm mua sắm / mall' },
  { mandarin: '购物', pinyin: 'gòuwù', vietnamese: 'mua sắm' },
  { mandarin: '外套', pinyin: 'wàitào', vietnamese: 'áo khoác, áo choàng' },
  { mandarin: '包裹', pinyin: 'bāoguǒ', vietnamese: 'bưu phẩm' },
  { mandarin: '关照', pinyin: 'guānzhào', vietnamese: 'chiếu cố' },
  { mandarin: '加入', pinyin: 'jiārù', vietnamese: 'gia nhập' },
  { mandarin: '经营部', pinyin: 'jīngyíngbù', vietnamese: 'Phòng kinh doanh' },
  { mandarin: '遇到', pinyin: 'yùdào', vietnamese: 'gặp phải' },
  { mandarin: '尝试', pinyin: 'chángshì', vietnamese: 'thử (thưởng thức)' },
  { mandarin: '经验', pinyin: 'jīngyàn', vietnamese: 'kinh nghiệm' },
  { mandarin: '熟悉', pinyin: 'shúxī', vietnamese: 'làm quen' },
  { mandarin: '快递', pinyin: 'kuàidì', vietnamese: 'chuyển phát nhanh' },
  { mandarin: '深刻', pinyin: 'shēnkè', vietnamese: 'sâu sắc' },
  { mandarin: '印象', pinyin: 'yìnxiàng', vietnamese: 'ấn tượng' },
  { mandarin: '缆车', pinyin: 'lǎnchē', vietnamese: 'cáp treo' },
  { mandarin: '吃力', pinyin: 'chīlì', vietnamese: 'cố sức (mệt), vất vả' },
  { mandarin: '过去', pinyin: 'guòqù', vietnamese: 'qua bên kia, đó/ quá khứ' },
  { mandarin: '愿意', pinyin: 'yuànyì', vietnamese: 'sẵn lòng' },
  // Bài 4
  { mandarin: '总是', pinyin: 'zǒngshì', vietnamese: 'luôn luôn' },
  { mandarin: '叔叔', pinyin: 'shūshu', vietnamese: 'chú' },
  { mandarin: '阿姨', pinyin: 'āyí', vietnamese: 'dì' },
  { mandarin: '来不及', pinyin: 'láibují', vietnamese: 'không kịp' },
  { mandarin: '来得及', pinyin: 'láidejí', vietnamese: 'kịp' },
  { mandarin: '打扫', pinyin: 'dǎsǎo', vietnamese: 'quét dọn' },
  { mandarin: '冰箱', pinyin: 'bīngxiāng', vietnamese: 'tủ lạnh' },
  { mandarin: '布置', pinyin: 'bùzhì', vietnamese: 'trang trí, sắp xếp' },
  { mandarin: '纪念', pinyin: 'jìniàn', vietnamese: 'kỷ niệm' },
  { mandarin: '庆祝', pinyin: 'qìngzhù', vietnamese: 'ăn mừng' },
  { mandarin: '举办', pinyin: 'jǔbàn', vietnamese: 'tổ chức' },
  { mandarin: '了解', pinyin: 'liǎojiě', vietnamese: 'tìm hiểu' },
  { mandarin: '自助餐', pinyin: 'zìzhùcān', vietnamese: 'buffet' },
  { mandarin: '菜单', pinyin: 'càidān', vietnamese: 'thực đơn' },
  { mandarin: '一般', pinyin: 'yìbān', vietnamese: 'thông thường' },
  { mandarin: '简单', pinyin: 'jiǎndān', vietnamese: 'đơn giản' },
  { mandarin: '西红柿', pinyin: 'xīhóngshì', vietnamese: 'cà chua' },
  { mandarin: '炒', pinyin: 'chǎo', vietnamese: 'xào' },
  { mandarin: '月亮', pinyin: 'yuèliang', vietnamese: 'mặt trăng' },
  { mandarin: '盘子', pinyin: 'pánzi', vietnamese: 'cái dĩa' },
  // Bài 5
  // Bài 6
  // Bài 7
  // Bài 8
  // Bài 9
  // Bài 10
];
