import { HSKWord } from './types';

export const TIENG_TRUNG_4_VOCABULARY: HSKWord[] = [
  // Bài 1 (20 từ)
  { mandarin: '高铁', pinyin: 'gāotiě', vietnamese: 'cao tốc' },
  { mandarin: '游戏', pinyin: 'yóuxì', vietnamese: 'trò chơi' },
  { mandarin: '作业', pinyin: 'zuòyè', vietnamese: 'bài tập' },
  { mandarin: '天堂', pinyin: 'tiāntáng', vietnamese: 'thiên đàng' },
  { mandarin: '苏杭', pinyin: 'Sū Háng', vietnamese: 'Tô Châu, Hàng Châu' },
  { mandarin: '地图', pinyin: 'dìtú', vietnamese: 'bản đồ' },
  { mandarin: '要紧', pinyin: 'yàojǐn', vietnamese: 'quan trọng/gấp' },
  { mandarin: '期末', pinyin: 'qīmò', vietnamese: 'cuối kì' },
  { mandarin: '着急', pinyin: 'zháojí', vietnamese: 'lo lắng, vội vàng' },
  { mandarin: '用功', pinyin: 'yònggōng', vietnamese: 'siêng năng, chăm chỉ' },
  { mandarin: '提', pinyin: 'tí', vietnamese: 'nêu ra, xách, nâng' },
  { mandarin: '周末', pinyin: 'zhōumò', vietnamese: 'cuối tuần' },
  { mandarin: '打算', pinyin: 'dǎsuàn', vietnamese: 'dự định' },
  { mandarin: '风景', pinyin: 'fēngjǐng', vietnamese: 'phong cảnh' },
  { mandarin: '一直', pinyin: 'yìzhí', vietnamese: 'luôn, một mạch' },
  { mandarin: '出发', pinyin: 'chūfā', vietnamese: 'xuất phát' },
  { mandarin: '水果', pinyin: 'shuǐguǒ', vietnamese: 'trái cây' },
  { mandarin: '面包', pinyin: 'miànbāo', vietnamese: 'bánh mì' },
  { mandarin: '香蕉', pinyin: 'xiāngjiāo', vietnamese: 'chuối' },
  { mandarin: '担心', pinyin: 'dānxīn', vietnamese: 'lo lắng' },
  // Bài 2 (18 từ)
  { mandarin: '拿', pinyin: 'ná', vietnamese: 'cầm, lấy' },
  { mandarin: '玩儿', pinyin: 'wánr', vietnamese: 'chơi' },
  { mandarin: '该', pinyin: 'gāi', vietnamese: 'nên, cần' },
  { mandarin: '辆', pinyin: 'liàng', vietnamese: 'lượng từ chiếc (xe)' },
  { mandarin: '楼', pinyin: 'lóu', vietnamese: 'lầu, tòa nhà' },
  { mandarin: '把', pinyin: 'bǎ', vietnamese: 'lượng từ (cho vật có cán/tay cầm)' },
  { mandarin: '伞', pinyin: 'sǎn', vietnamese: 'dù, ô' },
  { mandarin: '照相机', pinyin: 'zhàoxiāngjī', vietnamese: 'máy ảnh' },
  { mandarin: '嗯', pinyin: 'ēn', vietnamese: 'ừ, à (đồng ý)' },
  { mandarin: '极了', pinyin: 'jí le', vietnamese: 'cực kỳ, hết sức' },
  { mandarin: '特别', pinyin: 'tèbié', vietnamese: 'đặc biệt' },
  { mandarin: '不过', pinyin: 'búguò', vietnamese: 'nhưng mà, chẳng qua là' },
  { mandarin: '容易', pinyin: 'róngyì', vietnamese: 'dễ dàng' },
  { mandarin: '难', pinyin: 'nán', vietnamese: 'khó' },
  { mandarin: '也许', pinyin: 'yěxǔ', vietnamese: 'có lẽ, có thể' },
  { mandarin: '其实', pinyin: 'qíshí', vietnamese: 'thật ra, thực tế' },
  { mandarin: '香山', pinyin: 'Xiāngshān', vietnamese: 'Hương Sơn' },
  { mandarin: '红叶', pinyin: 'hóngyè', vietnamese: 'lá đỏ (lá phong)' },
  // Bài 3 (16 từ)
  { mandarin: '着', pinyin: 'zhe', vietnamese: 'đang (trạng thái)' },
  { mandarin: '条', pinyin: 'tiáo', vietnamese: 'lượng từ (vật dài)' },
  { mandarin: '还是', pinyin: 'háishi', vietnamese: 'hay là (câu hỏi)' },
  { mandarin: '保安', pinyin: 'bǎo\'ān', vietnamese: 'bảo vệ' },
  { mandarin: '叔叔', pinyin: 'shūshu', vietnamese: 'chú' },
  { mandarin: '约', pinyin: 'yuē', vietnamese: 'hẹn' },
  { mandarin: '稍等', pinyin: 'shāoděng', vietnamese: 'đợi một chút' },
  { mandarin: '电视台', pinyin: 'diànshìtái', vietnamese: 'đài truyền hình' },
  { mandarin: '记者', pinyin: 'jìzhě', vietnamese: 'phóng viên' },
  { mandarin: '采访', pinyin: 'cǎifǎng', vietnamese: 'phỏng vấn' },
  { mandarin: '通', pinyin: 'tōng', vietnamese: 'thông, xong' },
  { mandarin: '裤子', pinyin: 'kùzi', vietnamese: 'quần' },
  { mandarin: '记得', pinyin: 'jìde', vietnamese: 'nhớ' },
  { mandarin: '衬衫', pinyin: 'chènshān', vietnamese: 'áo sơ mi' },
  { mandarin: '或者', pinyin: 'huòzhě', vietnamese: 'hoặc là (câu kể)' },
  { mandarin: '哎', pinyin: 'āi', vietnamese: 'này, chà' },
  // Bài 4 (17 từ)
  { mandarin: '站', pinyin: 'zhàn', vietnamese: 'đứng' },
  { mandarin: '说话', pinyin: 'shuōhuà', vietnamese: 'nói chuyện' },
  { mandarin: '笑', pinyin: 'xiào', vietnamese: 'cười' },
  { mandarin: '帮', pinyin: 'bāng', vietnamese: 'giúp đỡ' },
  { mandarin: '家', pinyin: 'jiā', vietnamese: 'nhà, căn (lượng từ)' },
  { mandarin: '超市', pinyin: 'chāoshì', vietnamese: 'siêu thị' },
  { mandarin: '懂', pinyin: 'dǒng', vietnamese: 'hiểu' },
  { mandarin: '成语', pinyin: 'chéngyǔ', vietnamese: 'thành ngữ' },
  { mandarin: '热情', pinyin: 'rèqíng', vietnamese: 'nhiệt tình' },
  { mandarin: '总是', pinyin: 'zǒngshì', vietnamese: 'luôn luôn' },
  { mandarin: '经常', pinyin: 'jīngcháng', vietnamese: 'thường xuyên' },
  { mandarin: '饿', pinyin: 'è', vietnamese: 'đói' },
  { mandarin: '蛋糕', pinyin: 'dàngāo', vietnamese: 'bánh ngọt' },
  { mandarin: '年轻', pinyin: 'niánqīng', vietnamese: 'trẻ trung' },
  { mandarin: '哈哈', pinyin: 'hāhā', vietnamese: 'ha ha' },
  { mandarin: '可乐', pinyin: 'kělè', vietnamese: 'coca cola' },
  { mandarin: '又', pinyin: 'yòu', vietnamese: 'lại (vừa... vừa...)' },
  // Bài 5 (15 từ)
  { mandarin: '了', pinyin: 'le', vietnamese: 'rồi (trợ từ)' },
  { mandarin: '吃药', pinyin: 'chī yào', vietnamese: 'uống thuốc' },
  { mandarin: '不用', pinyin: 'bú yòng', vietnamese: 'không cần' },
  { mandarin: '夏天', pinyin: 'xiàtiān', vietnamese: 'mùa hè' },
  { mandarin: '每天', pinyin: 'měitiān', vietnamese: 'mỗi ngày' },
  { mandarin: '晚饭', pinyin: 'wǎnfàn', vietnamese: 'bữa tối' },
  { mandarin: '照顾', pinyin: 'zhàogù', vietnamese: 'chăm sóc' },
  { mandarin: '发烧', pinyin: 'fāshāo', vietnamese: 'sốt' },
  { mandarin: '感冒', pinyin: 'gǎnmào', vietnamese: 'cảm cúm' },
  { mandarin: '多', pinyin: 'duō', vietnamese: 'nhiều' },
  { mandarin: '保重', pinyin: 'bǎozhòng', vietnamese: 'bảo trọng' },
  { mandarin: '下次', pinyin: 'xiàcì', vietnamese: 'lần sau' },
  { mandarin: '公斤', pinyin: 'gōngjīn', vietnamese: 'kilogram' },
  { mandarin: '亲爱', pinyin: 'qīn\'ài', vietnamese: 'thân ái' },
  { mandarin: '为', pinyin: 'wèi', vietnamese: 'vì, cho' },
  // Bài 6 (16 từ)
  { mandarin: '帮忙', pinyin: 'bāngmáng', vietnamese: 'giúp đỡ' },
  { mandarin: '聊天', pinyin: 'liáotiān', vietnamese: 'nói chuyện' },
  { mandarin: '担心', pinyin: 'dānxīn', vietnamese: 'lo lắng' },
  { mandarin: '眼镜', pinyin: 'yǎnjìng', vietnamese: 'mắt kính' },
  { mandarin: '突然', pinyin: 'tùrán', vietnamese: 'đột nhiên' },
  { mandarin: '刚才', pinyin: 'gāngcái', vietnamese: 'vừa nãy' },
  { mandarin: '大衣', pinyin: 'dàyī', vietnamese: 'áo khoác' },
  { mandarin: '口袋', pinyin: 'kǒudài', vietnamese: 'túi' },
  { mandarin: '煮饭', pinyin: 'zhǔfàn', vietnamese: 'nấu cơm' },
  { mandarin: '卧室', pinyin: 'wòshì', vietnamese: 'phòng ngủ' },
  { mandarin: '公园', pinyin: 'gōngyuán', vietnamese: 'công viên' },
  { mandarin: '越来越', pinyin: 'yuèláiyuè', vietnamese: 'càng ngày càng' },
  { mandarin: '哪里哪里', pinyin: 'nǎlinǎli', vietnamese: 'đâu có đâu có (khiêm tốn)' },
  { mandarin: '发音', pinyin: 'fāyīn', vietnamese: 'phát âm' },
  { mandarin: '互相', pinyin: 'hùxiāng', vietnamese: 'lẫn nhau' },
  { mandarin: '练习', pinyin: 'liànxí', vietnamese: 'luyện tập' },
  // Bài 7 (14 từ)
  { mandarin: '同事', pinyin: 'tóngshì', vietnamese: 'đồng nghiệp' },
  { mandarin: '唱歌', pinyin: 'chànggē', vietnamese: 'hát' },
  { mandarin: '欢迎', pinyin: 'huānyíng', vietnamese: 'hoan nghênh' },
  { mandarin: '以前', pinyin: 'yǐqián', vietnamese: 'trước đây' },
  { mandarin: '然后', pinyin: 'ránhòu', vietnamese: 'sau đó' },
  { mandarin: '周日', pinyin: 'zhōurì', vietnamese: 'chủ nhật' },
  { mandarin: '久', pinyin: 'jiǔ', vietnamese: 'lâu' },
  { mandarin: '半', pinyin: 'bàn', vietnamese: 'một nửa' },
  { mandarin: '结婚', pinyin: 'jiéhūn', vietnamese: 'kết hôn' },
  { mandarin: '业余', pinyin: 'yèyú', vietnamese: 'nghiệp dư' },
  { mandarin: '感兴趣', pinyin: 'gǎnxìngqù', vietnamese: 'có hứng thú' },
  { mandarin: '书法展', pinyin: 'shūfǎzhǎn', vietnamese: 'triển lãm thư pháp' },
  { mandarin: '刻', pinyin: 'kè', vietnamese: 'khắc (15 phút)' },
  { mandarin: '差', pinyin: 'chà', vietnamese: 'kém, thiếu' },
  // Bài 8 (17 từ)
  { mandarin: '健康', pinyin: 'jiànkāng', vietnamese: 'sức khỏe' },
  { mandarin: '安静', pinyin: 'ānjìng', vietnamese: 'yên tĩnh' },
  { mandarin: '旁边', pinyin: 'pángbiān', vietnamese: 'bên cạnh' },
  { mandarin: '再', pinyin: 'zài', vietnamese: 'lại (tương lai)' },
  { mandarin: '又', pinyin: 'yòu', vietnamese: 'lại (quá khứ)' },
  { mandarin: '几乎', pinyin: 'jīhū', vietnamese: 'hầu như' },
  { mandarin: '变化', pinyin: 'biànhuà', vietnamese: 'thay đổi' },
  { mandarin: '重要', pinyin: 'zhòngyào', vietnamese: 'quan trọng' },
  { mandarin: '优美', pinyin: 'yōuměi', vietnamese: 'ưu mỹ, đẹp' },
  { mandarin: '随便', pinyin: 'suíbiàn', vietnamese: 'tùy ý' },
  { mandarin: '珍珠奶茶', pinyin: 'zhēnzhū nǎichá', vietnamese: 'trà sữa trân châu' },
  { mandarin: '电梯', pinyin: 'diàntī', vietnamese: 'thang máy' },
  { mandarin: '吵', pinyin: 'chǎo', vietnamese: 'ồn ào' },
  { mandarin: '另', pinyin: 'lìng', vietnamese: 'cái khác' },
  { mandarin: '层', pinyin: 'céng', vietnamese: 'tầng' },
  { mandarin: '害怕', pinyin: 'hàipà', vietnamese: 'sợ hãi' },
  { mandarin: '中介', pinyin: 'zhōngjiè', vietnamese: 'môi giới' },
  // Bài 9 (18 từ)
  { mandarin: '可以', pinyin: 'kěyǐ', vietnamese: 'có thể' },
  { mandarin: '听力', pinyin: 'tīnglì', vietnamese: 'nghe hiểu' },
  { mandarin: '一样', pinyin: 'yíyàng', vietnamese: 'giống nhau' },
  { mandarin: '参加', pinyin: 'cānjiā', vietnamese: 'tham gia' },
  { mandarin: '上网', pinyin: 'shàngwǎng', vietnamese: 'lên mạng' },
  { mandarin: '中文', pinyin: 'Zhōngwén', vietnamese: 'tiếng Trung' },
  { mandarin: '阅读', pinyin: 'yuèdú', vietnamese: 'đọc hiểu' },
  { mandarin: '棒', pinyin: 'bàng', vietnamese: 'giỏi, tuyệt' },
  { mandarin: '口语', pinyin: 'kǒuyǔ', vietnamese: 'khẩu ngữ' },
  { mandarin: '之前', pinyin: 'zhīqián', vietnamese: 'trước khi' },
  { mandarin: '曾', pinyin: 'céng', vietnamese: 'từng' },
  { mandarin: '迷', pinyin: 'mí', vietnamese: 'mê, fan' },
  { mandarin: '比较', pinyin: 'bǐjiào', vietnamese: 'so sánh, khá là' },
  { mandarin: '东京', pinyin: 'Dōngjīng', vietnamese: 'Tokyo' },
  { mandarin: '一定', pinyin: 'yídìng', vietnamese: 'nhất định' },
  { mandarin: '日本', pinyin: 'Rìběn', vietnamese: 'Nhật Bản' },
  { mandarin: '当', pinyin: 'dāng', vietnamese: 'làm (nghề)' },
  { mandarin: '导游', pinyin: 'dǎoyóu', vietnamese: 'hướng dẫn viên' },
];